$axure.loadCurrentPage({
  "url":"news_updates_1.html",
  "generationDate":new Date(1479235423636.49),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"08d7c08b81f54622bca78c6969e80dc5",
    "type":"Axure:Page",
    "name":"News Updates",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b147babde7834c5d80be67f4a49d87fc",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"e163cbb4cef54461ad56955f368f2e96"},
{
          "id":"b2e24ae280514be6a0f7eccf53a9b805",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":293,
              "y":142},
            "size":{
              "width":1022,
              "height":588},
            "borderWidth":"-1",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":0,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b586b23f61c4f969d039bc62ffec873",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":293,
                  "y":142},
                "size":{
                  "width":1022,
                  "height":588},
                "borderWidth":"-1",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":0,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/list_of_ambassadors/u11.png"}},
{
          "id":"fa4229a818304ecb8f20c64469727105",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Regular', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":294,
              "y":72},
            "size":{
              "width":157,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f1bb9a2bbad4739ba0185d302efd574",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Regular', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":294,
                  "y":72},
                "size":{
                  "width":157,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cfdd493c15f4b0fbbcf611321201538",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1996C7},
            "location":{
              "x":293,
              "y":142},
            "size":{
              "width":1022,
              "height":35},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54374e6d3a4849b2a2806dab9a4775b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1996C7},
                "location":{
                  "x":293,
                  "y":142},
                "size":{
                  "width":1022,
                  "height":35},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/list_of_ambassadors/u15.png"}},
{
          "id":"7fb87094ec2747b785e1cb140fb4cab6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1270,
              "y":25},
            "size":{
              "width":50,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1586387c8124e0eb9c42786eb232318",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1270,
                  "y":25},
                "size":{
                  "width":50,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37badc0c61174a4e8ab699fcad824687",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":303,
              "y":200},
            "size":{
              "width":987,
              "height":255}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa2dff89341e409fa7639b797caf1bba",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1996C7,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "size":{
                  "width":430,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"296a84963ca14848a07013e425cd7228",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1996C7,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "size":{
                      "width":430,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates_1/u20.png"}},
{
              "id":"f536382567424dc08eb9b1f92f6b5556",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":195},
                "size":{
                  "width":430,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6979252fa0924f69840b0bd29f40b55c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":195},
                    "size":{
                      "width":430,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates_1/u52.png"}},
{
              "id":"05ac645783a94470b02195dff4d1e325",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":225},
                "size":{
                  "width":430,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"47a8cf266de64d0f9d1a56442cce70ce",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":225},
                    "size":{
                      "width":430,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates_1/u56.png"}},
{
              "id":"2712c85751c24529bc02d731bce2d269",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1996C7,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":430,
                  "y":0},
                "size":{
                  "width":557,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9327f6493d8143978ad07a4a57ab46aa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1996C7,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":430,
                      "y":0},
                    "size":{
                      "width":557,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates_1/u22.png"}},
{
              "id":"dc9c10f6be874b80acc9d8af8a14465d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":430,
                  "y":195},
                "size":{
                  "width":557,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5fd59565240043049e28d25a118774d4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":430,
                      "y":195},
                    "size":{
                      "width":557,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates_1/u54.png"}},
{
              "id":"ffad79fdd2db4f8980ce3d1193f8f6f4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":430,
                  "y":225},
                "size":{
                  "width":557,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1cb6081c928c4dd0a2baa68909ea94a5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":430,
                      "y":225},
                    "size":{
                      "width":557,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates_1/u58.png"}},
{
              "id":"f8137901b6b34536beed603aa9c95491",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":25},
                "size":{
                  "width":430,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d96bd8ee88cc4350925263227c0b56d2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":25},
                    "size":{
                      "width":430,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates_1/u24.png"}},
{
              "id":"a3e62543ee2a44b5ab2afdef68a74dfd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":430,
                  "y":25},
                "size":{
                  "width":557,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e3996a5704984fbcab1ddbe83f263eed",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":430,
                      "y":25},
                    "size":{
                      "width":557,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates_1/u26.png"}},
{
              "id":"d470a41c44ec4f80a67f066bb49ea0c8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":430,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5475efd7d12c49f9aba47cf3eccc2750",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":50},
                    "size":{
                      "width":430,
                      "height":20},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates_1/u28.png"}},
{
              "id":"a7b6e05b9522436e87ef3096268553d4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":430,
                  "y":50},
                "size":{
                  "width":557,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7f84b2b3feb142b79c17597e8b211c0d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":430,
                      "y":50},
                    "size":{
                      "width":557,
                      "height":20},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates_1/u30.png"}},
{
              "id":"7a7acfe90a75411eaca50a7e83ad4575",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":70},
                "size":{
                  "width":430,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5bd553f511ae4799b91900b15c9f8729",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":70},
                    "size":{
                      "width":430,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates_1/u24.png"}},
{
              "id":"3d27263965884168992949ac00ae40b4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":430,
                  "y":70},
                "size":{
                  "width":557,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9319e9fee39942eca279520554798a2a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":430,
                      "y":70},
                    "size":{
                      "width":557,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates_1/u26.png"}},
{
              "id":"a745ef5a4e324f74bc1061b0e5103423",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":95},
                "size":{
                  "width":430,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"09195e37636e492c9fd6a305b4e5d8ad",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":95},
                    "size":{
                      "width":430,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates_1/u24.png"}},
{
              "id":"88a264480ce2445f937c800341637cbb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":430,
                  "y":95},
                "size":{
                  "width":557,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c3760290fe734afeb03a2f390184d79c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":430,
                      "y":95},
                    "size":{
                      "width":557,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates_1/u26.png"}},
{
              "id":"b132599a52a4490093d7fd9758507d4c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":430,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e0c65c1d842b473683cee6433802f7f1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":430,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates_1/u24.png"}},
{
              "id":"f12adba306e546b3810fbf4e3a13a6b8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":430,
                  "y":120},
                "size":{
                  "width":557,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"54921efc7c034923a4d8c159ebd629aa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":430,
                      "y":120},
                    "size":{
                      "width":557,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates_1/u26.png"}},
{
              "id":"ad1717f5d503430cae63f1038b62dee1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":170},
                "size":{
                  "width":430,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7333ce7dd87d4a679681f54367d3c4cb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":170},
                    "size":{
                      "width":430,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates_1/u24.png"}},
{
              "id":"0e80ff22cb5a48948f5cd3fc335373d3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":430,
                  "y":170},
                "size":{
                  "width":557,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"62d6ebef0e1c4ef786ba09c80a475467",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":430,
                      "y":170},
                    "size":{
                      "width":557,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates_1/u26.png"}},
{
              "id":"da84be11e4a5437ebe3caa63bb606e58",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":145},
                "size":{
                  "width":430,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"18641507d29c4f5887f7c1363ff9c4b0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":145},
                    "size":{
                      "width":430,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates_1/u24.png"}},
{
              "id":"5ef7ffb5129c4831a796ef10bfcb1381",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":430,
                  "y":145},
                "size":{
                  "width":557,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f80b8423807a42b2bf93932494e774b8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":430,
                      "y":145},
                    "size":{
                      "width":557,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates_1/u26.png"}}]},
{
          "id":"5f536308492b4bf6b9f2759956b5aa64",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":54},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11b2f47323534f76a46da7f0f802fae1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":54},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"71e9cf6f35a2494a9ac42a6c34826f7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":96},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31b3b2c3c672456d848009a5d8f457bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":96},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Surveys in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"surveys_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"9b6b1beb862b4a5f840950b978a1c7ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":137},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab410acd89484d23acfc6c20e5a118c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":137},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Leads in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"leads_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"b1bdade3bb074b149e8638a7d4f3da30",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1996C7,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":179},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"321613970ae64c1aa7d98d917b95f94a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1996C7,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":179},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News Updates in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news_updates_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"b983225665764e40bff57b0c6411385b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":221},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7679049e0ccf4cf19e2f54cbf804387a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":221},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Events in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"events_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}}]}},
  "masters":{
    "e163cbb4cef54461ad56955f368f2e96":{
      "packageId":"e163cbb4cef54461ad56955f368f2e96",
      "type":"Axure:Master",
      "name":"main",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1affd31496854a90aaf55cb21b7c1027",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF9F9F9},
              "size":{
                "width":1366,
                "height":768}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6b795c4f50714ccc8e66f16ce98c2618",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF9F9F9},
                  "size":{
                    "width":1366,
                    "height":768}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u1.png"}},
{
            "id":"cee52dc11a8744b0a43052d502487fd5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF1996C7},
              "size":{
                "width":1366,
                "height":50},
              "borderWidth":"-1",
              "outerShadow":{
                "on":true,
                "offsetX":0,
                "offsetY":1,
                "blurRadius":5,
                "color":{
                  "r":0,
                  "g":0,
                  "b":0,
                  "a":0.349019607843137}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bde88dba9c1a4e2988a327f1c196765c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF1996C7},
                  "size":{
                    "width":1366,
                    "height":50},
                  "borderWidth":"-1",
                  "outerShadow":{
                    "on":true,
                    "offsetX":0,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.349019607843137}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u3.png"}},
{
            "id":"56fbb49b18bd46129591d114da88345e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF0E5570},
              "location":{
                "x":0,
                "y":50},
              "size":{
                "width":1366,
                "height":4},
              "borderWidth":"-1",
              "outerShadow":{
                "on":true,
                "offsetX":0,
                "offsetY":1,
                "blurRadius":5,
                "color":{
                  "r":0,
                  "g":0,
                  "b":0,
                  "a":0.349019607843137}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b9154b46c7af49f6b3c8fa13b5e2aa9c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0E5570},
                  "location":{
                    "x":0,
                    "y":50},
                  "size":{
                    "width":1366,
                    "height":4},
                  "borderWidth":"-1",
                  "outerShadow":{
                    "on":true,
                    "offsetX":0,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.349019607843137}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u5.png"}},
{
            "id":"8e7b142cf5d5486cbc949c1ae82f56d1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF212121},
              "location":{
                "x":0,
                "y":54},
              "size":{
                "width":250,
                "height":714},
              "borderWidth":"-1",
              "outerShadow":{
                "on":true,
                "offsetX":2,
                "offsetY":0,
                "blurRadius":5,
                "color":{
                  "r":0,
                  "g":0,
                  "b":0,
                  "a":0.349019607843137}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59e38fb539e04bb29cde628389cf5bd8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF212121},
                  "location":{
                    "x":0,
                    "y":54},
                  "size":{
                    "width":250,
                    "height":714},
                  "borderWidth":"-1",
                  "outerShadow":{
                    "on":true,
                    "offsetX":2,
                    "offsetY":0,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.349019607843137}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u7.png"}},
{
            "id":"dcdfff1ef73440ecb729883ed1488cee",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"28px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":31,
                "y":7},
              "size":{
                "width":140,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ee24b8d3672d4a26a4e0d5b9d8a0528a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"28px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":31,
                    "y":7},
                  "size":{
                    "width":140,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "b147babde7834c5d80be67f4a49d87fc":{
      "scriptId":"u0",
      "1affd31496854a90aaf55cb21b7c1027":{
        "scriptId":"u1"},
      "6b795c4f50714ccc8e66f16ce98c2618":{
        "scriptId":"u2"},
      "cee52dc11a8744b0a43052d502487fd5":{
        "scriptId":"u3"},
      "bde88dba9c1a4e2988a327f1c196765c":{
        "scriptId":"u4"},
      "56fbb49b18bd46129591d114da88345e":{
        "scriptId":"u5"},
      "b9154b46c7af49f6b3c8fa13b5e2aa9c":{
        "scriptId":"u6"},
      "8e7b142cf5d5486cbc949c1ae82f56d1":{
        "scriptId":"u7"},
      "59e38fb539e04bb29cde628389cf5bd8":{
        "scriptId":"u8"},
      "dcdfff1ef73440ecb729883ed1488cee":{
        "scriptId":"u9"},
      "ee24b8d3672d4a26a4e0d5b9d8a0528a":{
        "scriptId":"u10"}},
    "b2e24ae280514be6a0f7eccf53a9b805":{
      "scriptId":"u11"},
    "3b586b23f61c4f969d039bc62ffec873":{
      "scriptId":"u12"},
    "fa4229a818304ecb8f20c64469727105":{
      "scriptId":"u13"},
    "0f1bb9a2bbad4739ba0185d302efd574":{
      "scriptId":"u14"},
    "6cfdd493c15f4b0fbbcf611321201538":{
      "scriptId":"u15"},
    "54374e6d3a4849b2a2806dab9a4775b2":{
      "scriptId":"u16"},
    "7fb87094ec2747b785e1cb140fb4cab6":{
      "scriptId":"u17"},
    "e1586387c8124e0eb9c42786eb232318":{
      "scriptId":"u18"},
    "37badc0c61174a4e8ab699fcad824687":{
      "scriptId":"u19"},
    "fa2dff89341e409fa7639b797caf1bba":{
      "scriptId":"u20"},
    "296a84963ca14848a07013e425cd7228":{
      "scriptId":"u21"},
    "2712c85751c24529bc02d731bce2d269":{
      "scriptId":"u22"},
    "9327f6493d8143978ad07a4a57ab46aa":{
      "scriptId":"u23"},
    "f8137901b6b34536beed603aa9c95491":{
      "scriptId":"u24"},
    "d96bd8ee88cc4350925263227c0b56d2":{
      "scriptId":"u25"},
    "a3e62543ee2a44b5ab2afdef68a74dfd":{
      "scriptId":"u26"},
    "e3996a5704984fbcab1ddbe83f263eed":{
      "scriptId":"u27"},
    "d470a41c44ec4f80a67f066bb49ea0c8":{
      "scriptId":"u28"},
    "5475efd7d12c49f9aba47cf3eccc2750":{
      "scriptId":"u29"},
    "a7b6e05b9522436e87ef3096268553d4":{
      "scriptId":"u30"},
    "7f84b2b3feb142b79c17597e8b211c0d":{
      "scriptId":"u31"},
    "7a7acfe90a75411eaca50a7e83ad4575":{
      "scriptId":"u32"},
    "5bd553f511ae4799b91900b15c9f8729":{
      "scriptId":"u33"},
    "3d27263965884168992949ac00ae40b4":{
      "scriptId":"u34"},
    "9319e9fee39942eca279520554798a2a":{
      "scriptId":"u35"},
    "a745ef5a4e324f74bc1061b0e5103423":{
      "scriptId":"u36"},
    "09195e37636e492c9fd6a305b4e5d8ad":{
      "scriptId":"u37"},
    "88a264480ce2445f937c800341637cbb":{
      "scriptId":"u38"},
    "c3760290fe734afeb03a2f390184d79c":{
      "scriptId":"u39"},
    "b132599a52a4490093d7fd9758507d4c":{
      "scriptId":"u40"},
    "e0c65c1d842b473683cee6433802f7f1":{
      "scriptId":"u41"},
    "f12adba306e546b3810fbf4e3a13a6b8":{
      "scriptId":"u42"},
    "54921efc7c034923a4d8c159ebd629aa":{
      "scriptId":"u43"},
    "da84be11e4a5437ebe3caa63bb606e58":{
      "scriptId":"u44"},
    "18641507d29c4f5887f7c1363ff9c4b0":{
      "scriptId":"u45"},
    "5ef7ffb5129c4831a796ef10bfcb1381":{
      "scriptId":"u46"},
    "f80b8423807a42b2bf93932494e774b8":{
      "scriptId":"u47"},
    "ad1717f5d503430cae63f1038b62dee1":{
      "scriptId":"u48"},
    "7333ce7dd87d4a679681f54367d3c4cb":{
      "scriptId":"u49"},
    "0e80ff22cb5a48948f5cd3fc335373d3":{
      "scriptId":"u50"},
    "62d6ebef0e1c4ef786ba09c80a475467":{
      "scriptId":"u51"},
    "f536382567424dc08eb9b1f92f6b5556":{
      "scriptId":"u52"},
    "6979252fa0924f69840b0bd29f40b55c":{
      "scriptId":"u53"},
    "dc9c10f6be874b80acc9d8af8a14465d":{
      "scriptId":"u54"},
    "5fd59565240043049e28d25a118774d4":{
      "scriptId":"u55"},
    "05ac645783a94470b02195dff4d1e325":{
      "scriptId":"u56"},
    "47a8cf266de64d0f9d1a56442cce70ce":{
      "scriptId":"u57"},
    "ffad79fdd2db4f8980ce3d1193f8f6f4":{
      "scriptId":"u58"},
    "1cb6081c928c4dd0a2baa68909ea94a5":{
      "scriptId":"u59"},
    "5f536308492b4bf6b9f2759956b5aa64":{
      "scriptId":"u60"},
    "11b2f47323534f76a46da7f0f802fae1":{
      "scriptId":"u61"},
    "71e9cf6f35a2494a9ac42a6c34826f7f":{
      "scriptId":"u62"},
    "31b3b2c3c672456d848009a5d8f457bc":{
      "scriptId":"u63"},
    "9b6b1beb862b4a5f840950b978a1c7ae":{
      "scriptId":"u64"},
    "ab410acd89484d23acfc6c20e5a118c1":{
      "scriptId":"u65"},
    "b1bdade3bb074b149e8638a7d4f3da30":{
      "scriptId":"u66"},
    "321613970ae64c1aa7d98d917b95f94a":{
      "scriptId":"u67"},
    "b983225665764e40bff57b0c6411385b":{
      "scriptId":"u68"},
    "7679049e0ccf4cf19e2f54cbf804387a":{
      "scriptId":"u69"}}});