$axure.loadCurrentPage({
  "url":"options_-_details.html",
  "generationDate":new Date(1470822510978.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2465153e33aa4727bf6a1d1be9f44e22",
    "type":"Axure:Page",
    "name":"Options - Details",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e7a262b522284df4b0918f50c6d532b9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":-43}},
          "adaptiveStyles":{
},
          "masterId":"866c22c904d0473f85c124c9890df389"},
{
          "id":"841cce0d009b440ca79949a6d41852d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4CAF50,
              "opacity":1},
            "location":{
              "x":190,
              "y":160},
            "size":{
              "width":280,
              "height":450},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7c22e605cf7406da1abf5945160f660",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4CAF50,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":160},
                "size":{
                  "width":280,
                  "height":450},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/options_-_details/u5.png"}},
{
          "id":"547d984a6cdb476b887a1f58c347808f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":540},
            "size":{
              "width":280,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/options_-_news_updates/u7_line.png"}},
{
          "id":"0e45dbebb5fe4a5598cf858e38fce49b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "location":{
              "x":193,
              "y":254},
            "size":{
              "width":22,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38c705095a0d4c90a95923d30102223b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "location":{
                  "x":193,
                  "y":254},
                "size":{
                  "width":22,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/options_-_profile/u5.png"}},
{
          "id":"6c4aaf7796df4c7497ba93add09c0fae",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "location":{
              "x":181,
              "y":103},
            "size":{
              "width":295,
              "height":43},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":5,
              "color":{
                "r":94,
                "g":94,
                "b":94,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8254199a66a44fde931929895163f87f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "location":{
                  "x":181,
                  "y":103},
                "size":{
                  "width":295,
                  "height":43},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":5,
                  "color":{
                    "r":94,
                    "g":94,
                    "b":94,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/options/u5.png"}},
{
          "id":"7c4873ea81d443929c22c6e360d92a89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "fontSize":"17px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xDDFFFFFF,
              "opacity":0.866666674613953},
            "baseStyle":"6e631585fe0e401a93235178bc877cb7",
            "fill":{
              "fillType":"solid",
              "color":0xFF8445AD},
            "location":{
              "x":220,
              "y":112},
            "size":{
              "width":113,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"915081ce2fe44076b27ca45c02d1ded6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "fontSize":"17px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xDDFFFFFF,
                  "opacity":0.866666674613953},
                "baseStyle":"6e631585fe0e401a93235178bc877cb7",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8445AD},
                "location":{
                  "x":220,
                  "y":112},
                "size":{
                  "width":113,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/options_-_news_updates/u12.png"}},
{
          "id":"b022fca8480c4c5db413d86463fc9763",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "verticalAlignment":"middle",
            "baseStyle":"f434fc19aed0486cb28659f79fc585db",
            "lineSpacing":"20px",
            "location":{
              "x":198,
              "y":400},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b60d30fe1c6b4e6f83a22a8bf22145fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "verticalAlignment":"middle",
                "baseStyle":"f434fc19aed0486cb28659f79fc585db",
                "lineSpacing":"20px",
                "location":{
                  "x":198,
                  "y":400},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3928f2eae674066a73c48430718f529",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":500,
              "y":209},
            "size":{
              "width":295,
              "height":385},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcbbea251a314391bb498d4b01042b26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":500,
                  "y":209},
                "size":{
                  "width":295,
                  "height":385},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"52c4a708139b4d61b0a1d74670191547",
          "label":"Menu Icon",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "location":{
              "x":181,
              "y":104},
            "size":{
              "width":38,
              "height":33},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c492234b8eb54e87a10adf4382dc1310",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "location":{
                  "x":181,
                  "y":104},
                "size":{
                  "width":38,
                  "height":33},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1<br> (If state of Unidentified equals Unidentified)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["d8495c5424bb4a1da3455bb885390dfa"]}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["d8495c5424bb4a1da3455bb885390dfa"],
                      "panelIndex":0}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]},
{
                  "description":"Case 2<br> (Else If state of Unidentified equals Unidentified)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["d8495c5424bb4a1da3455bb885390dfa"]}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["d8495c5424bb4a1da3455bb885390dfa"],
                      "panelIndex":0}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/options/menu_icon_u9.png"}},
{
          "id":"f06137b6a55748649b0d5709e2723c14",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2E2925,
              "opacity":1},
            "location":{
              "x":201,
              "y":168},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce0642c93add495f913dc289123ec49f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2E2925,
                  "opacity":1},
                "location":{
                  "x":201,
                  "y":168},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"808a8cd673194b72bfa442c523cf16d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":204,
              "y":197},
            "size":{
              "width":254,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf340f5fcbf94cfba471a834784c2ea6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":204,
                  "y":197},
                "size":{
                  "width":254,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c47b253c179417db1f537e4349d6528",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFBCE01},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFBCE01}},
              "mouseDown":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF003366}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF8445AD},
            "location":{
              "x":410,
              "y":560},
            "size":{
              "width":47,
              "height":38},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae56aa199428471b873a0bc223d5a716",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFBCE01},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFBCE01}},
                  "mouseDown":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF003366}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8445AD},
                "location":{
                  "x":410,
                  "y":560},
                "size":{
                  "width":47,
                  "height":38},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Options - News Updates in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"options_-_news_updates.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/options_-_details/u24.png",
            "mouseOver~":"images/options_-_details/u24_mouseOver.png",
            "mouseDown~":"images/options_-_details/u24_mouseDown.png"}},
{
          "id":"add7f705483e4ad3af7337a7ba1a01a5",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":181,
              "y":144},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"544d37a2e2394581bf716549979131cd",
              "label":"Invisible",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"4c0237ca3afd4574b406dbb643866f2e",
              "label":"visible",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d39829ba51964761b8a36bcb86c8590c",
                  "label":"",
                  "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF8445AD},
                    "size":{
                      "width":229,
                      "height":482}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7efd7650d4ca49a2a1788eb7642c0b0b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF8445AD},
                        "size":{
                          "width":229,
                          "height":482}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/options/u14.png"}},
{
                  "id":"8f4dddf42139420388dae4f0998c450a",
                  "label":"",
                  "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "verticalAlignment":"middle",
                    "baseStyle":"f434fc19aed0486cb28659f79fc585db",
                    "lineSpacing":"20px",
                    "location":{
                      "x":17,
                      "y":255},
                    "size":{
                      "width":74,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"66725dd21b074a9ca34904693e89e6c2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "verticalAlignment":"middle",
                        "baseStyle":"f434fc19aed0486cb28659f79fc585db",
                        "lineSpacing":"20px",
                        "location":{
                          "x":17,
                          "y":255},
                        "size":{
                          "width":74,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5a8a4118cc4441bcb920a2a2941733a3",
                  "label":"",
                  "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"71c1d4ea3e41457a908011c1d00fb7d5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/options/u18.png"}},
{
                  "id":"9e35f97f5c8e466c83aa67ec25d6c77f",
                  "label":"",
                  "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":61,
                      "y":12},
                    "size":{
                      "width":168,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"81771c38820748939b5bc8546467b528",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":61,
                          "y":12},
                        "size":{
                          "width":168,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d4afef6f75da484cbd7507cde6e42050",
                  "label":"",
                  "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "location":{
                      "x":12,
                      "y":12},
                    "size":{
                      "width":39,
                      "height":39}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a6990169f9a44bcdb9fa16b6bc804750",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "location":{
                          "x":12,
                          "y":12},
                        "size":{
                          "width":39,
                          "height":39}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/options/u22.png"}},
{
                  "id":"7eb2b4d330d04ce685dc8cd3f02e34f5",
                  "label":"",
                  "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "verticalAlignment":"bottom",
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "location":{
                      "x":0,
                      "y":62},
                    "size":{
                      "width":229,
                      "height":63},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2054427a51c644488ac3aea9eb5e4988",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "verticalAlignment":"bottom",
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "location":{
                          "x":0,
                          "y":62},
                        "size":{
                          "width":229,
                          "height":63},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/options/u24.png"}},
{
                  "id":"16a307a4f33a44d7a60c97b68e59cd61",
                  "label":"",
                  "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":57,
                      "y":75},
                    "size":{
                      "width":162,
                      "height":38}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"af687cd9b35a4f21ba1afbebf6864017",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":57,
                          "y":75},
                        "size":{
                          "width":162,
                          "height":38}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3304dc2ae48f443e840919f79fb57bd0",
                  "label":"",
                  "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "verticalAlignment":"bottom",
                    "location":{
                      "x":12,
                      "y":75},
                    "size":{
                      "width":35,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3560d9c93d714e0e91ce445485ba7800",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "verticalAlignment":"bottom",
                        "location":{
                          "x":12,
                          "y":75},
                        "size":{
                          "width":35,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/options/u28.png"}},
{
                  "id":"35b89668f6c34ec894a004db085172bc",
                  "label":"",
                  "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "location":{
                      "x":0,
                      "y":125},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cf33f2535aee4ba294ffa204ba654a81",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "location":{
                          "x":0,
                          "y":125},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/options/u18.png"}},
{
                  "id":"cfab710f5e4d419eb076ddfb514ecb83",
                  "label":"",
                  "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":61,
                      "y":137},
                    "size":{
                      "width":158,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0aa841f5c80447c787f29f0b1b16125c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":61,
                          "y":137},
                        "size":{
                          "width":158,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7136e990d47b46cabbc2573fa5e22704",
                  "label":"",
                  "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":12,
                      "y":137},
                    "size":{
                      "width":39,
                      "height":39}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cafb7d1265424bb1bf254256fdd42e8a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":12,
                          "y":137},
                        "size":{
                          "width":39,
                          "height":39}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/options/u34.png"}},
{
                  "id":"21349755c1e24d148a848a84d8fc0a6e",
                  "label":"",
                  "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "location":{
                      "x":0,
                      "y":187},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b7fe2c1e57f14420918786a75898d8c1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "location":{
                          "x":0,
                          "y":187},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/options/u18.png"}},
{
                  "id":"84ded73654064a458193af2327704947",
                  "label":"",
                  "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":61,
                      "y":199},
                    "size":{
                      "width":158,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d75c1d3bc4154e06bbccc707fa33d319",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":61,
                          "y":199},
                        "size":{
                          "width":158,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e588d592de39455e8525e68491670fe3",
                  "label":"",
                  "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":12,
                      "y":199},
                    "size":{
                      "width":39,
                      "height":39}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a33fd1175bcf4ab68e66579f1df1c6f6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":12,
                          "y":199},
                        "size":{
                          "width":39,
                          "height":39}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/options/u40.png"}},
{
                  "id":"7f01bc70096a45a2ba7b38ec0da92524",
                  "label":"",
                  "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                  "panelIndex":1,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"188a6d67e48f4e15a2dd134ed17d2e6e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Options - Profile in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"options_-_profile.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/options/u42.png"}},
{
                  "id":"d810e721be8c4361af189b6105051379",
                  "label":"",
                  "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                  "panelIndex":1,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":1,
                      "y":62},
                    "size":{
                      "width":229,
                      "height":64},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2f795f4ce1c74b6797fe12dc7d4f3a86",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":1,
                          "y":62},
                        "size":{
                          "width":229,
                          "height":64},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Options - News Updates in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"options_-_news_updates.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f5e9f7a2963a47fab34a90377f02d7e2",
                  "label":"",
                  "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                  "panelIndex":1,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":1,
                      "y":125},
                    "size":{
                      "width":229,
                      "height":64},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5935d31015a44209a72312d1dd68f25a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"add7f705483e4ad3af7337a7ba1a01a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":1,
                          "y":125},
                        "size":{
                          "width":229,
                          "height":64},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Options - Change Password in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"options_-_change_password.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"a78382f0c1a64775bbf19b413b70a2ee",
          "label":"Menu Icon",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "location":{
              "x":181,
              "y":104},
            "size":{
              "width":38,
              "height":33},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"393a96e183f84a689ad31183d355dc96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "location":{
                  "x":181,
                  "y":104},
                "size":{
                  "width":38,
                  "height":33},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1<br> (If state of (Dynamic Panel) equals Invisible)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["add7f705483e4ad3af7337a7ba1a01a5"]}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["add7f705483e4ad3af7337a7ba1a01a5"],
                      "panelIndex":0}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set (Dynamic Panel) to visible",
                      "panelsToStates":[{
                          "panelPath":["add7f705483e4ad3af7337a7ba1a01a5"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]},
{
                  "description":"Case 2<br> (Else If state of (Dynamic Panel) equals visible)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["add7f705483e4ad3af7337a7ba1a01a5"]}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["add7f705483e4ad3af7337a7ba1a01a5"],
                      "panelIndex":1}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set (Dynamic Panel) to Invisible",
                      "panelsToStates":[{
                          "panelPath":["add7f705483e4ad3af7337a7ba1a01a5"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/options/menu_icon_u9.png"}}]}},
  "masters":{
    "866c22c904d0473f85c124c9890df389":{
      "packageId":"866c22c904d0473f85c124c9890df389",
      "type":"Axure:Master",
      "name":"frame-plain",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"786c97fb188e44ee8e7e5f4a26a54118",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":90,
                "y":-43},
              "size":{
                "width":469,
                "height":813}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cff2973955f54ebe8c64abe06b548aee",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":90,
                    "y":-43},
                  "size":{
                    "width":469,
                    "height":813}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/splash/u0.png"}},
{
            "id":"67400802aab24ac38de05902cd4eb835",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF9FAF5},
              "location":{
                "x":181,
                "y":103},
              "size":{
                "width":295,
                "height":523},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eea47f19de544c8b962b75de32a1caf9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF9FAF5},
                  "location":{
                    "x":181,
                    "y":103},
                  "size":{
                    "width":295,
                    "height":523},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/options/u3.png"}}]}}},
  "objectPaths":{
    "e7a262b522284df4b0918f50c6d532b9":{
      "scriptId":"u0",
      "786c97fb188e44ee8e7e5f4a26a54118":{
        "scriptId":"u1"},
      "cff2973955f54ebe8c64abe06b548aee":{
        "scriptId":"u2"},
      "67400802aab24ac38de05902cd4eb835":{
        "scriptId":"u3"},
      "eea47f19de544c8b962b75de32a1caf9":{
        "scriptId":"u4"}},
    "841cce0d009b440ca79949a6d41852d1":{
      "scriptId":"u5"},
    "e7c22e605cf7406da1abf5945160f660":{
      "scriptId":"u6"},
    "547d984a6cdb476b887a1f58c347808f":{
      "scriptId":"u7"},
    "0e45dbebb5fe4a5598cf858e38fce49b":{
      "scriptId":"u8"},
    "38c705095a0d4c90a95923d30102223b":{
      "scriptId":"u9"},
    "6c4aaf7796df4c7497ba93add09c0fae":{
      "scriptId":"u10"},
    "8254199a66a44fde931929895163f87f":{
      "scriptId":"u11"},
    "7c4873ea81d443929c22c6e360d92a89":{
      "scriptId":"u12"},
    "915081ce2fe44076b27ca45c02d1ded6":{
      "scriptId":"u13"},
    "b022fca8480c4c5db413d86463fc9763":{
      "scriptId":"u14"},
    "b60d30fe1c6b4e6f83a22a8bf22145fd":{
      "scriptId":"u15"},
    "f3928f2eae674066a73c48430718f529":{
      "scriptId":"u16"},
    "bcbbea251a314391bb498d4b01042b26":{
      "scriptId":"u17"},
    "52c4a708139b4d61b0a1d74670191547":{
      "scriptId":"u18"},
    "c492234b8eb54e87a10adf4382dc1310":{
      "scriptId":"u19"},
    "f06137b6a55748649b0d5709e2723c14":{
      "scriptId":"u20"},
    "ce0642c93add495f913dc289123ec49f":{
      "scriptId":"u21"},
    "808a8cd673194b72bfa442c523cf16d5":{
      "scriptId":"u22"},
    "bf340f5fcbf94cfba471a834784c2ea6":{
      "scriptId":"u23"},
    "5c47b253c179417db1f537e4349d6528":{
      "scriptId":"u24"},
    "ae56aa199428471b873a0bc223d5a716":{
      "scriptId":"u25"},
    "add7f705483e4ad3af7337a7ba1a01a5":{
      "scriptId":"u26"},
    "d39829ba51964761b8a36bcb86c8590c":{
      "scriptId":"u27"},
    "7efd7650d4ca49a2a1788eb7642c0b0b":{
      "scriptId":"u28"},
    "8f4dddf42139420388dae4f0998c450a":{
      "scriptId":"u29"},
    "66725dd21b074a9ca34904693e89e6c2":{
      "scriptId":"u30"},
    "5a8a4118cc4441bcb920a2a2941733a3":{
      "scriptId":"u31"},
    "71c1d4ea3e41457a908011c1d00fb7d5":{
      "scriptId":"u32"},
    "9e35f97f5c8e466c83aa67ec25d6c77f":{
      "scriptId":"u33"},
    "81771c38820748939b5bc8546467b528":{
      "scriptId":"u34"},
    "d4afef6f75da484cbd7507cde6e42050":{
      "scriptId":"u35"},
    "a6990169f9a44bcdb9fa16b6bc804750":{
      "scriptId":"u36"},
    "7eb2b4d330d04ce685dc8cd3f02e34f5":{
      "scriptId":"u37"},
    "2054427a51c644488ac3aea9eb5e4988":{
      "scriptId":"u38"},
    "16a307a4f33a44d7a60c97b68e59cd61":{
      "scriptId":"u39"},
    "af687cd9b35a4f21ba1afbebf6864017":{
      "scriptId":"u40"},
    "3304dc2ae48f443e840919f79fb57bd0":{
      "scriptId":"u41"},
    "3560d9c93d714e0e91ce445485ba7800":{
      "scriptId":"u42"},
    "35b89668f6c34ec894a004db085172bc":{
      "scriptId":"u43"},
    "cf33f2535aee4ba294ffa204ba654a81":{
      "scriptId":"u44"},
    "cfab710f5e4d419eb076ddfb514ecb83":{
      "scriptId":"u45"},
    "0aa841f5c80447c787f29f0b1b16125c":{
      "scriptId":"u46"},
    "7136e990d47b46cabbc2573fa5e22704":{
      "scriptId":"u47"},
    "cafb7d1265424bb1bf254256fdd42e8a":{
      "scriptId":"u48"},
    "21349755c1e24d148a848a84d8fc0a6e":{
      "scriptId":"u49"},
    "b7fe2c1e57f14420918786a75898d8c1":{
      "scriptId":"u50"},
    "84ded73654064a458193af2327704947":{
      "scriptId":"u51"},
    "d75c1d3bc4154e06bbccc707fa33d319":{
      "scriptId":"u52"},
    "e588d592de39455e8525e68491670fe3":{
      "scriptId":"u53"},
    "a33fd1175bcf4ab68e66579f1df1c6f6":{
      "scriptId":"u54"},
    "7f01bc70096a45a2ba7b38ec0da92524":{
      "scriptId":"u55"},
    "188a6d67e48f4e15a2dd134ed17d2e6e":{
      "scriptId":"u56"},
    "d810e721be8c4361af189b6105051379":{
      "scriptId":"u57"},
    "2f795f4ce1c74b6797fe12dc7d4f3a86":{
      "scriptId":"u58"},
    "f5e9f7a2963a47fab34a90377f02d7e2":{
      "scriptId":"u59"},
    "5935d31015a44209a72312d1dd68f25a":{
      "scriptId":"u60"},
    "a78382f0c1a64775bbf19b413b70a2ee":{
      "scriptId":"u61"},
    "393a96e183f84a689ad31183d355dc96":{
      "scriptId":"u62"}}});