$axure.loadCurrentPage({
  "url":"confirm_payment.html",
  "generationDate":new Date(1470822546770.97),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"337a5dd3fcf84a25850e4f6215c29931",
    "type":"Axure:Page",
    "name":"Confirm Payment",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e7a262b522284df4b0918f50c6d532b9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":-43}},
          "adaptiveStyles":{
},
          "masterId":"866c22c904d0473f85c124c9890df389"},
{
          "id":"841cce0d009b440ca79949a6d41852d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4CAF50,
              "opacity":1},
            "location":{
              "x":181,
              "y":174},
            "size":{
              "width":295,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7c22e605cf7406da1abf5945160f660",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4CAF50,
                  "opacity":1},
                "location":{
                  "x":181,
                  "y":174},
                "size":{
                  "width":295,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/choose_processing/u20.png"}},
{
          "id":"547d984a6cdb476b887a1f58c347808f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":181,
              "y":197},
            "size":{
              "width":295,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/choose_processing/u22_line.png"}},
{
          "id":"0e45dbebb5fe4a5598cf858e38fce49b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "location":{
              "x":193,
              "y":254},
            "size":{
              "width":22,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38c705095a0d4c90a95923d30102223b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "location":{
                  "x":193,
                  "y":254},
                "size":{
                  "width":22,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/payment/u8.png"}},
{
          "id":"6c4aaf7796df4c7497ba93add09c0fae",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "location":{
              "x":181,
              "y":103},
            "size":{
              "width":295,
              "height":43},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":5,
              "color":{
                "r":94,
                "g":94,
                "b":94,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8254199a66a44fde931929895163f87f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "location":{
                  "x":181,
                  "y":103},
                "size":{
                  "width":295,
                  "height":43},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":5,
                  "color":{
                    "r":94,
                    "g":94,
                    "b":94,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/payment/u10.png"}},
{
          "id":"7c4873ea81d443929c22c6e360d92a89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "fontSize":"17px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xDDFFFFFF,
              "opacity":0.866666674613953},
            "baseStyle":"6e631585fe0e401a93235178bc877cb7",
            "location":{
              "x":220,
              "y":112},
            "size":{
              "width":70,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"915081ce2fe44076b27ca45c02d1ded6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "fontSize":"17px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xDDFFFFFF,
                  "opacity":0.866666674613953},
                "baseStyle":"6e631585fe0e401a93235178bc877cb7",
                "location":{
                  "x":220,
                  "y":112},
                "size":{
                  "width":70,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21da2d11d5c5456cbd86ad66f51aaa16",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "verticalAlignment":"middle",
            "baseStyle":"f434fc19aed0486cb28659f79fc585db",
            "lineSpacing":"20px",
            "location":{
              "x":198,
              "y":222},
            "size":{
              "width":117,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9018ce1e7ac43679b02a60309510725",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "verticalAlignment":"middle",
                "baseStyle":"f434fc19aed0486cb28659f79fc585db",
                "lineSpacing":"20px",
                "location":{
                  "x":198,
                  "y":222},
                "size":{
                  "width":117,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5d8e7a06f83469abc2535f93872cab0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "verticalAlignment":"middle",
            "baseStyle":"f434fc19aed0486cb28659f79fc585db",
            "lineSpacing":"20px",
            "location":{
              "x":198,
              "y":281},
            "size":{
              "width":88,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6537b41bbe584626a118fe39e247844d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "verticalAlignment":"middle",
                "baseStyle":"f434fc19aed0486cb28659f79fc585db",
                "lineSpacing":"20px",
                "location":{
                  "x":198,
                  "y":281},
                "size":{
                  "width":88,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"004db746b30f4bdba5c17e6e5c07234a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "verticalAlignment":"middle",
            "baseStyle":"f434fc19aed0486cb28659f79fc585db",
            "lineSpacing":"20px",
            "location":{
              "x":198,
              "y":340},
            "size":{
              "width":92,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"112a93713756440a99aacd4f9947a74c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "verticalAlignment":"middle",
                "baseStyle":"f434fc19aed0486cb28659f79fc585db",
                "lineSpacing":"20px",
                "location":{
                  "x":198,
                  "y":340},
                "size":{
                  "width":92,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b022fca8480c4c5db413d86463fc9763",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "verticalAlignment":"middle",
            "baseStyle":"f434fc19aed0486cb28659f79fc585db",
            "lineSpacing":"20px",
            "location":{
              "x":198,
              "y":400},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b60d30fe1c6b4e6f83a22a8bf22145fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "verticalAlignment":"middle",
                "baseStyle":"f434fc19aed0486cb28659f79fc585db",
                "lineSpacing":"20px",
                "location":{
                  "x":198,
                  "y":400},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99dd5b67db744d87b084d476abd9315a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "verticalAlignment":"middle",
            "baseStyle":"f434fc19aed0486cb28659f79fc585db",
            "lineSpacing":"20px",
            "location":{
              "x":237,
              "y":410},
            "size":{
              "width":35,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"274c705727304796928be8ab0fd12f2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "verticalAlignment":"middle",
                "baseStyle":"f434fc19aed0486cb28659f79fc585db",
                "lineSpacing":"20px",
                "location":{
                  "x":237,
                  "y":410},
                "size":{
                  "width":35,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c19da6321ce4f7e919b6530313a46c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"13px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x89000000,
              "opacity":0.537254929542542},
            "baseStyle":"f434fc19aed0486cb28659f79fc585db",
            "lineSpacing":"20px",
            "location":{
              "x":343,
              "y":222},
            "size":{
              "width":47,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e50a915ca9a34830b9b8ab49bff7d120",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"13px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x89000000,
                  "opacity":0.537254929542542},
                "baseStyle":"f434fc19aed0486cb28659f79fc585db",
                "lineSpacing":"20px",
                "location":{
                  "x":343,
                  "y":222},
                "size":{
                  "width":47,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95877fa0105c4b7f9002e34332b20d67",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"13px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x89000000,
              "opacity":0.537254929542542},
            "baseStyle":"f434fc19aed0486cb28659f79fc585db",
            "lineSpacing":"20px",
            "location":{
              "x":343,
              "y":281},
            "size":{
              "width":47,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03e673c1da284ca1b3406c74d85e9d41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"13px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x89000000,
                  "opacity":0.537254929542542},
                "baseStyle":"f434fc19aed0486cb28659f79fc585db",
                "lineSpacing":"20px",
                "location":{
                  "x":343,
                  "y":281},
                "size":{
                  "width":47,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc3a2562670248e791de85760e4d5af5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"13px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x89000000,
              "opacity":0.537254929542542},
            "baseStyle":"f434fc19aed0486cb28659f79fc585db",
            "lineSpacing":"20px",
            "location":{
              "x":343,
              "y":340},
            "size":{
              "width":50,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd30331e382f4740b7b419d75d19b9bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"13px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x89000000,
                  "opacity":0.537254929542542},
                "baseStyle":"f434fc19aed0486cb28659f79fc585db",
                "lineSpacing":"20px",
                "location":{
                  "x":343,
                  "y":340},
                "size":{
                  "width":50,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"137272e97d6e429780c6f15e51f9a5a4",
          "label":"Menu Icon",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "location":{
              "x":181,
              "y":104},
            "size":{
              "width":38,
              "height":33},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cbad76258c840dda97a333391d23602",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "location":{
                  "x":181,
                  "y":104},
                "size":{
                  "width":38,
                  "height":33},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/take_photo/menu_icon_u117.png"}},
{
          "id":"e04c0db181d64c23b25bc45a4ac829c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"13px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x89000000,
              "opacity":0.537254929542542},
            "baseStyle":"f434fc19aed0486cb28659f79fc585db",
            "lineSpacing":"20px",
            "location":{
              "x":210,
              "y":242},
            "size":{
              "width":56,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95e5824d4abd4784a3a90a866864ecc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"13px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x89000000,
                  "opacity":0.537254929542542},
                "baseStyle":"f434fc19aed0486cb28659f79fc585db",
                "lineSpacing":"20px",
                "location":{
                  "x":210,
                  "y":242},
                "size":{
                  "width":56,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c64ddff5bee8435cad38a90eb152a515",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "verticalAlignment":"middle",
            "baseStyle":"f434fc19aed0486cb28659f79fc585db",
            "lineSpacing":"20px",
            "location":{
              "x":343,
              "y":410},
            "size":{
              "width":86,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2d8e30ea2d74e7c8c8651c1e9e6df56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "verticalAlignment":"middle",
                "baseStyle":"f434fc19aed0486cb28659f79fc585db",
                "lineSpacing":"20px",
                "location":{
                  "x":343,
                  "y":410},
                "size":{
                  "width":86,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa14c1f646614ba7b9efc4c001a4f326",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4CAF50},
            "location":{
              "x":350,
              "y":472},
            "size":{
              "width":79,
              "height":58},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8029d0144764983b0b0f78daeb0f5c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4CAF50},
                "location":{
                  "x":350,
                  "y":472},
                "size":{
                  "width":79,
                  "height":58},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/payment/u36.png"}},
{
          "id":"a3231ad3dee44951a0d1b9f30b8109b8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":390},
            "size":{
              "width":239,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/payment/u38_line.png"}},
{
          "id":"332ee6ada9b245b78ad8486ffad8025e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":440},
            "size":{
              "width":239,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/payment/u38_line.png"}},
{
          "id":"172440287ad04f218f2c8ad997bee18e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x63000000},
            "location":{
              "x":180,
              "y":102},
            "size":{
              "width":297,
              "height":527},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db5c4f8629304b0ca2203a8c7c0c278a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x63000000},
                "location":{
                  "x":180,
                  "y":102},
                "size":{
                  "width":297,
                  "height":527},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/confirm_payment/u40.png"}},
{
          "id":"d5bd238e99c4431b86fd374e65b27222",
          "label":"BG Shape",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEEEEEE},
            "location":{
              "x":200,
              "y":274},
            "size":{
              "width":259,
              "height":175},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"3",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":0,
              "blurRadius":7,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bedc5e5c1ff4466a8cf6aee3f29b54be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEEEEEE},
                "location":{
                  "x":200,
                  "y":274},
                "size":{
                  "width":259,
                  "height":175},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"3",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":0,
                  "blurRadius":7,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/confirm_payment/bg_shape_u42.png"}},
{
          "id":"7074d33e99fb43eaa0d5407156eaa849",
          "label":"Title",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "fontSize":"17px",
            "fontWeight":"400",
            "location":{
              "x":219,
              "y":294},
            "size":{
              "width":64,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0e9b8db8d914725969a97f9006707d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "fontSize":"17px",
                "fontWeight":"400",
                "location":{
                  "x":219,
                  "y":294},
                "size":{
                  "width":64,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9636181f5c704a9dbb2379f665dac5a9",
          "label":"Message",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "fontSize":"13px",
            "fontWeight":"400",
            "location":{
              "x":219,
              "y":311},
            "size":{
              "width":214,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74e41e41785347bb85e53a1125df7c0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "fontSize":"13px",
                "fontWeight":"400",
                "location":{
                  "x":219,
                  "y":311},
                "size":{
                  "width":214,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd379305f87f4a2aa43809193e9d05e6",
          "label":"Message",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "fontSize":"13px",
            "fontWeight":"400",
            "location":{
              "x":388,
              "y":382},
            "size":{
              "width":41,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42a04dadf17b48aa8c7d0b537467bef9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "fontSize":"13px",
                "fontWeight":"400",
                "location":{
                  "x":388,
                  "y":382},
                "size":{
                  "width":41,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Payment Feedback in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"payment_feedback.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11a73ecb16c44d64b419081c54bebc98",
          "label":"Message",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "fontSize":"13px",
            "fontWeight":"400",
            "location":{
              "x":319,
              "y":382},
            "size":{
              "width":41,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d78c56a97e449fbb7ce2a95cc982fd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "fontSize":"13px",
                "fontWeight":"400",
                "location":{
                  "x":319,
                  "y":382},
                "size":{
                  "width":41,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3744c677dbb8460ebcda1a0ffcde5804",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":370},
            "size":{
              "width":214,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/confirm_payment/u52_line.png"}}]}},
  "masters":{
    "866c22c904d0473f85c124c9890df389":{
      "packageId":"866c22c904d0473f85c124c9890df389",
      "type":"Axure:Master",
      "name":"frame-plain",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"786c97fb188e44ee8e7e5f4a26a54118",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":90,
                "y":-43},
              "size":{
                "width":469,
                "height":813}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cff2973955f54ebe8c64abe06b548aee",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":90,
                    "y":-43},
                  "size":{
                    "width":469,
                    "height":813}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/splash/u0.png"}},
{
            "id":"67400802aab24ac38de05902cd4eb835",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF9FAF5},
              "location":{
                "x":181,
                "y":103},
              "size":{
                "width":295,
                "height":523},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eea47f19de544c8b962b75de32a1caf9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF9FAF5},
                  "location":{
                    "x":181,
                    "y":103},
                  "size":{
                    "width":295,
                    "height":523},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/take_photo/u3.png"}}]}}},
  "objectPaths":{
    "e7a262b522284df4b0918f50c6d532b9":{
      "scriptId":"u0",
      "786c97fb188e44ee8e7e5f4a26a54118":{
        "scriptId":"u1"},
      "cff2973955f54ebe8c64abe06b548aee":{
        "scriptId":"u2"},
      "67400802aab24ac38de05902cd4eb835":{
        "scriptId":"u3"},
      "eea47f19de544c8b962b75de32a1caf9":{
        "scriptId":"u4"}},
    "841cce0d009b440ca79949a6d41852d1":{
      "scriptId":"u5"},
    "e7c22e605cf7406da1abf5945160f660":{
      "scriptId":"u6"},
    "547d984a6cdb476b887a1f58c347808f":{
      "scriptId":"u7"},
    "0e45dbebb5fe4a5598cf858e38fce49b":{
      "scriptId":"u8"},
    "38c705095a0d4c90a95923d30102223b":{
      "scriptId":"u9"},
    "6c4aaf7796df4c7497ba93add09c0fae":{
      "scriptId":"u10"},
    "8254199a66a44fde931929895163f87f":{
      "scriptId":"u11"},
    "7c4873ea81d443929c22c6e360d92a89":{
      "scriptId":"u12"},
    "915081ce2fe44076b27ca45c02d1ded6":{
      "scriptId":"u13"},
    "21da2d11d5c5456cbd86ad66f51aaa16":{
      "scriptId":"u14"},
    "c9018ce1e7ac43679b02a60309510725":{
      "scriptId":"u15"},
    "d5d8e7a06f83469abc2535f93872cab0":{
      "scriptId":"u16"},
    "6537b41bbe584626a118fe39e247844d":{
      "scriptId":"u17"},
    "004db746b30f4bdba5c17e6e5c07234a":{
      "scriptId":"u18"},
    "112a93713756440a99aacd4f9947a74c":{
      "scriptId":"u19"},
    "b022fca8480c4c5db413d86463fc9763":{
      "scriptId":"u20"},
    "b60d30fe1c6b4e6f83a22a8bf22145fd":{
      "scriptId":"u21"},
    "99dd5b67db744d87b084d476abd9315a":{
      "scriptId":"u22"},
    "274c705727304796928be8ab0fd12f2d":{
      "scriptId":"u23"},
    "7c19da6321ce4f7e919b6530313a46c4":{
      "scriptId":"u24"},
    "e50a915ca9a34830b9b8ab49bff7d120":{
      "scriptId":"u25"},
    "95877fa0105c4b7f9002e34332b20d67":{
      "scriptId":"u26"},
    "03e673c1da284ca1b3406c74d85e9d41":{
      "scriptId":"u27"},
    "fc3a2562670248e791de85760e4d5af5":{
      "scriptId":"u28"},
    "bd30331e382f4740b7b419d75d19b9bc":{
      "scriptId":"u29"},
    "137272e97d6e429780c6f15e51f9a5a4":{
      "scriptId":"u30"},
    "4cbad76258c840dda97a333391d23602":{
      "scriptId":"u31"},
    "e04c0db181d64c23b25bc45a4ac829c4":{
      "scriptId":"u32"},
    "95e5824d4abd4784a3a90a866864ecc0":{
      "scriptId":"u33"},
    "c64ddff5bee8435cad38a90eb152a515":{
      "scriptId":"u34"},
    "b2d8e30ea2d74e7c8c8651c1e9e6df56":{
      "scriptId":"u35"},
    "fa14c1f646614ba7b9efc4c001a4f326":{
      "scriptId":"u36"},
    "d8029d0144764983b0b0f78daeb0f5c6":{
      "scriptId":"u37"},
    "a3231ad3dee44951a0d1b9f30b8109b8":{
      "scriptId":"u38"},
    "332ee6ada9b245b78ad8486ffad8025e":{
      "scriptId":"u39"},
    "172440287ad04f218f2c8ad997bee18e":{
      "scriptId":"u40"},
    "db5c4f8629304b0ca2203a8c7c0c278a":{
      "scriptId":"u41"},
    "d5bd238e99c4431b86fd374e65b27222":{
      "scriptId":"u42"},
    "bedc5e5c1ff4466a8cf6aee3f29b54be":{
      "scriptId":"u43"},
    "7074d33e99fb43eaa0d5407156eaa849":{
      "scriptId":"u44"},
    "b0e9b8db8d914725969a97f9006707d1":{
      "scriptId":"u45"},
    "9636181f5c704a9dbb2379f665dac5a9":{
      "scriptId":"u46"},
    "74e41e41785347bb85e53a1125df7c0b":{
      "scriptId":"u47"},
    "bd379305f87f4a2aa43809193e9d05e6":{
      "scriptId":"u48"},
    "42a04dadf17b48aa8c7d0b537467bef9":{
      "scriptId":"u49"},
    "11a73ecb16c44d64b419081c54bebc98":{
      "scriptId":"u50"},
    "2d78c56a97e449fbb7ce2a95cc982fd9":{
      "scriptId":"u51"},
    "3744c677dbb8460ebcda1a0ffcde5804":{
      "scriptId":"u52"}}});