$axure.loadCurrentPage({
  "url":"payment_feedback.html",
  "generationDate":new Date(1470822546925.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"079892b4d36743e1bd3672c665767fd4",
    "type":"Axure:Page",
    "name":"Payment Feedback",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e7a262b522284df4b0918f50c6d532b9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":-43}},
          "adaptiveStyles":{
},
          "masterId":"866c22c904d0473f85c124c9890df389"},
{
          "id":"547d984a6cdb476b887a1f58c347808f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":181,
              "y":197},
            "size":{
              "width":295,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/choose_processing/u22_line.png"}},
{
          "id":"0e45dbebb5fe4a5598cf858e38fce49b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "location":{
              "x":193,
              "y":254},
            "size":{
              "width":22,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38c705095a0d4c90a95923d30102223b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "location":{
                  "x":193,
                  "y":254},
                "size":{
                  "width":22,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/payment/u8.png"}},
{
          "id":"6c4aaf7796df4c7497ba93add09c0fae",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "location":{
              "x":181,
              "y":103},
            "size":{
              "width":295,
              "height":43},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":5,
              "color":{
                "r":94,
                "g":94,
                "b":94,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8254199a66a44fde931929895163f87f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "location":{
                  "x":181,
                  "y":103},
                "size":{
                  "width":295,
                  "height":43},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":5,
                  "color":{
                    "r":94,
                    "g":94,
                    "b":94,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/payment/u10.png"}},
{
          "id":"7c4873ea81d443929c22c6e360d92a89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "fontSize":"17px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xDDFFFFFF,
              "opacity":0.866666674613953},
            "baseStyle":"6e631585fe0e401a93235178bc877cb7",
            "location":{
              "x":220,
              "y":112},
            "size":{
              "width":149,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"915081ce2fe44076b27ca45c02d1ded6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "fontSize":"17px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xDDFFFFFF,
                  "opacity":0.866666674613953},
                "baseStyle":"6e631585fe0e401a93235178bc877cb7",
                "location":{
                  "x":220,
                  "y":112},
                "size":{
                  "width":149,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b022fca8480c4c5db413d86463fc9763",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "verticalAlignment":"middle",
            "baseStyle":"f434fc19aed0486cb28659f79fc585db",
            "lineSpacing":"20px",
            "location":{
              "x":198,
              "y":400},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b60d30fe1c6b4e6f83a22a8bf22145fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "verticalAlignment":"middle",
                "baseStyle":"f434fc19aed0486cb28659f79fc585db",
                "lineSpacing":"20px",
                "location":{
                  "x":198,
                  "y":400},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99dd5b67db744d87b084d476abd9315a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "verticalAlignment":"middle",
            "baseStyle":"f434fc19aed0486cb28659f79fc585db",
            "lineSpacing":"20px",
            "location":{
              "x":199,
              "y":501},
            "size":{
              "width":238,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"274c705727304796928be8ab0fd12f2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "verticalAlignment":"middle",
                "baseStyle":"f434fc19aed0486cb28659f79fc585db",
                "lineSpacing":"20px",
                "location":{
                  "x":199,
                  "y":501},
                "size":{
                  "width":238,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c64ddff5bee8435cad38a90eb152a515",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xDD666666,
              "opacity":0.866666674613953},
            "baseStyle":"f434fc19aed0486cb28659f79fc585db",
            "lineSpacing":"20px",
            "location":{
              "x":198,
              "y":521},
            "size":{
              "width":241,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2d8e30ea2d74e7c8c8651c1e9e6df56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xDD666666,
                  "opacity":0.866666674613953},
                "baseStyle":"f434fc19aed0486cb28659f79fc585db",
                "lineSpacing":"20px",
                "location":{
                  "x":198,
                  "y":521},
                "size":{
                  "width":241,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa14c1f646614ba7b9efc4c001a4f326",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4CAF50},
            "location":{
              "x":273,
              "y":166},
            "size":{
              "width":93,
              "height":78},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8029d0144764983b0b0f78daeb0f5c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4CAF50},
                "location":{
                  "x":273,
                  "y":166},
                "size":{
                  "width":93,
                  "height":78},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/payment_feedback/u18.png"}},
{
          "id":"aa938195dc854635aa289a9c0ad03a6b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":170},
            "size":{
              "width":79,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da1c5fd17694409e983c320c597414c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":170},
                "size":{
                  "width":79,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/payment_feedback/u20.png"}},
{
          "id":"ac0f5b28aea445e08b3cd4ac2f7855e1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":250},
            "size":{
              "width":241,
              "height":241}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a416267789154241973bf1b61e535900",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":198,
                  "y":250},
                "size":{
                  "width":241,
                  "height":241}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/apply_filters/u13.png"}},
{
          "id":"fa45ff0d1fce4eaaa7d3356468f8d635",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4CAF50},
            "location":{
              "x":400,
              "y":570},
            "size":{
              "width":60,
              "height":48},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b05f13d0daab453786718eed6d310605",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4CAF50},
                "location":{
                  "x":400,
                  "y":570},
                "size":{
                  "width":60,
                  "height":48},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/payment_feedback/u24.png"}},
{
          "id":"056a32f86a694141ba9678b2d099aed0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":415,
              "y":584},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6cc51a36afc4f2fa3ad78749428b2ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":415,
                  "y":584},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/payment_feedback/u26.png"}},
{
          "id":"6fcfcccd295945688ce2c28c3c08467d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF003300,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF006600}},
              "mouseDown":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF003366}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF4CAF50},
            "location":{
              "x":193,
              "y":580},
            "size":{
              "width":47,
              "height":38},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc907166730541dab1aff62ead87fa18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF003300,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF006600}},
                  "mouseDown":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF003366}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4CAF50},
                "location":{
                  "x":193,
                  "y":580},
                "size":{
                  "width":47,
                  "height":38},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/payment_feedback/u28.png",
            "mouseOver~":"images/payment_feedback/u28_mouseOver.png",
            "mouseDown~":"images/payment_feedback/u28_mouseDown.png"}},
{
          "id":"08b32b7f64cf4ef69937d7de284d6bc2",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":181,
              "y":144},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"344a07b921c2415383b05917f7a64eea",
              "label":"Invisible",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"d5d45ea25fc54a979087977c514219c5",
              "label":"visible",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8f4ce08ba6be4c4a9aa80c0037ce9189",
                  "label":"",
                  "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF4CAF50},
                    "size":{
                      "width":229,
                      "height":482}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b6c61da4f394475aab246dca94f608a0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF4CAF50},
                        "size":{
                          "width":229,
                          "height":482}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u75.png"}},
{
                  "id":"11536f4eecab42659de9e7cb5455b983",
                  "label":"",
                  "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "verticalAlignment":"middle",
                    "baseStyle":"f434fc19aed0486cb28659f79fc585db",
                    "lineSpacing":"20px",
                    "location":{
                      "x":17,
                      "y":255},
                    "size":{
                      "width":74,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"51210225caf44ebea4c075ca743a873e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "verticalAlignment":"middle",
                        "baseStyle":"f434fc19aed0486cb28659f79fc585db",
                        "lineSpacing":"20px",
                        "location":{
                          "x":17,
                          "y":255},
                        "size":{
                          "width":74,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e335bdd7b7c64b67b6cbcb1c522b1eaa",
                  "label":"",
                  "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b4c514af0c7f41f8a79dca65896e86a9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u79.png"}},
{
                  "id":"0350e3fc8a2f42a5aecd8e025c36874a",
                  "label":"",
                  "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":61,
                      "y":12},
                    "size":{
                      "width":168,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7933cf5f2b6e4b7793c6e058e0a8acde",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":61,
                          "y":12},
                        "size":{
                          "width":168,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"11b8dae301014fe1bcea6b10037e1531",
                  "label":"",
                  "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "location":{
                      "x":12,
                      "y":12},
                    "size":{
                      "width":39,
                      "height":39}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e6e7831b1ad3420dbd2959bf778b9349",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "location":{
                          "x":12,
                          "y":12},
                        "size":{
                          "width":39,
                          "height":39}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u83.png"}},
{
                  "id":"b8a88c69b9ad4e01b88600bdfedb99f8",
                  "label":"",
                  "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "verticalAlignment":"bottom",
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "location":{
                      "x":0,
                      "y":62},
                    "size":{
                      "width":229,
                      "height":63},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8fe6fc4666ba4607bb01c8f6024080ed",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "verticalAlignment":"bottom",
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "location":{
                          "x":0,
                          "y":62},
                        "size":{
                          "width":229,
                          "height":63},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u85.png"}},
{
                  "id":"abe5c576f46d43e49d2e6ae7ad83f452",
                  "label":"",
                  "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":57,
                      "y":83},
                    "size":{
                      "width":150,
                      "height":38}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a5d766af4d124724945b7265cda0e627",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":57,
                          "y":83},
                        "size":{
                          "width":150,
                          "height":38}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e5037c15b5df4831b88b7c391282db60",
                  "label":"",
                  "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "verticalAlignment":"bottom",
                    "location":{
                      "x":12,
                      "y":75},
                    "size":{
                      "width":35,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"74d0aef9c6dc46c7a04020edf2023205",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "verticalAlignment":"bottom",
                        "location":{
                          "x":12,
                          "y":75},
                        "size":{
                          "width":35,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u89.png"}},
{
                  "id":"d301ed4ef51d4220bf0e50a70910e707",
                  "label":"",
                  "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "location":{
                      "x":0,
                      "y":125},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0ac3d1cfd5184701842508f30fb3a56d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "location":{
                          "x":0,
                          "y":125},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u79.png"}},
{
                  "id":"d44d7cb2c7aa4502b071bc86e4f67934",
                  "label":"",
                  "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":61,
                      "y":136},
                    "size":{
                      "width":158,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ff32ef5cae154b2ea8ec45d8de311c5e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":61,
                          "y":136},
                        "size":{
                          "width":158,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fdc0c8b77c684da8b175838d7e8fa956",
                  "label":"",
                  "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":12,
                      "y":136},
                    "size":{
                      "width":39,
                      "height":39}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d55da4b97bf144b49b02fd901c5b4f4b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":12,
                          "y":136},
                        "size":{
                          "width":39,
                          "height":39}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u95.png"}},
{
                  "id":"3e63ad47e1614a9b83659433e58fe3c5",
                  "label":"",
                  "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "location":{
                      "x":0,
                      "y":187},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e95c655cfa904884a0090216cca8424a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "location":{
                          "x":0,
                          "y":187},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u79.png"}},
{
                  "id":"e85bc1a8b9634290804b713f5b5bd196",
                  "label":"",
                  "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":61,
                      "y":199},
                    "size":{
                      "width":158,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"baa7649dc7b54267951627cf02b1731d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":61,
                          "y":199},
                        "size":{
                          "width":158,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5fab7dac00ee41db8d19f9cc74af6caf",
                  "label":"",
                  "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":12,
                      "y":199},
                    "size":{
                      "width":39,
                      "height":39}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"831a3361aa8e4b8697d1a59d8b6fd123",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":12,
                          "y":199},
                        "size":{
                          "width":39,
                          "height":39}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u101.png"}},
{
                  "id":"a323670e6fc54ee888288e85c9b483a9",
                  "label":"",
                  "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "location":{
                      "x":0,
                      "y":249},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7fae7067a2b248b282071e22d6d35fd1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "location":{
                          "x":0,
                          "y":249},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u79.png"}},
{
                  "id":"39a89829961747dc932f1502029e2dc5",
                  "label":"",
                  "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":61,
                      "y":261},
                    "size":{
                      "width":158,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"64adecac7c43419e88d6222c4fb31610",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":61,
                          "y":261},
                        "size":{
                          "width":158,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e45b08f49f8e4cb0b4a2d18ce07a98c9",
                  "label":"",
                  "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":12,
                      "y":261},
                    "size":{
                      "width":39,
                      "height":39}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"19b0bee2fbea492197048025b9c106a9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":12,
                          "y":261},
                        "size":{
                          "width":39,
                          "height":39}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u107.png"}},
{
                  "id":"673ab2e9553d4c388198d7ff5dc6a70d",
                  "label":"",
                  "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                  "panelIndex":1,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1149dff8bdb9438aac344b1ccabbbec1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Options - Profile in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"options_-_profile.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/take_photo/u109.png"}},
{
                  "id":"a4d0ec9eabfa4b85baaf0ca58e34556d",
                  "label":"",
                  "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                  "panelIndex":1,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":61},
                    "size":{
                      "width":229,
                      "height":64},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ba60c1ba3a1f4fa8b170dd5c11c9a4dd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":61},
                        "size":{
                          "width":229,
                          "height":64},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Options - Records in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"options_-_records.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8449f57214724adfa2e4ecaa607f3be3",
                  "label":"",
                  "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                  "panelIndex":1,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":125},
                    "size":{
                      "width":229,
                      "height":62},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"071026d840e74237b1cdfc42ccc5b1d4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":125},
                        "size":{
                          "width":229,
                          "height":62},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Options - Sent Pictures in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"options_-_sent_pictures.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"66e5cff25a414f04a11a1620f8ce92c0",
                  "label":"",
                  "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                  "panelIndex":1,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":187},
                    "size":{
                      "width":229,
                      "height":64},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"948284832c2a4fe7ae55467748a3a1e1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"08b32b7f64cf4ef69937d7de284d6bc2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":187},
                        "size":{
                          "width":229,
                          "height":64},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"0c18e5b4d16246debba16b911fa00de8",
          "label":"Menu Icon",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "location":{
              "x":181,
              "y":104},
            "size":{
              "width":38,
              "height":33},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a95d143b11db493e8e631f1d5f481e11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "location":{
                  "x":181,
                  "y":104},
                "size":{
                  "width":38,
                  "height":33},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1<br> (If state of (Dynamic Panel) equals Invisible)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["08b32b7f64cf4ef69937d7de284d6bc2"]}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["08b32b7f64cf4ef69937d7de284d6bc2"],
                      "panelIndex":0}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set (Dynamic Panel) to visible",
                      "panelsToStates":[{
                          "panelPath":["08b32b7f64cf4ef69937d7de284d6bc2"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]},
{
                  "description":"Case 2<br> (Else If state of (Dynamic Panel) equals visible)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["08b32b7f64cf4ef69937d7de284d6bc2"]}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["08b32b7f64cf4ef69937d7de284d6bc2"],
                      "panelIndex":1}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set (Dynamic Panel) to Invisible",
                      "panelsToStates":[{
                          "panelPath":["08b32b7f64cf4ef69937d7de284d6bc2"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/take_photo/menu_icon_u117.png"}}]}},
  "masters":{
    "866c22c904d0473f85c124c9890df389":{
      "packageId":"866c22c904d0473f85c124c9890df389",
      "type":"Axure:Master",
      "name":"frame-plain",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"786c97fb188e44ee8e7e5f4a26a54118",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":90,
                "y":-43},
              "size":{
                "width":469,
                "height":813}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cff2973955f54ebe8c64abe06b548aee",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":90,
                    "y":-43},
                  "size":{
                    "width":469,
                    "height":813}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/splash/u0.png"}},
{
            "id":"67400802aab24ac38de05902cd4eb835",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF9FAF5},
              "location":{
                "x":181,
                "y":103},
              "size":{
                "width":295,
                "height":523},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eea47f19de544c8b962b75de32a1caf9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF9FAF5},
                  "location":{
                    "x":181,
                    "y":103},
                  "size":{
                    "width":295,
                    "height":523},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/take_photo/u3.png"}}]}}},
  "objectPaths":{
    "e7a262b522284df4b0918f50c6d532b9":{
      "scriptId":"u0",
      "786c97fb188e44ee8e7e5f4a26a54118":{
        "scriptId":"u1"},
      "cff2973955f54ebe8c64abe06b548aee":{
        "scriptId":"u2"},
      "67400802aab24ac38de05902cd4eb835":{
        "scriptId":"u3"},
      "eea47f19de544c8b962b75de32a1caf9":{
        "scriptId":"u4"}},
    "547d984a6cdb476b887a1f58c347808f":{
      "scriptId":"u5"},
    "0e45dbebb5fe4a5598cf858e38fce49b":{
      "scriptId":"u6"},
    "38c705095a0d4c90a95923d30102223b":{
      "scriptId":"u7"},
    "6c4aaf7796df4c7497ba93add09c0fae":{
      "scriptId":"u8"},
    "8254199a66a44fde931929895163f87f":{
      "scriptId":"u9"},
    "7c4873ea81d443929c22c6e360d92a89":{
      "scriptId":"u10"},
    "915081ce2fe44076b27ca45c02d1ded6":{
      "scriptId":"u11"},
    "b022fca8480c4c5db413d86463fc9763":{
      "scriptId":"u12"},
    "b60d30fe1c6b4e6f83a22a8bf22145fd":{
      "scriptId":"u13"},
    "99dd5b67db744d87b084d476abd9315a":{
      "scriptId":"u14"},
    "274c705727304796928be8ab0fd12f2d":{
      "scriptId":"u15"},
    "c64ddff5bee8435cad38a90eb152a515":{
      "scriptId":"u16"},
    "b2d8e30ea2d74e7c8c8651c1e9e6df56":{
      "scriptId":"u17"},
    "fa14c1f646614ba7b9efc4c001a4f326":{
      "scriptId":"u18"},
    "d8029d0144764983b0b0f78daeb0f5c6":{
      "scriptId":"u19"},
    "aa938195dc854635aa289a9c0ad03a6b":{
      "scriptId":"u20"},
    "da1c5fd17694409e983c320c597414c3":{
      "scriptId":"u21"},
    "ac0f5b28aea445e08b3cd4ac2f7855e1":{
      "scriptId":"u22"},
    "a416267789154241973bf1b61e535900":{
      "scriptId":"u23"},
    "fa45ff0d1fce4eaaa7d3356468f8d635":{
      "scriptId":"u24"},
    "b05f13d0daab453786718eed6d310605":{
      "scriptId":"u25"},
    "056a32f86a694141ba9678b2d099aed0":{
      "scriptId":"u26"},
    "e6cc51a36afc4f2fa3ad78749428b2ec":{
      "scriptId":"u27"},
    "6fcfcccd295945688ce2c28c3c08467d":{
      "scriptId":"u28"},
    "fc907166730541dab1aff62ead87fa18":{
      "scriptId":"u29"},
    "08b32b7f64cf4ef69937d7de284d6bc2":{
      "scriptId":"u30"},
    "8f4ce08ba6be4c4a9aa80c0037ce9189":{
      "scriptId":"u31"},
    "b6c61da4f394475aab246dca94f608a0":{
      "scriptId":"u32"},
    "11536f4eecab42659de9e7cb5455b983":{
      "scriptId":"u33"},
    "51210225caf44ebea4c075ca743a873e":{
      "scriptId":"u34"},
    "e335bdd7b7c64b67b6cbcb1c522b1eaa":{
      "scriptId":"u35"},
    "b4c514af0c7f41f8a79dca65896e86a9":{
      "scriptId":"u36"},
    "0350e3fc8a2f42a5aecd8e025c36874a":{
      "scriptId":"u37"},
    "7933cf5f2b6e4b7793c6e058e0a8acde":{
      "scriptId":"u38"},
    "11b8dae301014fe1bcea6b10037e1531":{
      "scriptId":"u39"},
    "e6e7831b1ad3420dbd2959bf778b9349":{
      "scriptId":"u40"},
    "b8a88c69b9ad4e01b88600bdfedb99f8":{
      "scriptId":"u41"},
    "8fe6fc4666ba4607bb01c8f6024080ed":{
      "scriptId":"u42"},
    "abe5c576f46d43e49d2e6ae7ad83f452":{
      "scriptId":"u43"},
    "a5d766af4d124724945b7265cda0e627":{
      "scriptId":"u44"},
    "e5037c15b5df4831b88b7c391282db60":{
      "scriptId":"u45"},
    "74d0aef9c6dc46c7a04020edf2023205":{
      "scriptId":"u46"},
    "d301ed4ef51d4220bf0e50a70910e707":{
      "scriptId":"u47"},
    "0ac3d1cfd5184701842508f30fb3a56d":{
      "scriptId":"u48"},
    "d44d7cb2c7aa4502b071bc86e4f67934":{
      "scriptId":"u49"},
    "ff32ef5cae154b2ea8ec45d8de311c5e":{
      "scriptId":"u50"},
    "fdc0c8b77c684da8b175838d7e8fa956":{
      "scriptId":"u51"},
    "d55da4b97bf144b49b02fd901c5b4f4b":{
      "scriptId":"u52"},
    "3e63ad47e1614a9b83659433e58fe3c5":{
      "scriptId":"u53"},
    "e95c655cfa904884a0090216cca8424a":{
      "scriptId":"u54"},
    "e85bc1a8b9634290804b713f5b5bd196":{
      "scriptId":"u55"},
    "baa7649dc7b54267951627cf02b1731d":{
      "scriptId":"u56"},
    "5fab7dac00ee41db8d19f9cc74af6caf":{
      "scriptId":"u57"},
    "831a3361aa8e4b8697d1a59d8b6fd123":{
      "scriptId":"u58"},
    "a323670e6fc54ee888288e85c9b483a9":{
      "scriptId":"u59"},
    "7fae7067a2b248b282071e22d6d35fd1":{
      "scriptId":"u60"},
    "39a89829961747dc932f1502029e2dc5":{
      "scriptId":"u61"},
    "64adecac7c43419e88d6222c4fb31610":{
      "scriptId":"u62"},
    "e45b08f49f8e4cb0b4a2d18ce07a98c9":{
      "scriptId":"u63"},
    "19b0bee2fbea492197048025b9c106a9":{
      "scriptId":"u64"},
    "673ab2e9553d4c388198d7ff5dc6a70d":{
      "scriptId":"u65"},
    "1149dff8bdb9438aac344b1ccabbbec1":{
      "scriptId":"u66"},
    "a4d0ec9eabfa4b85baaf0ca58e34556d":{
      "scriptId":"u67"},
    "ba60c1ba3a1f4fa8b170dd5c11c9a4dd":{
      "scriptId":"u68"},
    "8449f57214724adfa2e4ecaa607f3be3":{
      "scriptId":"u69"},
    "071026d840e74237b1cdfc42ccc5b1d4":{
      "scriptId":"u70"},
    "66e5cff25a414f04a11a1620f8ce92c0":{
      "scriptId":"u71"},
    "948284832c2a4fe7ae55467748a3a1e1":{
      "scriptId":"u72"},
    "0c18e5b4d16246debba16b911fa00de8":{
      "scriptId":"u73"},
    "a95d143b11db493e8e631f1d5f481e11":{
      "scriptId":"u74"}}});