$axure.loadCurrentPage({
  "url":"apply_filters.html",
  "generationDate":new Date(1470822546230),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b29f05acabcd4ca6b1c081e4bd2bd25e",
    "type":"Axure:Page",
    "name":"Apply Filters",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"08f59f02fbec42528b460f5385b6dab3",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":-43}},
          "adaptiveStyles":{
},
          "masterId":"866c22c904d0473f85c124c9890df389"},
{
          "id":"c3b5119d62d540abbd55c2084d7059b5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4CAF50,
              "opacity":1},
            "location":{
              "x":181,
              "y":103},
            "size":{
              "width":295,
              "height":38},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":5,
              "color":{
                "r":94,
                "g":94,
                "b":94,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c870f44595594b4cad593f163ee8e08f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4CAF50,
                  "opacity":1},
                "location":{
                  "x":181,
                  "y":103},
                "size":{
                  "width":295,
                  "height":38},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":5,
                  "color":{
                    "r":94,
                    "g":94,
                    "b":94,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u6.png"}},
{
          "id":"6a05dd8d91f043e2b98c109e862fabc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "fontSize":"17px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xDDFFFFFF,
              "opacity":0.866666674613953},
            "baseStyle":"6e631585fe0e401a93235178bc877cb7",
            "location":{
              "x":226,
              "y":111},
            "size":{
              "width":97,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab47d9326d4948bcab57c8c879e5a916",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "fontSize":"17px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xDDFFFFFF,
                  "opacity":0.866666674613953},
                "baseStyle":"6e631585fe0e401a93235178bc877cb7",
                "location":{
                  "x":226,
                  "y":111},
                "size":{
                  "width":97,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a3dc97f640e42ed92afcdcd393c3534",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":461,
              "y":165},
            "size":{
              "width":10,
              "height":446},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF898989}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/take_photo/u33_line.png"}},
{
          "id":"32b65302348b4a10b7e8610112201ea6",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":461,
              "y":158},
            "size":{
              "width":10,
              "height":25},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF898989}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/take_photo/u34_line.png"}},
{
          "id":"b0335a9b429b47129fada45eb253216b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":190,
              "y":140},
            "size":{
              "width":276,
              "height":276}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe0e825bedac4cf4868215119c4bbbd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":140},
                "size":{
                  "width":276,
                  "height":276}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/apply_filters/u11.jpg"}},
{
          "id":"6c666f860893414889bc2263c80dd0cb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":437},
            "size":{
              "width":81,
              "height":81}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fed341520b394cf28fdb0a4dc76458ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":437},
                "size":{
                  "width":81,
                  "height":81}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/apply_filters/u13.png"}},
{
          "id":"339fc5cf84a2416296c73b4dc6a5b809",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":291,
              "y":437},
            "size":{
              "width":81,
              "height":81}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1a35b298c784ba3a987736c1179eddf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":291,
                  "y":437},
                "size":{
                  "width":81,
                  "height":81}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/apply_filters/u15.png"}},
{
          "id":"7db071ac55624bb6a77cd498748e6a1c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":381,
              "y":437},
            "size":{
              "width":81,
              "height":81}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24e5ec2fbc56410984156f97aa08ebd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":381,
                  "y":437},
                "size":{
                  "width":81,
                  "height":81}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/apply_filters/u17.png"}},
{
          "id":"18d3d30e284d46749dbabf0696e185b4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":437},
            "size":{
              "width":81,
              "height":81}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf494f4fe6c64474b411d84d3152f426",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":437},
                "size":{
                  "width":81,
                  "height":81}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/apply_filters/u19.png"}},
{
          "id":"5e8372134ea740a09d21168260e17e45",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4CAF50},
            "location":{
              "x":400,
              "y":532},
            "size":{
              "width":59,
              "height":58},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fb2e9ffe12744f4ba82ae21c2f472f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4CAF50},
                "location":{
                  "x":400,
                  "y":532},
                "size":{
                  "width":59,
                  "height":58},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Choose Processing in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"choose_processing.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/apply_filters/u21.png"}},
{
          "id":"32dc2ceafaf342e9a73d4d98ba662143",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":181,
              "y":144},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"a645fb286fac45ebac9e35110e403e6d",
              "label":"Invisible",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"2272394c20dc4972bf3ff667b8bd68ce",
              "label":"visible",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a5b3e3b7a66a49c393f8d61dc1c7d291",
                  "label":"",
                  "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF4CAF50},
                    "size":{
                      "width":229,
                      "height":482}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6bb094efe900494dbabfbc869c3db417",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF4CAF50},
                        "size":{
                          "width":229,
                          "height":482}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u75.png"}},
{
                  "id":"8a803d841a2b4f12b5cb087ecce303ca",
                  "label":"",
                  "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "verticalAlignment":"middle",
                    "baseStyle":"f434fc19aed0486cb28659f79fc585db",
                    "lineSpacing":"20px",
                    "location":{
                      "x":17,
                      "y":255},
                    "size":{
                      "width":74,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3215765dcf364dfbbc05d3192ed47dc2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "verticalAlignment":"middle",
                        "baseStyle":"f434fc19aed0486cb28659f79fc585db",
                        "lineSpacing":"20px",
                        "location":{
                          "x":17,
                          "y":255},
                        "size":{
                          "width":74,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"619507add9a64f37a0cfdaaa81034586",
                  "label":"",
                  "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dd5a47c4cf834c1a8946a64d8b04ce53",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u79.png"}},
{
                  "id":"cf9157bcc8e1472f8f06bffe4b2bf5c3",
                  "label":"",
                  "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":61,
                      "y":12},
                    "size":{
                      "width":168,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"38a45911ec734556a609c4896bdb4eab",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":61,
                          "y":12},
                        "size":{
                          "width":168,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1feed212b62242e8a549a7e43b2145c8",
                  "label":"",
                  "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "location":{
                      "x":12,
                      "y":12},
                    "size":{
                      "width":39,
                      "height":39}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"951d0f44dc834f359d6c00234aa0558a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "location":{
                          "x":12,
                          "y":12},
                        "size":{
                          "width":39,
                          "height":39}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u83.png"}},
{
                  "id":"14190b32f6fa4d89b1c9d09802c43688",
                  "label":"",
                  "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "verticalAlignment":"bottom",
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "location":{
                      "x":0,
                      "y":62},
                    "size":{
                      "width":229,
                      "height":63},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a712bc830b1b489a9e5b951f3ef171af",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "verticalAlignment":"bottom",
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "location":{
                          "x":0,
                          "y":62},
                        "size":{
                          "width":229,
                          "height":63},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u85.png"}},
{
                  "id":"e4903d196b1b47eba85168eefb9b2adf",
                  "label":"",
                  "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":57,
                      "y":83},
                    "size":{
                      "width":150,
                      "height":38}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a40194a978a64010bbbb947bd1326698",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":57,
                          "y":83},
                        "size":{
                          "width":150,
                          "height":38}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b568fcf7619649b9a2fe25801974dbe0",
                  "label":"",
                  "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "verticalAlignment":"bottom",
                    "location":{
                      "x":12,
                      "y":75},
                    "size":{
                      "width":35,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"77acbb58d0de4217bf2a5e4e4e4a67f2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "verticalAlignment":"bottom",
                        "location":{
                          "x":12,
                          "y":75},
                        "size":{
                          "width":35,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u89.png"}},
{
                  "id":"18c72eec329a40b88fed0ceef7b64fe9",
                  "label":"",
                  "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "location":{
                      "x":0,
                      "y":125},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7bd07727a45d4f9ab0ef204bfdb9cf26",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "location":{
                          "x":0,
                          "y":125},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u79.png"}},
{
                  "id":"4520b027f6e54f568fe03b8b1c03b994",
                  "label":"",
                  "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":61,
                      "y":136},
                    "size":{
                      "width":158,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0f13e7a743c849d8969ecb2d7359af8c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":61,
                          "y":136},
                        "size":{
                          "width":158,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ba8d99361dfb405da9570a581e7ff9db",
                  "label":"",
                  "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":12,
                      "y":136},
                    "size":{
                      "width":39,
                      "height":39}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e2d923f147e24206a4e351bd9a651ae6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":12,
                          "y":136},
                        "size":{
                          "width":39,
                          "height":39}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u95.png"}},
{
                  "id":"cbb7915480914de38b8cf185b100c9f3",
                  "label":"",
                  "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "location":{
                      "x":0,
                      "y":187},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ebee95f0ed044fb58fcd981de6aba84b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "location":{
                          "x":0,
                          "y":187},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u79.png"}},
{
                  "id":"001262b2bed84f819b170bb519ff8b79",
                  "label":"",
                  "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":61,
                      "y":199},
                    "size":{
                      "width":158,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5277157d85bf4eedb42f1c07b9fc34cc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":61,
                          "y":199},
                        "size":{
                          "width":158,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"27522a96a714496faa3dc952a609d8cc",
                  "label":"",
                  "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":12,
                      "y":199},
                    "size":{
                      "width":39,
                      "height":39}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d53e8e5b745d460bbc00300a416388ec",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":12,
                          "y":199},
                        "size":{
                          "width":39,
                          "height":39}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u101.png"}},
{
                  "id":"a4d730ff479d4ec599082d4b2dfdb7e3",
                  "label":"",
                  "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "location":{
                      "x":0,
                      "y":249},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cea7d1ae1a7d4e1ebc9eef0548feed8e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "location":{
                          "x":0,
                          "y":249},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u79.png"}},
{
                  "id":"4edfe89dca1741ff93120c409612525d",
                  "label":"",
                  "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":61,
                      "y":261},
                    "size":{
                      "width":158,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"74b4c55bde1b46bea09c3a0678867ff7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":61,
                          "y":261},
                        "size":{
                          "width":158,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0bd2a41a54ed45269bec2adca94ae86e",
                  "label":"",
                  "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":12,
                      "y":261},
                    "size":{
                      "width":39,
                      "height":39}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d47d48db2f404db1ad35b7d3e4beb5a5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":12,
                          "y":261},
                        "size":{
                          "width":39,
                          "height":39}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u107.png"}},
{
                  "id":"08176ab5ab174929ae8f282a5a284976",
                  "label":"",
                  "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                  "panelIndex":1,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3f61394f6efc4517b6b3c468b2eb3c0c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Options - Profile in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"options_-_profile.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/take_photo/u109.png"}},
{
                  "id":"d2c374c7f5b24c22ab683de27a5cc1ee",
                  "label":"",
                  "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                  "panelIndex":1,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":61},
                    "size":{
                      "width":229,
                      "height":64},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8e921678209143bc8b6a3f3e94538657",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":61},
                        "size":{
                          "width":229,
                          "height":64},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Options - Records in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"options_-_records.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"678ae2024c2c44f2bbd02b82c56a84cf",
                  "label":"",
                  "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                  "panelIndex":1,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":125},
                    "size":{
                      "width":229,
                      "height":62},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f86184bfdc4245d699087fd0e3564a27",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":125},
                        "size":{
                          "width":229,
                          "height":62},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Options - Sent Pictures in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"options_-_sent_pictures.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e98827ac334b4826b65b524326ffe6be",
                  "label":"",
                  "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                  "panelIndex":1,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":187},
                    "size":{
                      "width":229,
                      "height":64},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7f4ca54af1804107a19d6f149878b74e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32dc2ceafaf342e9a73d4d98ba662143",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":187},
                        "size":{
                          "width":229,
                          "height":64},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"e7f1c32762cf495996324dbc43c62815",
          "label":"Menu Icon",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "location":{
              "x":181,
              "y":104},
            "size":{
              "width":38,
              "height":33},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa2636a0e5104341b676a54d560bc9ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "location":{
                  "x":181,
                  "y":104},
                "size":{
                  "width":38,
                  "height":33},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1<br> (If state of (Dynamic Panel) equals Invisible)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["32dc2ceafaf342e9a73d4d98ba662143"]}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["32dc2ceafaf342e9a73d4d98ba662143"],
                      "panelIndex":0}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set (Dynamic Panel) to visible",
                      "panelsToStates":[{
                          "panelPath":["32dc2ceafaf342e9a73d4d98ba662143"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]},
{
                  "description":"Case 2<br> (Else If state of (Dynamic Panel) equals visible)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["32dc2ceafaf342e9a73d4d98ba662143"]}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["32dc2ceafaf342e9a73d4d98ba662143"],
                      "panelIndex":1}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set (Dynamic Panel) to Invisible",
                      "panelsToStates":[{
                          "panelPath":["32dc2ceafaf342e9a73d4d98ba662143"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/take_photo/menu_icon_u117.png"}}]}},
  "masters":{
    "866c22c904d0473f85c124c9890df389":{
      "packageId":"866c22c904d0473f85c124c9890df389",
      "type":"Axure:Master",
      "name":"frame-plain",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"786c97fb188e44ee8e7e5f4a26a54118",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":90,
                "y":-43},
              "size":{
                "width":469,
                "height":813}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cff2973955f54ebe8c64abe06b548aee",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":90,
                    "y":-43},
                  "size":{
                    "width":469,
                    "height":813}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/splash/u0.png"}},
{
            "id":"67400802aab24ac38de05902cd4eb835",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF9FAF5},
              "location":{
                "x":181,
                "y":103},
              "size":{
                "width":295,
                "height":523},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eea47f19de544c8b962b75de32a1caf9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF9FAF5},
                  "location":{
                    "x":181,
                    "y":103},
                  "size":{
                    "width":295,
                    "height":523},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/take_photo/u3.png"}}]}}},
  "objectPaths":{
    "08f59f02fbec42528b460f5385b6dab3":{
      "scriptId":"u0",
      "786c97fb188e44ee8e7e5f4a26a54118":{
        "scriptId":"u1"},
      "cff2973955f54ebe8c64abe06b548aee":{
        "scriptId":"u2"},
      "67400802aab24ac38de05902cd4eb835":{
        "scriptId":"u3"},
      "eea47f19de544c8b962b75de32a1caf9":{
        "scriptId":"u4"}},
    "c3b5119d62d540abbd55c2084d7059b5":{
      "scriptId":"u5"},
    "c870f44595594b4cad593f163ee8e08f":{
      "scriptId":"u6"},
    "6a05dd8d91f043e2b98c109e862fabc7":{
      "scriptId":"u7"},
    "ab47d9326d4948bcab57c8c879e5a916":{
      "scriptId":"u8"},
    "3a3dc97f640e42ed92afcdcd393c3534":{
      "scriptId":"u9"},
    "32b65302348b4a10b7e8610112201ea6":{
      "scriptId":"u10"},
    "b0335a9b429b47129fada45eb253216b":{
      "scriptId":"u11"},
    "fe0e825bedac4cf4868215119c4bbbd8":{
      "scriptId":"u12"},
    "6c666f860893414889bc2263c80dd0cb":{
      "scriptId":"u13"},
    "fed341520b394cf28fdb0a4dc76458ce":{
      "scriptId":"u14"},
    "339fc5cf84a2416296c73b4dc6a5b809":{
      "scriptId":"u15"},
    "b1a35b298c784ba3a987736c1179eddf":{
      "scriptId":"u16"},
    "7db071ac55624bb6a77cd498748e6a1c":{
      "scriptId":"u17"},
    "24e5ec2fbc56410984156f97aa08ebd3":{
      "scriptId":"u18"},
    "18d3d30e284d46749dbabf0696e185b4":{
      "scriptId":"u19"},
    "cf494f4fe6c64474b411d84d3152f426":{
      "scriptId":"u20"},
    "5e8372134ea740a09d21168260e17e45":{
      "scriptId":"u21"},
    "0fb2e9ffe12744f4ba82ae21c2f472f8":{
      "scriptId":"u22"},
    "32dc2ceafaf342e9a73d4d98ba662143":{
      "scriptId":"u23"},
    "a5b3e3b7a66a49c393f8d61dc1c7d291":{
      "scriptId":"u24"},
    "6bb094efe900494dbabfbc869c3db417":{
      "scriptId":"u25"},
    "8a803d841a2b4f12b5cb087ecce303ca":{
      "scriptId":"u26"},
    "3215765dcf364dfbbc05d3192ed47dc2":{
      "scriptId":"u27"},
    "619507add9a64f37a0cfdaaa81034586":{
      "scriptId":"u28"},
    "dd5a47c4cf834c1a8946a64d8b04ce53":{
      "scriptId":"u29"},
    "cf9157bcc8e1472f8f06bffe4b2bf5c3":{
      "scriptId":"u30"},
    "38a45911ec734556a609c4896bdb4eab":{
      "scriptId":"u31"},
    "1feed212b62242e8a549a7e43b2145c8":{
      "scriptId":"u32"},
    "951d0f44dc834f359d6c00234aa0558a":{
      "scriptId":"u33"},
    "14190b32f6fa4d89b1c9d09802c43688":{
      "scriptId":"u34"},
    "a712bc830b1b489a9e5b951f3ef171af":{
      "scriptId":"u35"},
    "e4903d196b1b47eba85168eefb9b2adf":{
      "scriptId":"u36"},
    "a40194a978a64010bbbb947bd1326698":{
      "scriptId":"u37"},
    "b568fcf7619649b9a2fe25801974dbe0":{
      "scriptId":"u38"},
    "77acbb58d0de4217bf2a5e4e4e4a67f2":{
      "scriptId":"u39"},
    "18c72eec329a40b88fed0ceef7b64fe9":{
      "scriptId":"u40"},
    "7bd07727a45d4f9ab0ef204bfdb9cf26":{
      "scriptId":"u41"},
    "4520b027f6e54f568fe03b8b1c03b994":{
      "scriptId":"u42"},
    "0f13e7a743c849d8969ecb2d7359af8c":{
      "scriptId":"u43"},
    "ba8d99361dfb405da9570a581e7ff9db":{
      "scriptId":"u44"},
    "e2d923f147e24206a4e351bd9a651ae6":{
      "scriptId":"u45"},
    "cbb7915480914de38b8cf185b100c9f3":{
      "scriptId":"u46"},
    "ebee95f0ed044fb58fcd981de6aba84b":{
      "scriptId":"u47"},
    "001262b2bed84f819b170bb519ff8b79":{
      "scriptId":"u48"},
    "5277157d85bf4eedb42f1c07b9fc34cc":{
      "scriptId":"u49"},
    "27522a96a714496faa3dc952a609d8cc":{
      "scriptId":"u50"},
    "d53e8e5b745d460bbc00300a416388ec":{
      "scriptId":"u51"},
    "a4d730ff479d4ec599082d4b2dfdb7e3":{
      "scriptId":"u52"},
    "cea7d1ae1a7d4e1ebc9eef0548feed8e":{
      "scriptId":"u53"},
    "4edfe89dca1741ff93120c409612525d":{
      "scriptId":"u54"},
    "74b4c55bde1b46bea09c3a0678867ff7":{
      "scriptId":"u55"},
    "0bd2a41a54ed45269bec2adca94ae86e":{
      "scriptId":"u56"},
    "d47d48db2f404db1ad35b7d3e4beb5a5":{
      "scriptId":"u57"},
    "08176ab5ab174929ae8f282a5a284976":{
      "scriptId":"u58"},
    "3f61394f6efc4517b6b3c468b2eb3c0c":{
      "scriptId":"u59"},
    "d2c374c7f5b24c22ab683de27a5cc1ee":{
      "scriptId":"u60"},
    "8e921678209143bc8b6a3f3e94538657":{
      "scriptId":"u61"},
    "678ae2024c2c44f2bbd02b82c56a84cf":{
      "scriptId":"u62"},
    "f86184bfdc4245d699087fd0e3564a27":{
      "scriptId":"u63"},
    "e98827ac334b4826b65b524326ffe6be":{
      "scriptId":"u64"},
    "7f4ca54af1804107a19d6f149878b74e":{
      "scriptId":"u65"},
    "e7f1c32762cf495996324dbc43c62815":{
      "scriptId":"u66"},
    "fa2636a0e5104341b676a54d560bc9ed":{
      "scriptId":"u67"}}});