$axure.loadCurrentPage({
  "url":"options_-_profile.html",
  "generationDate":new Date(1470822547242.5),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bb4ac2d615064e2f98d24b5b68062834",
    "type":"Axure:Page",
    "name":"Options - Profile",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e7a262b522284df4b0918f50c6d532b9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":-43}},
          "adaptiveStyles":{
},
          "masterId":"866c22c904d0473f85c124c9890df389"},
{
          "id":"547d984a6cdb476b887a1f58c347808f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":181,
              "y":197},
            "size":{
              "width":295,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/choose_processing/u22_line.png"}},
{
          "id":"0e45dbebb5fe4a5598cf858e38fce49b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "location":{
              "x":193,
              "y":254},
            "size":{
              "width":22,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38c705095a0d4c90a95923d30102223b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "location":{
                  "x":193,
                  "y":254},
                "size":{
                  "width":22,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/payment/u8.png"}},
{
          "id":"6c4aaf7796df4c7497ba93add09c0fae",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "location":{
              "x":181,
              "y":103},
            "size":{
              "width":295,
              "height":43},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":5,
              "color":{
                "r":94,
                "g":94,
                "b":94,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8254199a66a44fde931929895163f87f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "location":{
                  "x":181,
                  "y":103},
                "size":{
                  "width":295,
                  "height":43},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":5,
                  "color":{
                    "r":94,
                    "g":94,
                    "b":94,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/payment/u10.png"}},
{
          "id":"7c4873ea81d443929c22c6e360d92a89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "fontSize":"17px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xDDFFFFFF,
              "opacity":0.866666674613953},
            "baseStyle":"6e631585fe0e401a93235178bc877cb7",
            "location":{
              "x":220,
              "y":112},
            "size":{
              "width":62,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"915081ce2fe44076b27ca45c02d1ded6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "fontSize":"17px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xDDFFFFFF,
                  "opacity":0.866666674613953},
                "baseStyle":"6e631585fe0e401a93235178bc877cb7",
                "location":{
                  "x":220,
                  "y":112},
                "size":{
                  "width":62,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b022fca8480c4c5db413d86463fc9763",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "verticalAlignment":"middle",
            "baseStyle":"f434fc19aed0486cb28659f79fc585db",
            "lineSpacing":"20px",
            "location":{
              "x":198,
              "y":400},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b60d30fe1c6b4e6f83a22a8bf22145fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "verticalAlignment":"middle",
                "baseStyle":"f434fc19aed0486cb28659f79fc585db",
                "lineSpacing":"20px",
                "location":{
                  "x":198,
                  "y":400},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"312f5012e14a47d598b95418e87d95c3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":233},
            "size":{
              "width":277,
              "height":37}},
          "adaptiveStyles":{
}},
{
          "id":"9a0219c4a7e145c1b913edf4279b0c0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":217},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e5df076d60743eeb51472ef68215af4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":193,
                  "y":217},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ea233c7b7234a98b0aa16c7f0923615",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":296},
            "size":{
              "width":277,
              "height":37}},
          "adaptiveStyles":{
}},
{
          "id":"363d1ac347264b27bee72942ae6fb80e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":280},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5516fc0af471499dbcf2e2b67506cc1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":193,
                  "y":280},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97f9cf6f16df423db27da8a68a523d67",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":359},
            "size":{
              "width":277,
              "height":37}},
          "adaptiveStyles":{
}},
{
          "id":"17443da11c9f414bb8cb3f2867f5b46e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":343},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24029db4f5b440f7a8528b748a0c4e25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":193,
                  "y":343},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc0307a8c9e64e3c9824f5a99a5b0c3f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":422},
            "size":{
              "width":277,
              "height":37}},
          "adaptiveStyles":{
}},
{
          "id":"bd2ce6cebeb5457e9520845ee24217d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":406},
            "size":{
              "width":127,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73d700c8d8e54dd9b4a10e288c99092d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":193,
                  "y":406},
                "size":{
                  "width":127,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23df2e934fe943a6bcaca6ddaf08bbe5",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":485},
            "size":{
              "width":277,
              "height":37}},
          "adaptiveStyles":{
}},
{
          "id":"f038ccaba5f940ef8fad8c92441d1d15",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":469},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c00780d782ff4bf182caf9588e951d5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":193,
                  "y":469},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ff87890c32b4ad09cae911ed554591c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4CAF50},
            "location":{
              "x":410,
              "y":532},
            "size":{
              "width":49,
              "height":48},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f63844679ed4ac9a7ef28e03e805421",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4CAF50},
                "location":{
                  "x":410,
                  "y":532},
                "size":{
                  "width":49,
                  "height":48},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/options_-_profile/u29.png"}},
{
          "id":"3c3761a95cf84b2abdd30f8485b3f75a",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":181,
              "y":144},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"795b2a2880e742639ee55a346aa1efc9",
              "label":"Invisible",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"8f2efae02e884c66b53a24f36c84cfc5",
              "label":"visible",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e3575d3ffc7343c6a894ad3a38900134",
                  "label":"",
                  "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF4CAF50},
                    "size":{
                      "width":229,
                      "height":482}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"935c166183d14a2fb99023b9c053b64b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF4CAF50},
                        "size":{
                          "width":229,
                          "height":482}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u75.png"}},
{
                  "id":"5d372c3ba7ff444ca416be54d425ab16",
                  "label":"",
                  "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "verticalAlignment":"middle",
                    "baseStyle":"f434fc19aed0486cb28659f79fc585db",
                    "lineSpacing":"20px",
                    "location":{
                      "x":17,
                      "y":255},
                    "size":{
                      "width":74,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c38eff3f69314b73b674e2a4dca81a88",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "verticalAlignment":"middle",
                        "baseStyle":"f434fc19aed0486cb28659f79fc585db",
                        "lineSpacing":"20px",
                        "location":{
                          "x":17,
                          "y":255},
                        "size":{
                          "width":74,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0818694053204dcea7c94d5f9989f409",
                  "label":"",
                  "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b6767305e5414426bffa6b781e112a03",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u79.png"}},
{
                  "id":"5877c3043e2b4e8cabbe9f6e05cab123",
                  "label":"",
                  "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":61,
                      "y":12},
                    "size":{
                      "width":168,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cc0639969a2f43b7b50c2a7ec3cd7ba2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":61,
                          "y":12},
                        "size":{
                          "width":168,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7c9b44a674694b41a14490b704bebfac",
                  "label":"",
                  "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "location":{
                      "x":12,
                      "y":12},
                    "size":{
                      "width":39,
                      "height":39}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ff3b6fc168f24116852491f93562eed8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "location":{
                          "x":12,
                          "y":12},
                        "size":{
                          "width":39,
                          "height":39}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u83.png"}},
{
                  "id":"a02d7dd4aec24ebbb38636d922cc6e60",
                  "label":"",
                  "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "verticalAlignment":"bottom",
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "location":{
                      "x":0,
                      "y":62},
                    "size":{
                      "width":229,
                      "height":63},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"75acddc8f55740a78c9778c7a68cf63f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "verticalAlignment":"bottom",
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "location":{
                          "x":0,
                          "y":62},
                        "size":{
                          "width":229,
                          "height":63},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u85.png"}},
{
                  "id":"73a4e1345fb645adbe5c35f1b25ab41e",
                  "label":"",
                  "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":57,
                      "y":83},
                    "size":{
                      "width":150,
                      "height":38}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b2c19c2fa4574822915e674ed702d5fa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":57,
                          "y":83},
                        "size":{
                          "width":150,
                          "height":38}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"57b2b25d702a41c7bee539cbc954aca8",
                  "label":"",
                  "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "verticalAlignment":"bottom",
                    "location":{
                      "x":12,
                      "y":75},
                    "size":{
                      "width":35,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3ea65dab7a624d45b4a8d02863407a44",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "verticalAlignment":"bottom",
                        "location":{
                          "x":12,
                          "y":75},
                        "size":{
                          "width":35,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u89.png"}},
{
                  "id":"f9b0daae217e401ca31d519f91376936",
                  "label":"",
                  "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "location":{
                      "x":0,
                      "y":125},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"720242eb6cfb44a08a0c220380f54d22",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "location":{
                          "x":0,
                          "y":125},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u79.png"}},
{
                  "id":"20ea1d4fd88f4422bcb7c52bb74e0f26",
                  "label":"",
                  "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":61,
                      "y":136},
                    "size":{
                      "width":158,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ba29d263704e4b7bacd06ca7c7816bca",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":61,
                          "y":136},
                        "size":{
                          "width":158,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ec350e47c2694acb9543cb617afc3b32",
                  "label":"",
                  "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":12,
                      "y":136},
                    "size":{
                      "width":39,
                      "height":39}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3e2782d6c0ba47bfbedd9f0554da37e0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":12,
                          "y":136},
                        "size":{
                          "width":39,
                          "height":39}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u95.png"}},
{
                  "id":"312b8a42b580456e97ffbef08fba19df",
                  "label":"",
                  "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "location":{
                      "x":0,
                      "y":187},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5aaea96e61f3455eb6a261b6af3087f4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "location":{
                          "x":0,
                          "y":187},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u79.png"}},
{
                  "id":"2ea71caa64614bdc9cc53e36ce517df8",
                  "label":"",
                  "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":61,
                      "y":199},
                    "size":{
                      "width":158,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"68ff4482caea48fcafa759c384396893",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":61,
                          "y":199},
                        "size":{
                          "width":158,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5f108534e7af4b8c903b7e7b11aaf784",
                  "label":"",
                  "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":12,
                      "y":199},
                    "size":{
                      "width":39,
                      "height":39}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"67e2e830e9a84240b7bb1c2b70445c52",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":12,
                          "y":199},
                        "size":{
                          "width":39,
                          "height":39}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u101.png"}},
{
                  "id":"8740213b9ed44c4bb7ad40af2f1954c7",
                  "label":"",
                  "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "location":{
                      "x":0,
                      "y":249},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a6ce37707504448685a756ea111f6450",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "location":{
                          "x":0,
                          "y":249},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u79.png"}},
{
                  "id":"6d7ddb2e60454f4b92ec8f5aefed3481",
                  "label":"",
                  "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":61,
                      "y":261},
                    "size":{
                      "width":158,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f5a2e9fa5c934de8a2d4257efd3b3ff7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":61,
                          "y":261},
                        "size":{
                          "width":158,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"646ba114a3bf414dad81ae47c5dd5a70",
                  "label":"",
                  "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":12,
                      "y":261},
                    "size":{
                      "width":39,
                      "height":39}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"769766e21d834a18940bfa7cc46baa9a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":12,
                          "y":261},
                        "size":{
                          "width":39,
                          "height":39}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_photo/u107.png"}},
{
                  "id":"575a852d5a6248eb933401e0dd073121",
                  "label":"",
                  "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                  "panelIndex":1,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"122f2429320141da9a4decf7a8f4acd3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Options - Profile in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"options_-_profile.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/take_photo/u109.png"}},
{
                  "id":"71c93cfae8bd42bb8e5b757824f827b6",
                  "label":"",
                  "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                  "panelIndex":1,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":61},
                    "size":{
                      "width":229,
                      "height":64},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"24cecff2230b49bbbf3c59c823d5b55e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":61},
                        "size":{
                          "width":229,
                          "height":64},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Options - Records in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"options_-_records.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5f07e8367af24d54931f23d62ce02b2a",
                  "label":"",
                  "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                  "panelIndex":1,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":125},
                    "size":{
                      "width":229,
                      "height":62},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"57a5c3984ac64692bdb4cd02ae647807",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":125},
                        "size":{
                          "width":229,
                          "height":62},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Options - Sent Pictures in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"options_-_sent_pictures.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7d36eb3e5a65495f9e8cab10efa0085d",
                  "label":"",
                  "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                  "panelIndex":1,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":187},
                    "size":{
                      "width":229,
                      "height":64},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f883f25d93e5494d86fd5b12dbf05974",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c3761a95cf84b2abdd30f8485b3f75a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":187},
                        "size":{
                          "width":229,
                          "height":64},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"43b49d1cc86348a0a29ea88a79f07108",
          "label":"Menu Icon",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "location":{
              "x":181,
              "y":104},
            "size":{
              "width":38,
              "height":33},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc8bca6104b94b3286f3c6c681f25ea0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "location":{
                  "x":181,
                  "y":104},
                "size":{
                  "width":38,
                  "height":33},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1<br> (If state of (Dynamic Panel) equals Invisible)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["3c3761a95cf84b2abdd30f8485b3f75a"]}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["3c3761a95cf84b2abdd30f8485b3f75a"],
                      "panelIndex":0}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set (Dynamic Panel) to visible",
                      "panelsToStates":[{
                          "panelPath":["3c3761a95cf84b2abdd30f8485b3f75a"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]},
{
                  "description":"Case 2<br> (Else If state of (Dynamic Panel) equals visible)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["3c3761a95cf84b2abdd30f8485b3f75a"]}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["3c3761a95cf84b2abdd30f8485b3f75a"],
                      "panelIndex":1}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set (Dynamic Panel) to Invisible",
                      "panelsToStates":[{
                          "panelPath":["3c3761a95cf84b2abdd30f8485b3f75a"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/take_photo/menu_icon_u117.png"}}]}},
  "masters":{
    "866c22c904d0473f85c124c9890df389":{
      "packageId":"866c22c904d0473f85c124c9890df389",
      "type":"Axure:Master",
      "name":"frame-plain",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"786c97fb188e44ee8e7e5f4a26a54118",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":90,
                "y":-43},
              "size":{
                "width":469,
                "height":813}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cff2973955f54ebe8c64abe06b548aee",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":90,
                    "y":-43},
                  "size":{
                    "width":469,
                    "height":813}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/splash/u0.png"}},
{
            "id":"67400802aab24ac38de05902cd4eb835",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF9FAF5},
              "location":{
                "x":181,
                "y":103},
              "size":{
                "width":295,
                "height":523},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eea47f19de544c8b962b75de32a1caf9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF9FAF5},
                  "location":{
                    "x":181,
                    "y":103},
                  "size":{
                    "width":295,
                    "height":523},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/take_photo/u3.png"}}]}}},
  "objectPaths":{
    "e7a262b522284df4b0918f50c6d532b9":{
      "scriptId":"u0",
      "786c97fb188e44ee8e7e5f4a26a54118":{
        "scriptId":"u1"},
      "cff2973955f54ebe8c64abe06b548aee":{
        "scriptId":"u2"},
      "67400802aab24ac38de05902cd4eb835":{
        "scriptId":"u3"},
      "eea47f19de544c8b962b75de32a1caf9":{
        "scriptId":"u4"}},
    "547d984a6cdb476b887a1f58c347808f":{
      "scriptId":"u5"},
    "0e45dbebb5fe4a5598cf858e38fce49b":{
      "scriptId":"u6"},
    "38c705095a0d4c90a95923d30102223b":{
      "scriptId":"u7"},
    "6c4aaf7796df4c7497ba93add09c0fae":{
      "scriptId":"u8"},
    "8254199a66a44fde931929895163f87f":{
      "scriptId":"u9"},
    "7c4873ea81d443929c22c6e360d92a89":{
      "scriptId":"u10"},
    "915081ce2fe44076b27ca45c02d1ded6":{
      "scriptId":"u11"},
    "b022fca8480c4c5db413d86463fc9763":{
      "scriptId":"u12"},
    "b60d30fe1c6b4e6f83a22a8bf22145fd":{
      "scriptId":"u13"},
    "312f5012e14a47d598b95418e87d95c3":{
      "scriptId":"u14"},
    "9a0219c4a7e145c1b913edf4279b0c0b":{
      "scriptId":"u15"},
    "7e5df076d60743eeb51472ef68215af4":{
      "scriptId":"u16"},
    "6ea233c7b7234a98b0aa16c7f0923615":{
      "scriptId":"u17"},
    "363d1ac347264b27bee72942ae6fb80e":{
      "scriptId":"u18"},
    "5516fc0af471499dbcf2e2b67506cc1f":{
      "scriptId":"u19"},
    "97f9cf6f16df423db27da8a68a523d67":{
      "scriptId":"u20"},
    "17443da11c9f414bb8cb3f2867f5b46e":{
      "scriptId":"u21"},
    "24029db4f5b440f7a8528b748a0c4e25":{
      "scriptId":"u22"},
    "cc0307a8c9e64e3c9824f5a99a5b0c3f":{
      "scriptId":"u23"},
    "bd2ce6cebeb5457e9520845ee24217d6":{
      "scriptId":"u24"},
    "73d700c8d8e54dd9b4a10e288c99092d":{
      "scriptId":"u25"},
    "23df2e934fe943a6bcaca6ddaf08bbe5":{
      "scriptId":"u26"},
    "f038ccaba5f940ef8fad8c92441d1d15":{
      "scriptId":"u27"},
    "c00780d782ff4bf182caf9588e951d5e":{
      "scriptId":"u28"},
    "6ff87890c32b4ad09cae911ed554591c":{
      "scriptId":"u29"},
    "9f63844679ed4ac9a7ef28e03e805421":{
      "scriptId":"u30"},
    "3c3761a95cf84b2abdd30f8485b3f75a":{
      "scriptId":"u31"},
    "e3575d3ffc7343c6a894ad3a38900134":{
      "scriptId":"u32"},
    "935c166183d14a2fb99023b9c053b64b":{
      "scriptId":"u33"},
    "5d372c3ba7ff444ca416be54d425ab16":{
      "scriptId":"u34"},
    "c38eff3f69314b73b674e2a4dca81a88":{
      "scriptId":"u35"},
    "0818694053204dcea7c94d5f9989f409":{
      "scriptId":"u36"},
    "b6767305e5414426bffa6b781e112a03":{
      "scriptId":"u37"},
    "5877c3043e2b4e8cabbe9f6e05cab123":{
      "scriptId":"u38"},
    "cc0639969a2f43b7b50c2a7ec3cd7ba2":{
      "scriptId":"u39"},
    "7c9b44a674694b41a14490b704bebfac":{
      "scriptId":"u40"},
    "ff3b6fc168f24116852491f93562eed8":{
      "scriptId":"u41"},
    "a02d7dd4aec24ebbb38636d922cc6e60":{
      "scriptId":"u42"},
    "75acddc8f55740a78c9778c7a68cf63f":{
      "scriptId":"u43"},
    "73a4e1345fb645adbe5c35f1b25ab41e":{
      "scriptId":"u44"},
    "b2c19c2fa4574822915e674ed702d5fa":{
      "scriptId":"u45"},
    "57b2b25d702a41c7bee539cbc954aca8":{
      "scriptId":"u46"},
    "3ea65dab7a624d45b4a8d02863407a44":{
      "scriptId":"u47"},
    "f9b0daae217e401ca31d519f91376936":{
      "scriptId":"u48"},
    "720242eb6cfb44a08a0c220380f54d22":{
      "scriptId":"u49"},
    "20ea1d4fd88f4422bcb7c52bb74e0f26":{
      "scriptId":"u50"},
    "ba29d263704e4b7bacd06ca7c7816bca":{
      "scriptId":"u51"},
    "ec350e47c2694acb9543cb617afc3b32":{
      "scriptId":"u52"},
    "3e2782d6c0ba47bfbedd9f0554da37e0":{
      "scriptId":"u53"},
    "312b8a42b580456e97ffbef08fba19df":{
      "scriptId":"u54"},
    "5aaea96e61f3455eb6a261b6af3087f4":{
      "scriptId":"u55"},
    "2ea71caa64614bdc9cc53e36ce517df8":{
      "scriptId":"u56"},
    "68ff4482caea48fcafa759c384396893":{
      "scriptId":"u57"},
    "5f108534e7af4b8c903b7e7b11aaf784":{
      "scriptId":"u58"},
    "67e2e830e9a84240b7bb1c2b70445c52":{
      "scriptId":"u59"},
    "8740213b9ed44c4bb7ad40af2f1954c7":{
      "scriptId":"u60"},
    "a6ce37707504448685a756ea111f6450":{
      "scriptId":"u61"},
    "6d7ddb2e60454f4b92ec8f5aefed3481":{
      "scriptId":"u62"},
    "f5a2e9fa5c934de8a2d4257efd3b3ff7":{
      "scriptId":"u63"},
    "646ba114a3bf414dad81ae47c5dd5a70":{
      "scriptId":"u64"},
    "769766e21d834a18940bfa7cc46baa9a":{
      "scriptId":"u65"},
    "575a852d5a6248eb933401e0dd073121":{
      "scriptId":"u66"},
    "122f2429320141da9a4decf7a8f4acd3":{
      "scriptId":"u67"},
    "71c93cfae8bd42bb8e5b757824f827b6":{
      "scriptId":"u68"},
    "24cecff2230b49bbbf3c59c823d5b55e":{
      "scriptId":"u69"},
    "5f07e8367af24d54931f23d62ce02b2a":{
      "scriptId":"u70"},
    "57a5c3984ac64692bdb4cd02ae647807":{
      "scriptId":"u71"},
    "7d36eb3e5a65495f9e8cab10efa0085d":{
      "scriptId":"u72"},
    "f883f25d93e5494d86fd5b12dbf05974":{
      "scriptId":"u73"},
    "43b49d1cc86348a0a29ea88a79f07108":{
      "scriptId":"u74"},
    "bc8bca6104b94b3286f3c6c681f25ea0":{
      "scriptId":"u75"}}});