$axure.loadCurrentPage({
  "url":"news_updates.html",
  "generationDate":new Date(1478805210139.94),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"06e264e47e9f4ea28b615cbb4a1bc5e9",
    "type":"Axure:Page",
    "name":"News Updates",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b147babde7834c5d80be67f4a49d87fc",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"e163cbb4cef54461ad56955f368f2e96"},
{
          "id":"b2e24ae280514be6a0f7eccf53a9b805",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":293,
              "y":142},
            "size":{
              "width":1022,
              "height":588},
            "borderWidth":"-1",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":0,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b586b23f61c4f969d039bc62ffec873",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":293,
                  "y":142},
                "size":{
                  "width":1022,
                  "height":588},
                "borderWidth":"-1",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":0,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/list_of_ambassadors/u11.png"}},
{
          "id":"fa4229a818304ecb8f20c64469727105",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Regular', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":294,
              "y":72},
            "size":{
              "width":157,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f1bb9a2bbad4739ba0185d302efd574",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Regular', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":294,
                  "y":72},
                "size":{
                  "width":157,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cfdd493c15f4b0fbbcf611321201538",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1996C7},
            "location":{
              "x":293,
              "y":142},
            "size":{
              "width":1022,
              "height":35},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54374e6d3a4849b2a2806dab9a4775b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1996C7},
                "location":{
                  "x":293,
                  "y":142},
                "size":{
                  "width":1022,
                  "height":35},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/list_of_ambassadors/u15.png"}},
{
          "id":"7fb87094ec2747b785e1cb140fb4cab6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1270,
              "y":25},
            "size":{
              "width":50,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1586387c8124e0eb9c42786eb232318",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1270,
                  "y":25},
                "size":{
                  "width":50,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37badc0c61174a4e8ab699fcad824687",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":280},
            "size":{
              "width":871,
              "height":280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa2dff89341e409fa7639b797caf1bba",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1996C7,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "size":{
                  "width":264,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"296a84963ca14848a07013e425cd7228",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1996C7,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "size":{
                      "width":264,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/list_of_ambassadors/u22.png"}},
{
              "id":"f536382567424dc08eb9b1f92f6b5556",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":220},
                "size":{
                  "width":264,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6979252fa0924f69840b0bd29f40b55c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":220},
                    "size":{
                      "width":264,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/list_of_ambassadors/u76.png"}},
{
              "id":"05ac645783a94470b02195dff4d1e325",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":250},
                "size":{
                  "width":264,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"47a8cf266de64d0f9d1a56442cce70ce",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":250},
                    "size":{
                      "width":264,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/list_of_ambassadors/u82.png"}},
{
              "id":"2712c85751c24529bc02d731bce2d269",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1996C7,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":528,
                  "y":0},
                "size":{
                  "width":343,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9327f6493d8143978ad07a4a57ab46aa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1996C7,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":528,
                      "y":0},
                    "size":{
                      "width":343,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates/u24.png"}},
{
              "id":"dc9c10f6be874b80acc9d8af8a14465d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":528,
                  "y":220},
                "size":{
                  "width":343,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5fd59565240043049e28d25a118774d4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":528,
                      "y":220},
                    "size":{
                      "width":343,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates/u78.png"}},
{
              "id":"ffad79fdd2db4f8980ce3d1193f8f6f4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":528,
                  "y":250},
                "size":{
                  "width":343,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1cb6081c928c4dd0a2baa68909ea94a5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":528,
                      "y":250},
                    "size":{
                      "width":343,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates/u84.png"}},
{
              "id":"e23ff2dbb5fc41faa3a8c48967b500a7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":25},
                "size":{
                  "width":264,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"40e7b5a3d3fe4e62b0fd106d1e104f61",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":25},
                    "size":{
                      "width":264,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/list_of_ambassadors/u28.png"}},
{
              "id":"ab3cab915a8c4c6184a9946548716f8a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":528,
                  "y":25},
                "size":{
                  "width":343,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c8b71d13a48e42eeb642f5522365fb90",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":528,
                      "y":25},
                    "size":{
                      "width":343,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates/u30.png"}},
{
              "id":"f8137901b6b34536beed603aa9c95491",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":264,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d96bd8ee88cc4350925263227c0b56d2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":50},
                    "size":{
                      "width":264,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/list_of_ambassadors/u28.png"}},
{
              "id":"a3e62543ee2a44b5ab2afdef68a74dfd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":528,
                  "y":50},
                "size":{
                  "width":343,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e3996a5704984fbcab1ddbe83f263eed",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":528,
                      "y":50},
                    "size":{
                      "width":343,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates/u30.png"}},
{
              "id":"d470a41c44ec4f80a67f066bb49ea0c8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":75},
                "size":{
                  "width":264,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5475efd7d12c49f9aba47cf3eccc2750",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":75},
                    "size":{
                      "width":264,
                      "height":20},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/leads/u44.png"}},
{
              "id":"a7b6e05b9522436e87ef3096268553d4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":528,
                  "y":75},
                "size":{
                  "width":343,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7f84b2b3feb142b79c17597e8b211c0d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":528,
                      "y":75},
                    "size":{
                      "width":343,
                      "height":20},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates/u42.png"}},
{
              "id":"7a7acfe90a75411eaca50a7e83ad4575",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":95},
                "size":{
                  "width":264,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5bd553f511ae4799b91900b15c9f8729",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":95},
                    "size":{
                      "width":264,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/list_of_ambassadors/u28.png"}},
{
              "id":"3d27263965884168992949ac00ae40b4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":528,
                  "y":95},
                "size":{
                  "width":343,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9319e9fee39942eca279520554798a2a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":528,
                      "y":95},
                    "size":{
                      "width":343,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates/u30.png"}},
{
              "id":"a745ef5a4e324f74bc1061b0e5103423",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":264,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"09195e37636e492c9fd6a305b4e5d8ad",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":264,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/list_of_ambassadors/u28.png"}},
{
              "id":"88a264480ce2445f937c800341637cbb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":528,
                  "y":120},
                "size":{
                  "width":343,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c3760290fe734afeb03a2f390184d79c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":528,
                      "y":120},
                    "size":{
                      "width":343,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates/u30.png"}},
{
              "id":"b132599a52a4490093d7fd9758507d4c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":145},
                "size":{
                  "width":264,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e0c65c1d842b473683cee6433802f7f1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":145},
                    "size":{
                      "width":264,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/list_of_ambassadors/u28.png"}},
{
              "id":"f12adba306e546b3810fbf4e3a13a6b8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":528,
                  "y":145},
                "size":{
                  "width":343,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"54921efc7c034923a4d8c159ebd629aa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":528,
                      "y":145},
                    "size":{
                      "width":343,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates/u30.png"}},
{
              "id":"ad1717f5d503430cae63f1038b62dee1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":195},
                "size":{
                  "width":264,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7333ce7dd87d4a679681f54367d3c4cb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":195},
                    "size":{
                      "width":264,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/list_of_ambassadors/u28.png"}},
{
              "id":"0e80ff22cb5a48948f5cd3fc335373d3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":528,
                  "y":195},
                "size":{
                  "width":343,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"62d6ebef0e1c4ef786ba09c80a475467",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":528,
                      "y":195},
                    "size":{
                      "width":343,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates/u30.png"}},
{
              "id":"da84be11e4a5437ebe3caa63bb606e58",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":170},
                "size":{
                  "width":264,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"18641507d29c4f5887f7c1363ff9c4b0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":170},
                    "size":{
                      "width":264,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/list_of_ambassadors/u28.png"}},
{
              "id":"5ef7ffb5129c4831a796ef10bfcb1381",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":528,
                  "y":170},
                "size":{
                  "width":343,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f80b8423807a42b2bf93932494e774b8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":528,
                      "y":170},
                    "size":{
                      "width":343,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/news_updates/u30.png"}},
{
              "id":"b55c2b41ea9d413589164ab9c766a68c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1996C7,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":264,
                  "y":0},
                "size":{
                  "width":264,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8a05e8b71d894ab1ba734ba0ff7b490b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1996C7,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":264,
                      "y":0},
                    "size":{
                      "width":264,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/list_of_ambassadors/u22.png"}},
{
              "id":"9cb0551cabca4970b2dafb8855b75f86",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":264,
                  "y":25},
                "size":{
                  "width":264,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4933b1fff99e4c69b9fb448e18d2532f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":264,
                      "y":25},
                    "size":{
                      "width":264,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/list_of_ambassadors/u28.png"}},
{
              "id":"14e2b0e0a8c04cfc9ca06c245b8a3327",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":264,
                  "y":50},
                "size":{
                  "width":264,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"29ebcbd47a9248dcb949e9523d0255c9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":264,
                      "y":50},
                    "size":{
                      "width":264,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/list_of_ambassadors/u28.png"}},
{
              "id":"ed04a0093d064d98a21afa5ac433541b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":264,
                  "y":75},
                "size":{
                  "width":264,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4b59acab574843f89d64bdcd582654ff",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":264,
                      "y":75},
                    "size":{
                      "width":264,
                      "height":20},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/leads/u44.png"}},
{
              "id":"44332d4e90cb474baff1f38b7c65df8e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":264,
                  "y":95},
                "size":{
                  "width":264,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bef460f4b6394b139e74c3e9c5d264c4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":264,
                      "y":95},
                    "size":{
                      "width":264,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/list_of_ambassadors/u28.png"}},
{
              "id":"ea2a44f876cb492db9a8df9168fa8511",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":264,
                  "y":120},
                "size":{
                  "width":264,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f6be8ea3428c4e44a4738714c0e3ab83",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":264,
                      "y":120},
                    "size":{
                      "width":264,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/list_of_ambassadors/u28.png"}},
{
              "id":"1208463bf36c4283a518a0f59abc7caf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":264,
                  "y":145},
                "size":{
                  "width":264,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8e9f68abf98947899a13121af64dc1e2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":264,
                      "y":145},
                    "size":{
                      "width":264,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/list_of_ambassadors/u28.png"}},
{
              "id":"49b73bd8fd0142a8909af025a3ba6dd8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":264,
                  "y":170},
                "size":{
                  "width":264,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5745e2f7a39346a186ff2bb90de50b43",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":264,
                      "y":170},
                    "size":{
                      "width":264,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/list_of_ambassadors/u28.png"}},
{
              "id":"9df6841425aa445887e36be611e18916",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":264,
                  "y":195},
                "size":{
                  "width":264,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6fc4bfd460ec40ca908b43d8631be5d4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":264,
                      "y":195},
                    "size":{
                      "width":264,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/list_of_ambassadors/u28.png"}},
{
              "id":"73509cc4fb8c4aa68ebcdb207263bc96",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":264,
                  "y":220},
                "size":{
                  "width":264,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"41deda8363aa4fc08ff35683b1e93e11",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":264,
                      "y":220},
                    "size":{
                      "width":264,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/list_of_ambassadors/u76.png"}},
{
              "id":"6a4536eb52d843cfb7b92a51ecb4c3b2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":264,
                  "y":250},
                "size":{
                  "width":264,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c6bfb27b127e4ad4bf7099cd1fad8de6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":264,
                      "y":250},
                    "size":{
                      "width":264,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF949494}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/list_of_ambassadors/u82.png"}}]},
{
          "id":"485df33be4df42c5b90ec8fef027c320",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1996C7},
            "location":{
              "x":313,
              "y":200},
            "size":{
              "width":187,
              "height":30},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":0,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00d8b07d63304f85a0b15747538334a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1996C7},
                "location":{
                  "x":313,
                  "y":200},
                "size":{
                  "width":187,
                  "height":30},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":0,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Surveys - Create SMS Survey in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"surveys_-_create_sms_survey.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/surveys/u130.png"}},
{
          "id":"7df5ccd2797040c69acf413cd2e6c860",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":54},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb8c07ff773a47abba83a15093bbf483",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":54},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Dashboard in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"dashboard.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"8c3b551cef4c4feabc14ba31addc0b04",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":95},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96857f7536a743b8b4c7fa26cf31dc7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":95},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open List Of Ambassadors in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"list_of_ambassadors.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"91d280eb97e6434aa425d738c706a8e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":136},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65e7583f791f4a3285df0bfefd3dde76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":136},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Surveys in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"surveys.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"c47b34122e9a4999a720e405007f2164",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":177},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4e4d42d437b4a6c9a2009a98600fc83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":177},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Leads in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"leads.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"dadb749340db4e52872269e8136b817f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1996C7,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":219},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4240fb08dfd745a3b3ce7a7e56cdca12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1996C7,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":219},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News Updates in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news_updates.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"9aee5a195e094138b96eff5fc054cb35",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":261},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b8502356faa472f82aea447efe16753",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":261},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Users in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"users.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}}]}},
  "masters":{
    "e163cbb4cef54461ad56955f368f2e96":{
      "packageId":"e163cbb4cef54461ad56955f368f2e96",
      "type":"Axure:Master",
      "name":"main",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1affd31496854a90aaf55cb21b7c1027",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF9F9F9},
              "size":{
                "width":1366,
                "height":768}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6b795c4f50714ccc8e66f16ce98c2618",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF9F9F9},
                  "size":{
                    "width":1366,
                    "height":768}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u1.png"}},
{
            "id":"cee52dc11a8744b0a43052d502487fd5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF1996C7},
              "size":{
                "width":1366,
                "height":50},
              "borderWidth":"-1",
              "outerShadow":{
                "on":true,
                "offsetX":0,
                "offsetY":1,
                "blurRadius":5,
                "color":{
                  "r":0,
                  "g":0,
                  "b":0,
                  "a":0.349019607843137}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bde88dba9c1a4e2988a327f1c196765c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF1996C7},
                  "size":{
                    "width":1366,
                    "height":50},
                  "borderWidth":"-1",
                  "outerShadow":{
                    "on":true,
                    "offsetX":0,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.349019607843137}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u3.png"}},
{
            "id":"56fbb49b18bd46129591d114da88345e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF0E5570},
              "location":{
                "x":0,
                "y":50},
              "size":{
                "width":1366,
                "height":4},
              "borderWidth":"-1",
              "outerShadow":{
                "on":true,
                "offsetX":0,
                "offsetY":1,
                "blurRadius":5,
                "color":{
                  "r":0,
                  "g":0,
                  "b":0,
                  "a":0.349019607843137}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b9154b46c7af49f6b3c8fa13b5e2aa9c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0E5570},
                  "location":{
                    "x":0,
                    "y":50},
                  "size":{
                    "width":1366,
                    "height":4},
                  "borderWidth":"-1",
                  "outerShadow":{
                    "on":true,
                    "offsetX":0,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.349019607843137}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u5.png"}},
{
            "id":"8e7b142cf5d5486cbc949c1ae82f56d1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF212121},
              "location":{
                "x":0,
                "y":54},
              "size":{
                "width":250,
                "height":714},
              "borderWidth":"-1",
              "outerShadow":{
                "on":true,
                "offsetX":2,
                "offsetY":0,
                "blurRadius":5,
                "color":{
                  "r":0,
                  "g":0,
                  "b":0,
                  "a":0.349019607843137}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59e38fb539e04bb29cde628389cf5bd8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF212121},
                  "location":{
                    "x":0,
                    "y":54},
                  "size":{
                    "width":250,
                    "height":714},
                  "borderWidth":"-1",
                  "outerShadow":{
                    "on":true,
                    "offsetX":2,
                    "offsetY":0,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.349019607843137}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u7.png"}},
{
            "id":"dcdfff1ef73440ecb729883ed1488cee",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"28px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":31,
                "y":7},
              "size":{
                "width":140,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ee24b8d3672d4a26a4e0d5b9d8a0528a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"28px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":31,
                    "y":7},
                  "size":{
                    "width":140,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "b147babde7834c5d80be67f4a49d87fc":{
      "scriptId":"u0",
      "1affd31496854a90aaf55cb21b7c1027":{
        "scriptId":"u1"},
      "6b795c4f50714ccc8e66f16ce98c2618":{
        "scriptId":"u2"},
      "cee52dc11a8744b0a43052d502487fd5":{
        "scriptId":"u3"},
      "bde88dba9c1a4e2988a327f1c196765c":{
        "scriptId":"u4"},
      "56fbb49b18bd46129591d114da88345e":{
        "scriptId":"u5"},
      "b9154b46c7af49f6b3c8fa13b5e2aa9c":{
        "scriptId":"u6"},
      "8e7b142cf5d5486cbc949c1ae82f56d1":{
        "scriptId":"u7"},
      "59e38fb539e04bb29cde628389cf5bd8":{
        "scriptId":"u8"},
      "dcdfff1ef73440ecb729883ed1488cee":{
        "scriptId":"u9"},
      "ee24b8d3672d4a26a4e0d5b9d8a0528a":{
        "scriptId":"u10"}},
    "b2e24ae280514be6a0f7eccf53a9b805":{
      "scriptId":"u11"},
    "3b586b23f61c4f969d039bc62ffec873":{
      "scriptId":"u12"},
    "fa4229a818304ecb8f20c64469727105":{
      "scriptId":"u13"},
    "0f1bb9a2bbad4739ba0185d302efd574":{
      "scriptId":"u14"},
    "6cfdd493c15f4b0fbbcf611321201538":{
      "scriptId":"u15"},
    "54374e6d3a4849b2a2806dab9a4775b2":{
      "scriptId":"u16"},
    "7fb87094ec2747b785e1cb140fb4cab6":{
      "scriptId":"u17"},
    "e1586387c8124e0eb9c42786eb232318":{
      "scriptId":"u18"},
    "37badc0c61174a4e8ab699fcad824687":{
      "scriptId":"u19"},
    "fa2dff89341e409fa7639b797caf1bba":{
      "scriptId":"u20"},
    "296a84963ca14848a07013e425cd7228":{
      "scriptId":"u21"},
    "b55c2b41ea9d413589164ab9c766a68c":{
      "scriptId":"u22"},
    "8a05e8b71d894ab1ba734ba0ff7b490b":{
      "scriptId":"u23"},
    "2712c85751c24529bc02d731bce2d269":{
      "scriptId":"u24"},
    "9327f6493d8143978ad07a4a57ab46aa":{
      "scriptId":"u25"},
    "e23ff2dbb5fc41faa3a8c48967b500a7":{
      "scriptId":"u26"},
    "40e7b5a3d3fe4e62b0fd106d1e104f61":{
      "scriptId":"u27"},
    "9cb0551cabca4970b2dafb8855b75f86":{
      "scriptId":"u28"},
    "4933b1fff99e4c69b9fb448e18d2532f":{
      "scriptId":"u29"},
    "ab3cab915a8c4c6184a9946548716f8a":{
      "scriptId":"u30"},
    "c8b71d13a48e42eeb642f5522365fb90":{
      "scriptId":"u31"},
    "f8137901b6b34536beed603aa9c95491":{
      "scriptId":"u32"},
    "d96bd8ee88cc4350925263227c0b56d2":{
      "scriptId":"u33"},
    "14e2b0e0a8c04cfc9ca06c245b8a3327":{
      "scriptId":"u34"},
    "29ebcbd47a9248dcb949e9523d0255c9":{
      "scriptId":"u35"},
    "a3e62543ee2a44b5ab2afdef68a74dfd":{
      "scriptId":"u36"},
    "e3996a5704984fbcab1ddbe83f263eed":{
      "scriptId":"u37"},
    "d470a41c44ec4f80a67f066bb49ea0c8":{
      "scriptId":"u38"},
    "5475efd7d12c49f9aba47cf3eccc2750":{
      "scriptId":"u39"},
    "ed04a0093d064d98a21afa5ac433541b":{
      "scriptId":"u40"},
    "4b59acab574843f89d64bdcd582654ff":{
      "scriptId":"u41"},
    "a7b6e05b9522436e87ef3096268553d4":{
      "scriptId":"u42"},
    "7f84b2b3feb142b79c17597e8b211c0d":{
      "scriptId":"u43"},
    "7a7acfe90a75411eaca50a7e83ad4575":{
      "scriptId":"u44"},
    "5bd553f511ae4799b91900b15c9f8729":{
      "scriptId":"u45"},
    "44332d4e90cb474baff1f38b7c65df8e":{
      "scriptId":"u46"},
    "bef460f4b6394b139e74c3e9c5d264c4":{
      "scriptId":"u47"},
    "3d27263965884168992949ac00ae40b4":{
      "scriptId":"u48"},
    "9319e9fee39942eca279520554798a2a":{
      "scriptId":"u49"},
    "a745ef5a4e324f74bc1061b0e5103423":{
      "scriptId":"u50"},
    "09195e37636e492c9fd6a305b4e5d8ad":{
      "scriptId":"u51"},
    "ea2a44f876cb492db9a8df9168fa8511":{
      "scriptId":"u52"},
    "f6be8ea3428c4e44a4738714c0e3ab83":{
      "scriptId":"u53"},
    "88a264480ce2445f937c800341637cbb":{
      "scriptId":"u54"},
    "c3760290fe734afeb03a2f390184d79c":{
      "scriptId":"u55"},
    "b132599a52a4490093d7fd9758507d4c":{
      "scriptId":"u56"},
    "e0c65c1d842b473683cee6433802f7f1":{
      "scriptId":"u57"},
    "1208463bf36c4283a518a0f59abc7caf":{
      "scriptId":"u58"},
    "8e9f68abf98947899a13121af64dc1e2":{
      "scriptId":"u59"},
    "f12adba306e546b3810fbf4e3a13a6b8":{
      "scriptId":"u60"},
    "54921efc7c034923a4d8c159ebd629aa":{
      "scriptId":"u61"},
    "da84be11e4a5437ebe3caa63bb606e58":{
      "scriptId":"u62"},
    "18641507d29c4f5887f7c1363ff9c4b0":{
      "scriptId":"u63"},
    "49b73bd8fd0142a8909af025a3ba6dd8":{
      "scriptId":"u64"},
    "5745e2f7a39346a186ff2bb90de50b43":{
      "scriptId":"u65"},
    "5ef7ffb5129c4831a796ef10bfcb1381":{
      "scriptId":"u66"},
    "f80b8423807a42b2bf93932494e774b8":{
      "scriptId":"u67"},
    "ad1717f5d503430cae63f1038b62dee1":{
      "scriptId":"u68"},
    "7333ce7dd87d4a679681f54367d3c4cb":{
      "scriptId":"u69"},
    "9df6841425aa445887e36be611e18916":{
      "scriptId":"u70"},
    "6fc4bfd460ec40ca908b43d8631be5d4":{
      "scriptId":"u71"},
    "0e80ff22cb5a48948f5cd3fc335373d3":{
      "scriptId":"u72"},
    "62d6ebef0e1c4ef786ba09c80a475467":{
      "scriptId":"u73"},
    "f536382567424dc08eb9b1f92f6b5556":{
      "scriptId":"u74"},
    "6979252fa0924f69840b0bd29f40b55c":{
      "scriptId":"u75"},
    "73509cc4fb8c4aa68ebcdb207263bc96":{
      "scriptId":"u76"},
    "41deda8363aa4fc08ff35683b1e93e11":{
      "scriptId":"u77"},
    "dc9c10f6be874b80acc9d8af8a14465d":{
      "scriptId":"u78"},
    "5fd59565240043049e28d25a118774d4":{
      "scriptId":"u79"},
    "05ac645783a94470b02195dff4d1e325":{
      "scriptId":"u80"},
    "47a8cf266de64d0f9d1a56442cce70ce":{
      "scriptId":"u81"},
    "6a4536eb52d843cfb7b92a51ecb4c3b2":{
      "scriptId":"u82"},
    "c6bfb27b127e4ad4bf7099cd1fad8de6":{
      "scriptId":"u83"},
    "ffad79fdd2db4f8980ce3d1193f8f6f4":{
      "scriptId":"u84"},
    "1cb6081c928c4dd0a2baa68909ea94a5":{
      "scriptId":"u85"},
    "485df33be4df42c5b90ec8fef027c320":{
      "scriptId":"u86"},
    "00d8b07d63304f85a0b15747538334a8":{
      "scriptId":"u87"},
    "7df5ccd2797040c69acf413cd2e6c860":{
      "scriptId":"u88"},
    "bb8c07ff773a47abba83a15093bbf483":{
      "scriptId":"u89"},
    "8c3b551cef4c4feabc14ba31addc0b04":{
      "scriptId":"u90"},
    "96857f7536a743b8b4c7fa26cf31dc7c":{
      "scriptId":"u91"},
    "91d280eb97e6434aa425d738c706a8e6":{
      "scriptId":"u92"},
    "65e7583f791f4a3285df0bfefd3dde76":{
      "scriptId":"u93"},
    "c47b34122e9a4999a720e405007f2164":{
      "scriptId":"u94"},
    "c4e4d42d437b4a6c9a2009a98600fc83":{
      "scriptId":"u95"},
    "dadb749340db4e52872269e8136b817f":{
      "scriptId":"u96"},
    "4240fb08dfd745a3b3ce7a7e56cdca12":{
      "scriptId":"u97"},
    "9aee5a195e094138b96eff5fc054cb35":{
      "scriptId":"u98"},
    "4b8502356faa472f82aea447efe16753":{
      "scriptId":"u99"}}});