$axure.loadCurrentPage({
  "url":"surveys_-_create_ambassador_survey.html",
  "generationDate":new Date(1479235412807.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c9c628e1d5ff46c2844ed4b666ced618",
    "type":"Axure:Page",
    "name":"Surveys - Create Ambassador Survey",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ed9e661311c14ecabc6e21374bd7da49",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"e163cbb4cef54461ad56955f368f2e96"},
{
          "id":"50d2b2d4c29646dc93056ec91da36a68",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":293,
              "y":142},
            "size":{
              "width":1022,
              "height":368},
            "borderWidth":"-1",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":0,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"275a469800b24cfba05d332b439140ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":293,
                  "y":142},
                "size":{
                  "width":1022,
                  "height":368},
                "borderWidth":"-1",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":0,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/surveys_-_create_ambassador_survey/u11.png"}},
{
          "id":"25d072d34c744d62ae340b57ca681863",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Regular', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":294,
              "y":72},
            "size":{
              "width":313,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6187c0abb18745ea9d858ede21541561",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Regular', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":294,
                  "y":72},
                "size":{
                  "width":313,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff04d3ec6cb7424382e0f3a344183d96",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1996C7},
            "location":{
              "x":293,
              "y":142},
            "size":{
              "width":1022,
              "height":35},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"940f47bfa61648ed8dcf3ffe78419feb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1996C7},
                "location":{
                  "x":293,
                  "y":142},
                "size":{
                  "width":1022,
                  "height":35},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/list_of_ambassadors/u15.png"}},
{
          "id":"918f877e9e35486abb8c4d5bc8e98b25",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1996C7},
            "location":{
              "x":374.5,
              "y":315},
            "size":{
              "width":70,
              "height":30},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":0,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8f411eaa0f340bb90251975fd0bdef6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1996C7},
                "location":{
                  "x":374.5,
                  "y":315},
                "size":{
                  "width":70,
                  "height":30},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":0,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Surveys - Create Ambassador Survey 2 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"surveys_-_create_ambassador_survey_2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/list_of_ambassadors/u17.png"}},
{
          "id":"252c3ea977e04b33bad22c1e6040a192",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":320,
              "y":204},
            "size":{
              "width":120,
              "height":1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"659498bd263a411a8fb6a44e2c7cf5ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":320,
                  "y":204},
                "size":{
                  "width":120,
                  "height":1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dace2d499e614335866f98ae3a7c8027",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1996C7},
            "location":{
              "x":470,
              "y":315},
            "size":{
              "width":70,
              "height":30},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":0,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3eda7000f1e34d3fbe473b5698a9bafe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1996C7},
                "location":{
                  "x":470,
                  "y":315},
                "size":{
                  "width":70,
                  "height":30},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":0,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/list_of_ambassadors/u17.png"}},
{
          "id":"c190ac8a34eb4b57a79552ba8e9253b0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":204},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6243d4275f174a99829a7f65fe3fd59b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":54},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed58bae73d4f4ed489880a7634a832be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":54},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Dashboard in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"dashboard.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"9ddc05f622b2482d875d08f58c41101a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":95},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"792f67aa536a4c489d102d3e941928b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":95},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open List Of Ambassadors in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"list_of_ambassadors.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"d90d3e14afd44e6894a3388805b166f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1996C7,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":136},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51a43d8cc8dc4f6f9a2d8ce3f37b52cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1996C7,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":136},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Surveys in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"surveys.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"adc503da41404a1c856c768427c383e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":177},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"047997298712442eac28f9b427ec2ebd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":177},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Leads in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"leads.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"2db9d2a050de4ba2a6566bf6b745a6ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":219},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70737ac9906d449f94ed15dfb3014806",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":219},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News Updates in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news_updates.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"a40d6cf5baa74fea94cc9af097d4eaf6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":261},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e4c2c9a64b045ddbf6f23c08c52eb49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":261},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Users in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"users.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"7bfd5b9c16174a9f8a55f9d13aebfd3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":-1,
              "y":303},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fc475afc1a2490d95823cd19b651cec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":-1,
                  "y":303},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Events in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"events.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}}]}},
  "masters":{
    "e163cbb4cef54461ad56955f368f2e96":{
      "packageId":"e163cbb4cef54461ad56955f368f2e96",
      "type":"Axure:Master",
      "name":"main",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1affd31496854a90aaf55cb21b7c1027",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF9F9F9},
              "size":{
                "width":1366,
                "height":768}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6b795c4f50714ccc8e66f16ce98c2618",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF9F9F9},
                  "size":{
                    "width":1366,
                    "height":768}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u1.png"}},
{
            "id":"cee52dc11a8744b0a43052d502487fd5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF1996C7},
              "size":{
                "width":1366,
                "height":50},
              "borderWidth":"-1",
              "outerShadow":{
                "on":true,
                "offsetX":0,
                "offsetY":1,
                "blurRadius":5,
                "color":{
                  "r":0,
                  "g":0,
                  "b":0,
                  "a":0.349019607843137}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bde88dba9c1a4e2988a327f1c196765c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF1996C7},
                  "size":{
                    "width":1366,
                    "height":50},
                  "borderWidth":"-1",
                  "outerShadow":{
                    "on":true,
                    "offsetX":0,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.349019607843137}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u3.png"}},
{
            "id":"56fbb49b18bd46129591d114da88345e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF0E5570},
              "location":{
                "x":0,
                "y":50},
              "size":{
                "width":1366,
                "height":4},
              "borderWidth":"-1",
              "outerShadow":{
                "on":true,
                "offsetX":0,
                "offsetY":1,
                "blurRadius":5,
                "color":{
                  "r":0,
                  "g":0,
                  "b":0,
                  "a":0.349019607843137}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b9154b46c7af49f6b3c8fa13b5e2aa9c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0E5570},
                  "location":{
                    "x":0,
                    "y":50},
                  "size":{
                    "width":1366,
                    "height":4},
                  "borderWidth":"-1",
                  "outerShadow":{
                    "on":true,
                    "offsetX":0,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.349019607843137}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u5.png"}},
{
            "id":"8e7b142cf5d5486cbc949c1ae82f56d1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF212121},
              "location":{
                "x":0,
                "y":54},
              "size":{
                "width":250,
                "height":714},
              "borderWidth":"-1",
              "outerShadow":{
                "on":true,
                "offsetX":2,
                "offsetY":0,
                "blurRadius":5,
                "color":{
                  "r":0,
                  "g":0,
                  "b":0,
                  "a":0.349019607843137}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59e38fb539e04bb29cde628389cf5bd8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF212121},
                  "location":{
                    "x":0,
                    "y":54},
                  "size":{
                    "width":250,
                    "height":714},
                  "borderWidth":"-1",
                  "outerShadow":{
                    "on":true,
                    "offsetX":2,
                    "offsetY":0,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.349019607843137}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u7.png"}},
{
            "id":"dcdfff1ef73440ecb729883ed1488cee",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"28px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":31,
                "y":7},
              "size":{
                "width":140,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ee24b8d3672d4a26a4e0d5b9d8a0528a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"28px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":31,
                    "y":7},
                  "size":{
                    "width":140,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "ed9e661311c14ecabc6e21374bd7da49":{
      "scriptId":"u0",
      "1affd31496854a90aaf55cb21b7c1027":{
        "scriptId":"u1"},
      "6b795c4f50714ccc8e66f16ce98c2618":{
        "scriptId":"u2"},
      "cee52dc11a8744b0a43052d502487fd5":{
        "scriptId":"u3"},
      "bde88dba9c1a4e2988a327f1c196765c":{
        "scriptId":"u4"},
      "56fbb49b18bd46129591d114da88345e":{
        "scriptId":"u5"},
      "b9154b46c7af49f6b3c8fa13b5e2aa9c":{
        "scriptId":"u6"},
      "8e7b142cf5d5486cbc949c1ae82f56d1":{
        "scriptId":"u7"},
      "59e38fb539e04bb29cde628389cf5bd8":{
        "scriptId":"u8"},
      "dcdfff1ef73440ecb729883ed1488cee":{
        "scriptId":"u9"},
      "ee24b8d3672d4a26a4e0d5b9d8a0528a":{
        "scriptId":"u10"}},
    "50d2b2d4c29646dc93056ec91da36a68":{
      "scriptId":"u11"},
    "275a469800b24cfba05d332b439140ad":{
      "scriptId":"u12"},
    "25d072d34c744d62ae340b57ca681863":{
      "scriptId":"u13"},
    "6187c0abb18745ea9d858ede21541561":{
      "scriptId":"u14"},
    "ff04d3ec6cb7424382e0f3a344183d96":{
      "scriptId":"u15"},
    "940f47bfa61648ed8dcf3ffe78419feb":{
      "scriptId":"u16"},
    "918f877e9e35486abb8c4d5bc8e98b25":{
      "scriptId":"u17"},
    "c8f411eaa0f340bb90251975fd0bdef6":{
      "scriptId":"u18"},
    "252c3ea977e04b33bad22c1e6040a192":{
      "scriptId":"u19"},
    "659498bd263a411a8fb6a44e2c7cf5ce":{
      "scriptId":"u20"},
    "dace2d499e614335866f98ae3a7c8027":{
      "scriptId":"u21"},
    "3eda7000f1e34d3fbe473b5698a9bafe":{
      "scriptId":"u22"},
    "c190ac8a34eb4b57a79552ba8e9253b0":{
      "scriptId":"u23"},
    "6243d4275f174a99829a7f65fe3fd59b":{
      "scriptId":"u24"},
    "ed58bae73d4f4ed489880a7634a832be":{
      "scriptId":"u25"},
    "9ddc05f622b2482d875d08f58c41101a":{
      "scriptId":"u26"},
    "792f67aa536a4c489d102d3e941928b9":{
      "scriptId":"u27"},
    "d90d3e14afd44e6894a3388805b166f2":{
      "scriptId":"u28"},
    "51a43d8cc8dc4f6f9a2d8ce3f37b52cc":{
      "scriptId":"u29"},
    "adc503da41404a1c856c768427c383e9":{
      "scriptId":"u30"},
    "047997298712442eac28f9b427ec2ebd":{
      "scriptId":"u31"},
    "2db9d2a050de4ba2a6566bf6b745a6ac":{
      "scriptId":"u32"},
    "70737ac9906d449f94ed15dfb3014806":{
      "scriptId":"u33"},
    "a40d6cf5baa74fea94cc9af097d4eaf6":{
      "scriptId":"u34"},
    "0e4c2c9a64b045ddbf6f23c08c52eb49":{
      "scriptId":"u35"},
    "7bfd5b9c16174a9f8a55f9d13aebfd3b":{
      "scriptId":"u36"},
    "2fc475afc1a2490d95823cd19b651cec":{
      "scriptId":"u37"}}});