$axure.loadCurrentPage({
  "url":"login.html",
  "generationDate":new Date(1470822544783.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c761ecabff6f4352ad2d43decd859d23",
    "type":"Axure:Page",
    "name":"Login",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f1d12d64d171410fb281310ad179260d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":-43},
            "size":{
              "width":469,
              "height":813}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52504cad537b4606882b8f2fa8623e60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":-43},
                "size":{
                  "width":469,
                  "height":813}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/splash/u0.png"}},
{
          "id":"f93edf6064344342b9a49a003914a300",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9FAF5},
            "location":{
              "x":181,
              "y":103},
            "size":{
              "width":295,
              "height":523},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c53b998aef844a78da8960e16f2448c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9FAF5},
                "location":{
                  "x":181,
                  "y":103},
                "size":{
                  "width":295,
                  "height":523},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/splash/u2.png"}},
{
          "id":"c43490046a034d3983d0b4fbb5f69183",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":342},
            "size":{
              "width":214,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4CAF50}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/login/u4_line.png"}},
{
          "id":"b61a4ffc421e44969495cdfeb203928c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":392},
            "size":{
              "width":214,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4CAF50}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/login/u4_line.png"}},
{
          "id":"c3a25b4c295f4f4cbc18c47bfade56d7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "location":{
              "x":181,
              "y":103},
            "size":{
              "width":295,
              "height":38},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":5,
              "color":{
                "r":94,
                "g":94,
                "b":94,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a1911db10e04ec6a959222ebe27400e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "location":{
                  "x":181,
                  "y":103},
                "size":{
                  "width":295,
                  "height":38},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":5,
                  "color":{
                    "r":94,
                    "g":94,
                    "b":94,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u6.png"}},
{
          "id":"cf44ae3f0361403a8020e29e4ddb72ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "fontSize":"17px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xDDFFFFFF,
              "opacity":0.866666674613953},
            "baseStyle":"6e631585fe0e401a93235178bc877cb7",
            "location":{
              "x":198,
              "y":111},
            "size":{
              "width":44,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e07aa09fa9294afe85f5ea95866e7fdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "fontSize":"17px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xDDFFFFFF,
                  "opacity":0.866666674613953},
                "baseStyle":"6e631585fe0e401a93235178bc877cb7",
                "location":{
                  "x":198,
                  "y":111},
                "size":{
                  "width":44,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b885e68584974338be9620eea8341fdf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "fontSize":"15px",
            "fontWeight":"500",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4CAF50,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":381,
              "y":417},
            "size":{
              "width":56,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d23ac752fd724cd3b4d807846d7a6fbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "fontSize":"15px",
                "fontWeight":"500",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4CAF50,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":381,
                  "y":417},
                "size":{
                  "width":56,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Take Photo in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"take_photo.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3fe8a3ab48754b3481b0c91b2d368668",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4CAF50,
              "opacity":1},
            "baseStyle":"db0f01df1fcf495085ab10f03b87b2cb",
            "location":{
              "x":278,
              "y":593},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"172916ca93204a7fba4c19ff4d5455b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4CAF50,
                  "opacity":1},
                "baseStyle":"db0f01df1fcf495085ab10f03b87b2cb",
                "location":{
                  "x":278,
                  "y":593},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Login - Forget Password in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"login_-_forget_password.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08c282e7355a4eb19e982a8dd30cdf14",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x89000000,
              "opacity":0.537254929542542},
            "stateStyles":{
              "hint":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "fontWeight":"400",
                "fontStyle":"normal"}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":217,
              "y":316},
            "size":{
              "width":217,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":""},
{
          "id":"2c08a737c7244f36966e2f51be1657c3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x89000000,
              "opacity":0.537254929542542},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":217,
              "y":366},
            "size":{
              "width":217,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d254143367d14a70bfad424719472b5d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":264,
              "y":174},
            "size":{
              "width":131,
              "height":89}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d6e4b0bac4c4c77a6e1e19133e32250",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":264,
                  "y":174},
                "size":{
                  "width":131,
                  "height":89}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/splash/u4.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f1d12d64d171410fb281310ad179260d":{
      "scriptId":"u0"},
    "52504cad537b4606882b8f2fa8623e60":{
      "scriptId":"u1"},
    "f93edf6064344342b9a49a003914a300":{
      "scriptId":"u2"},
    "4c53b998aef844a78da8960e16f2448c":{
      "scriptId":"u3"},
    "c43490046a034d3983d0b4fbb5f69183":{
      "scriptId":"u4"},
    "b61a4ffc421e44969495cdfeb203928c":{
      "scriptId":"u5"},
    "c3a25b4c295f4f4cbc18c47bfade56d7":{
      "scriptId":"u6"},
    "3a1911db10e04ec6a959222ebe27400e":{
      "scriptId":"u7"},
    "cf44ae3f0361403a8020e29e4ddb72ee":{
      "scriptId":"u8"},
    "e07aa09fa9294afe85f5ea95866e7fdd":{
      "scriptId":"u9"},
    "b885e68584974338be9620eea8341fdf":{
      "scriptId":"u10"},
    "d23ac752fd724cd3b4d807846d7a6fbd":{
      "scriptId":"u11"},
    "3fe8a3ab48754b3481b0c91b2d368668":{
      "scriptId":"u12"},
    "172916ca93204a7fba4c19ff4d5455b0":{
      "scriptId":"u13"},
    "08c282e7355a4eb19e982a8dd30cdf14":{
      "scriptId":"u14"},
    "2c08a737c7244f36966e2f51be1657c3":{
      "scriptId":"u15"},
    "d254143367d14a70bfad424719472b5d":{
      "scriptId":"u16"},
    "8d6e4b0bac4c4c77a6e1e19133e32250":{
      "scriptId":"u17"}}});