$axure.loadCurrentPage({
  "url":"take_holy_communion.html",
  "generationDate":new Date(1481354582801.66),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"da088a4a3111452fab56589a11493fdd",
    "type":"Axure:Page",
    "name":"Take Holy Communion",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e7a262b522284df4b0918f50c6d532b9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":-43}},
          "adaptiveStyles":{
},
          "masterId":"866c22c904d0473f85c124c9890df389"},
{
          "id":"841cce0d009b440ca79949a6d41852d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4CAF50,
              "opacity":1},
            "location":{
              "x":190,
              "y":160},
            "size":{
              "width":280,
              "height":440},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7c22e605cf7406da1abf5945160f660",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4CAF50,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":160},
                "size":{
                  "width":280,
                  "height":440},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/take_holy_communion/u5.png"}},
{
          "id":"547d984a6cdb476b887a1f58c347808f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":477},
            "size":{
              "width":280,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/take_holy_communion/u7_line.png"}},
{
          "id":"0e45dbebb5fe4a5598cf858e38fce49b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "location":{
              "x":193,
              "y":254},
            "size":{
              "width":22,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38c705095a0d4c90a95923d30102223b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "location":{
                  "x":193,
                  "y":254},
                "size":{
                  "width":22,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/take_holy_communion/u8.png"}},
{
          "id":"6c4aaf7796df4c7497ba93add09c0fae",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "location":{
              "x":181,
              "y":103},
            "size":{
              "width":295,
              "height":43},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":5,
              "color":{
                "r":94,
                "g":94,
                "b":94,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8254199a66a44fde931929895163f87f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "location":{
                  "x":181,
                  "y":103},
                "size":{
                  "width":295,
                  "height":43},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":5,
                  "color":{
                    "r":94,
                    "g":94,
                    "b":94,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/take_holy_communion/u10.png"}},
{
          "id":"7c4873ea81d443929c22c6e360d92a89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "fontSize":"17px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xDDFFFFFF,
              "opacity":0.866666674613953},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF8445AD},
            "location":{
              "x":220,
              "y":112},
            "size":{
              "width":140,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"915081ce2fe44076b27ca45c02d1ded6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "fontSize":"17px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xDDFFFFFF,
                  "opacity":0.866666674613953},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8445AD},
                "location":{
                  "x":220,
                  "y":112},
                "size":{
                  "width":140,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/take_holy_communion/u12.png"}},
{
          "id":"b022fca8480c4c5db413d86463fc9763",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "verticalAlignment":"middle",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "lineSpacing":"20px",
            "location":{
              "x":198,
              "y":400},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b60d30fe1c6b4e6f83a22a8bf22145fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "verticalAlignment":"middle",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "lineSpacing":"20px",
                "location":{
                  "x":198,
                  "y":400},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"52c4a708139b4d61b0a1d74670191547",
          "label":"Menu Icon",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "location":{
              "x":181,
              "y":104},
            "size":{
              "width":38,
              "height":33},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c492234b8eb54e87a10adf4382dc1310",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "location":{
                  "x":181,
                  "y":104},
                "size":{
                  "width":38,
                  "height":33},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1<br> (If state of Unidentified equals Unidentified)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["d8495c5424bb4a1da3455bb885390dfa"]}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["d8495c5424bb4a1da3455bb885390dfa"],
                      "panelIndex":0}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]},
{
                  "description":"Case 2<br> (Else If state of Unidentified equals Unidentified)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["d8495c5424bb4a1da3455bb885390dfa"]}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["d8495c5424bb4a1da3455bb885390dfa"],
                      "panelIndex":0}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/take_holy_communion/menu_icon_u16.png"}},
{
          "id":"f06137b6a55748649b0d5709e2723c14",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2E2925,
              "opacity":1},
            "location":{
              "x":201,
              "y":168},
            "size":{
              "width":186,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce0642c93add495f913dc289123ec49f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2E2925,
                  "opacity":1},
                "location":{
                  "x":201,
                  "y":168},
                "size":{
                  "width":186,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"817ff43da5ed4e1c96d1d567f1f44136",
          "label":"Menu Icon",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "location":{
              "x":181,
              "y":104},
            "size":{
              "width":38,
              "height":33},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d6642f2f1a0404eaf63b348451b85f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "location":{
                  "x":181,
                  "y":104},
                "size":{
                  "width":38,
                  "height":33},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1<br> (If state of (Dynamic Panel) equals Invisible)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["50f7dbb0d48f4bb7ba49cef204c31166"]}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["50f7dbb0d48f4bb7ba49cef204c31166"],
                      "panelIndex":0}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set (Dynamic Panel) to visible slide left out 500ms slide right in 500ms",
                      "panelsToStates":[{
                          "panelPath":["50f7dbb0d48f4bb7ba49cef204c31166"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"slideLeft",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideRight",
                                "duration":500},
                              "compress":false}}}]}]},
{
                  "description":"Case 2<br> (Else If state of (Dynamic Panel) equals visible)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["50f7dbb0d48f4bb7ba49cef204c31166"]}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["50f7dbb0d48f4bb7ba49cef204c31166"],
                      "panelIndex":1}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set (Dynamic Panel) to Invisible slide left out 500ms slide right in 500ms",
                      "panelsToStates":[{
                          "panelPath":["50f7dbb0d48f4bb7ba49cef204c31166"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"slideLeft",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideRight",
                                "duration":500},
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/take_holy_communion/menu_icon_u16.png"}},
{
          "id":"fffbff09396641918ead74ad935b6080",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF8445AD},
            "location":{
              "x":391,
              "y":520},
            "size":{
              "width":49,
              "height":48},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7ebc1c8d8f0428d8945a77543bb1d16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8445AD},
                "location":{
                  "x":391,
                  "y":520},
                "size":{
                  "width":49,
                  "height":48},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/take_holy_communion/u22.png"}},
{
          "id":"50f7dbb0d48f4bb7ba49cef204c31166",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":181,
              "y":144},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"0bda7804f73c400a85e51bf2597dbc78",
              "label":"Invisible",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"9eceb8dffe974e529e9474b2d64ee315",
              "label":"visible",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f6ff7eef0def4403939c0c69fc0cffad",
                  "label":"",
                  "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF8445AD},
                    "size":{
                      "width":229,
                      "height":482}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6e56ab9bc5b74211b9c57cbbaca1ec7b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF8445AD},
                        "size":{
                          "width":229,
                          "height":482}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_holy_communion/u25.png"}},
{
                  "id":"4f716063e18343ddb6e513ec1d3dcac0",
                  "label":"",
                  "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "verticalAlignment":"middle",
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "lineSpacing":"20px",
                    "location":{
                      "x":17,
                      "y":255},
                    "size":{
                      "width":74,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d2271d9e196d44d98ce3584f2d7f9a10",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "verticalAlignment":"middle",
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "lineSpacing":"20px",
                        "location":{
                          "x":17,
                          "y":255},
                        "size":{
                          "width":74,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8dc54012aa914ea2a5617848a226e199",
                  "label":"",
                  "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "location":{
                      "x":-2,
                      "y":0},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"85d2f8429808405e8f221adc738d249f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "location":{
                          "x":-2,
                          "y":0},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_holy_communion/u29.png"}},
{
                  "id":"793ce23f8be9483cac2abf387f38344d",
                  "label":"",
                  "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":59,
                      "y":12},
                    "size":{
                      "width":168,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"deed5e0fb222432d923774e737cccc11",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":59,
                          "y":12},
                        "size":{
                          "width":168,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6abe5e5254e94dbd8a14f01ca2e2de05",
                  "label":"",
                  "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "verticalAlignment":"bottom",
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "location":{
                      "x":0,
                      "y":62},
                    "size":{
                      "width":229,
                      "height":63},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1026950b8a664ab1b4b46b7408ef21bd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "verticalAlignment":"bottom",
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "location":{
                          "x":0,
                          "y":62},
                        "size":{
                          "width":229,
                          "height":63},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_holy_communion/u33.png"}},
{
                  "id":"fdbb82349edc49829f043b3be5ec7ccc",
                  "label":"",
                  "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":57,
                      "y":75},
                    "size":{
                      "width":162,
                      "height":38}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"943ad73a0abf47918bfebe4967b7703c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":57,
                          "y":75},
                        "size":{
                          "width":162,
                          "height":38}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ab5f0da54ddc43acadfdfad8981802d5",
                  "label":"",
                  "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "location":{
                      "x":0,
                      "y":125},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6053e5e9a199485898b307169f43ec77",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "location":{
                          "x":0,
                          "y":125},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_holy_communion/u29.png"}},
{
                  "id":"9cdb7fd7331c49f985164dc1adbe7192",
                  "label":"",
                  "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":61,
                      "y":137},
                    "size":{
                      "width":158,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e0b89751c93d492c954d9578e13d210e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":61,
                          "y":137},
                        "size":{
                          "width":158,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3b3e2228ac4e40e5b7db05f6212b9dbb",
                  "label":"",
                  "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "location":{
                      "x":0,
                      "y":187},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"809fd5356d4d4b8c9feb1b1799e80399",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "location":{
                          "x":0,
                          "y":187},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_holy_communion/u29.png"}},
{
                  "id":"1035aa1e2bcb4a539c27f699db922571",
                  "label":"",
                  "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":61,
                      "y":199},
                    "size":{
                      "width":158,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f8d295d088f845f79d927ab0ea31d708",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":61,
                          "y":199},
                        "size":{
                          "width":158,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"871b9b4f5c6c415dadf842880a9ba2b7",
                  "label":"",
                  "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                  "panelIndex":1,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0386610fcc8146eda8768d49ea96c0a0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Link in Current Window",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/take_holy_communion/u45.png"}},
{
                  "id":"2c5ce64c27184eb0b8b557cf7cf99e75",
                  "label":"",
                  "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                  "panelIndex":1,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":62},
                    "size":{
                      "width":229,
                      "height":64},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5af49a78cf2d4d23b4158eaf6d85d8ce",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":62},
                        "size":{
                          "width":229,
                          "height":64},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Take Holy Communion in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"take_holy_communion.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"28394bbeb8064466a5db6271a8e0d2c9",
                  "label":"",
                  "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                  "panelIndex":1,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":125},
                    "size":{
                      "width":229,
                      "height":64},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"359ba52ff3634a7fa0f2d23f1ab6126c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":125},
                        "size":{
                          "width":229,
                          "height":64},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Take Holy Communion in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"take_holy_communion.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bc9cb4ad015948d48c219c01f99e9dc9",
                  "label":"",
                  "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                  "panelIndex":1,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":1,
                      "y":187},
                    "size":{
                      "width":229,
                      "height":64},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b48e87b593904cf6a36a4f2ea918af31",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":1,
                          "y":187},
                        "size":{
                          "width":229,
                          "height":64},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Take Holy Communion in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"take_holy_communion.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5c2f81a591884c2cb6723c4c16799abd",
                  "label":"",
                  "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "location":{
                      "x":0,
                      "y":249},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"68d3f3b11a9c4181868b4755382ab3c7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "location":{
                          "x":0,
                          "y":249},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_holy_communion/u29.png"}},
{
                  "id":"b86b04bcf6bb4522abe39a413ceababe",
                  "label":"",
                  "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":61,
                      "y":261},
                    "size":{
                      "width":158,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0f56f90d17394df9b8f513cc2bf79814",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":61,
                          "y":261},
                        "size":{
                          "width":158,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f1978fbe50ef4f9db7c2de0bf00fccdc",
                  "label":"",
                  "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                  "panelIndex":1,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":1,
                      "y":249},
                    "size":{
                      "width":229,
                      "height":64},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1fdfdfcf49914ddf8e06725d2c943b12",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":1,
                          "y":249},
                        "size":{
                          "width":229,
                          "height":64},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Take Holy Communion in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"take_holy_communion.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0672f1141366494d886245505d6ed4fb",
                  "label":"",
                  "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "location":{
                      "x":0,
                      "y":312},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"acc1778493814238a3d3dea731d3ad29",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "location":{
                          "x":0,
                          "y":312},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_holy_communion/u29.png"}},
{
                  "id":"ea9ba398459249edb50a2e9eb461e16c",
                  "label":"",
                  "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":61,
                      "y":324},
                    "size":{
                      "width":158,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4de35a34ffa249c8b3d1c6011e2eb0f3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":61,
                          "y":324},
                        "size":{
                          "width":158,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"226f7bab072d4d04994f056068b30096",
                  "label":"",
                  "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                  "panelIndex":1,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":312},
                    "size":{
                      "width":229,
                      "height":64},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d7630d6a0a9f42c3af6d318cb2d8ea0e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":312},
                        "size":{
                          "width":229,
                          "height":64},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Take Holy Communion in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"take_holy_communion.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c7730264244c413c9beef3098397e606",
                  "label":"",
                  "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "location":{
                      "x":-1,
                      "y":375},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3b3cefab8c20431e9e1a30db6a9a5155",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "location":{
                          "x":-1,
                          "y":375},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/take_holy_communion/u29.png"}},
{
                  "id":"a671a47bdffd42f0abcb5f79348bcc19",
                  "label":"",
                  "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":60,
                      "y":387},
                    "size":{
                      "width":158,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"db07847f1f744fc88e9c904675c09973",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":60,
                          "y":387},
                        "size":{
                          "width":158,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bec994d07b534033ae96bec056c85efa",
                  "label":"",
                  "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                  "panelIndex":1,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":1,
                      "y":375},
                    "size":{
                      "width":229,
                      "height":64},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"86efdec040b84a6da2de12a2a929b6ee",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50f7dbb0d48f4bb7ba49cef204c31166",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":1,
                          "y":375},
                        "size":{
                          "width":229,
                          "height":64},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Take Holy Communion in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"take_holy_communion.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"ccc4bc2d67be4c5ca392ce24b1d3a98c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":192},
            "size":{
              "width":280,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/take_holy_communion/u7_line.png"}},
{
          "id":"ab60130094074eaaaa88fd458f30f5a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2E2925,
              "opacity":1},
            "location":{
              "x":210,
              "y":209},
            "size":{
              "width":37,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"837eaf102b2a4fd28ef10c0f3a69c85a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2E2925,
                  "opacity":1},
                "location":{
                  "x":210,
                  "y":209},
                "size":{
                  "width":37,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "866c22c904d0473f85c124c9890df389":{
      "packageId":"866c22c904d0473f85c124c9890df389",
      "type":"Axure:Master",
      "name":"frame-plain",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"786c97fb188e44ee8e7e5f4a26a54118",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":90,
                "y":-43},
              "size":{
                "width":469,
                "height":813}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cff2973955f54ebe8c64abe06b548aee",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":90,
                    "y":-43},
                  "size":{
                    "width":469,
                    "height":813}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/take_holy_communion/u1.png"}},
{
            "id":"67400802aab24ac38de05902cd4eb835",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF9FAF5},
              "location":{
                "x":181,
                "y":103},
              "size":{
                "width":295,
                "height":523},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eea47f19de544c8b962b75de32a1caf9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF9FAF5},
                  "location":{
                    "x":181,
                    "y":103},
                  "size":{
                    "width":295,
                    "height":523},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/take_holy_communion/u3.png"}}]}}},
  "objectPaths":{
    "e7a262b522284df4b0918f50c6d532b9":{
      "scriptId":"u0",
      "786c97fb188e44ee8e7e5f4a26a54118":{
        "scriptId":"u1"},
      "cff2973955f54ebe8c64abe06b548aee":{
        "scriptId":"u2"},
      "67400802aab24ac38de05902cd4eb835":{
        "scriptId":"u3"},
      "eea47f19de544c8b962b75de32a1caf9":{
        "scriptId":"u4"}},
    "841cce0d009b440ca79949a6d41852d1":{
      "scriptId":"u5"},
    "e7c22e605cf7406da1abf5945160f660":{
      "scriptId":"u6"},
    "547d984a6cdb476b887a1f58c347808f":{
      "scriptId":"u7"},
    "0e45dbebb5fe4a5598cf858e38fce49b":{
      "scriptId":"u8"},
    "38c705095a0d4c90a95923d30102223b":{
      "scriptId":"u9"},
    "6c4aaf7796df4c7497ba93add09c0fae":{
      "scriptId":"u10"},
    "8254199a66a44fde931929895163f87f":{
      "scriptId":"u11"},
    "7c4873ea81d443929c22c6e360d92a89":{
      "scriptId":"u12"},
    "915081ce2fe44076b27ca45c02d1ded6":{
      "scriptId":"u13"},
    "b022fca8480c4c5db413d86463fc9763":{
      "scriptId":"u14"},
    "b60d30fe1c6b4e6f83a22a8bf22145fd":{
      "scriptId":"u15"},
    "52c4a708139b4d61b0a1d74670191547":{
      "scriptId":"u16"},
    "c492234b8eb54e87a10adf4382dc1310":{
      "scriptId":"u17"},
    "f06137b6a55748649b0d5709e2723c14":{
      "scriptId":"u18"},
    "ce0642c93add495f913dc289123ec49f":{
      "scriptId":"u19"},
    "817ff43da5ed4e1c96d1d567f1f44136":{
      "scriptId":"u20"},
    "8d6642f2f1a0404eaf63b348451b85f5":{
      "scriptId":"u21"},
    "fffbff09396641918ead74ad935b6080":{
      "scriptId":"u22"},
    "e7ebc1c8d8f0428d8945a77543bb1d16":{
      "scriptId":"u23"},
    "50f7dbb0d48f4bb7ba49cef204c31166":{
      "scriptId":"u24"},
    "f6ff7eef0def4403939c0c69fc0cffad":{
      "scriptId":"u25"},
    "6e56ab9bc5b74211b9c57cbbaca1ec7b":{
      "scriptId":"u26"},
    "4f716063e18343ddb6e513ec1d3dcac0":{
      "scriptId":"u27"},
    "d2271d9e196d44d98ce3584f2d7f9a10":{
      "scriptId":"u28"},
    "8dc54012aa914ea2a5617848a226e199":{
      "scriptId":"u29"},
    "85d2f8429808405e8f221adc738d249f":{
      "scriptId":"u30"},
    "793ce23f8be9483cac2abf387f38344d":{
      "scriptId":"u31"},
    "deed5e0fb222432d923774e737cccc11":{
      "scriptId":"u32"},
    "6abe5e5254e94dbd8a14f01ca2e2de05":{
      "scriptId":"u33"},
    "1026950b8a664ab1b4b46b7408ef21bd":{
      "scriptId":"u34"},
    "fdbb82349edc49829f043b3be5ec7ccc":{
      "scriptId":"u35"},
    "943ad73a0abf47918bfebe4967b7703c":{
      "scriptId":"u36"},
    "ab5f0da54ddc43acadfdfad8981802d5":{
      "scriptId":"u37"},
    "6053e5e9a199485898b307169f43ec77":{
      "scriptId":"u38"},
    "9cdb7fd7331c49f985164dc1adbe7192":{
      "scriptId":"u39"},
    "e0b89751c93d492c954d9578e13d210e":{
      "scriptId":"u40"},
    "3b3e2228ac4e40e5b7db05f6212b9dbb":{
      "scriptId":"u41"},
    "809fd5356d4d4b8c9feb1b1799e80399":{
      "scriptId":"u42"},
    "1035aa1e2bcb4a539c27f699db922571":{
      "scriptId":"u43"},
    "f8d295d088f845f79d927ab0ea31d708":{
      "scriptId":"u44"},
    "871b9b4f5c6c415dadf842880a9ba2b7":{
      "scriptId":"u45"},
    "0386610fcc8146eda8768d49ea96c0a0":{
      "scriptId":"u46"},
    "2c5ce64c27184eb0b8b557cf7cf99e75":{
      "scriptId":"u47"},
    "5af49a78cf2d4d23b4158eaf6d85d8ce":{
      "scriptId":"u48"},
    "28394bbeb8064466a5db6271a8e0d2c9":{
      "scriptId":"u49"},
    "359ba52ff3634a7fa0f2d23f1ab6126c":{
      "scriptId":"u50"},
    "bc9cb4ad015948d48c219c01f99e9dc9":{
      "scriptId":"u51"},
    "b48e87b593904cf6a36a4f2ea918af31":{
      "scriptId":"u52"},
    "5c2f81a591884c2cb6723c4c16799abd":{
      "scriptId":"u53"},
    "68d3f3b11a9c4181868b4755382ab3c7":{
      "scriptId":"u54"},
    "b86b04bcf6bb4522abe39a413ceababe":{
      "scriptId":"u55"},
    "0f56f90d17394df9b8f513cc2bf79814":{
      "scriptId":"u56"},
    "f1978fbe50ef4f9db7c2de0bf00fccdc":{
      "scriptId":"u57"},
    "1fdfdfcf49914ddf8e06725d2c943b12":{
      "scriptId":"u58"},
    "0672f1141366494d886245505d6ed4fb":{
      "scriptId":"u59"},
    "acc1778493814238a3d3dea731d3ad29":{
      "scriptId":"u60"},
    "ea9ba398459249edb50a2e9eb461e16c":{
      "scriptId":"u61"},
    "4de35a34ffa249c8b3d1c6011e2eb0f3":{
      "scriptId":"u62"},
    "226f7bab072d4d04994f056068b30096":{
      "scriptId":"u63"},
    "d7630d6a0a9f42c3af6d318cb2d8ea0e":{
      "scriptId":"u64"},
    "c7730264244c413c9beef3098397e606":{
      "scriptId":"u65"},
    "3b3cefab8c20431e9e1a30db6a9a5155":{
      "scriptId":"u66"},
    "a671a47bdffd42f0abcb5f79348bcc19":{
      "scriptId":"u67"},
    "db07847f1f744fc88e9c904675c09973":{
      "scriptId":"u68"},
    "bec994d07b534033ae96bec056c85efa":{
      "scriptId":"u69"},
    "86efdec040b84a6da2de12a2a929b6ee":{
      "scriptId":"u70"},
    "ccc4bc2d67be4c5ca392ce24b1d3a98c":{
      "scriptId":"u71"},
    "ab60130094074eaaaa88fd458f30f5a7":{
      "scriptId":"u72"},
    "837eaf102b2a4fd28ef10c0f3a69c85a":{
      "scriptId":"u73"}}});