$axure.loadCurrentPage({
  "url":"reports.html",
  "generationDate":new Date(1470822513082.97),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ebd96bd2963247e49268099b273229bf",
    "type":"Axure:Page",
    "name":"Reports",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"52061efb53794b9e932e51f128efd672",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"94f8821b4bd94788b5cc436b44ff4f3d"},
{
          "id":"b32a9909592c4edb996fbf3793e35492",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":89},
            "size":{
              "width":783,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/users/u20_line.png"}},
{
          "id":"0c220710eed345aea8d022bb806067a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Narrow Bold', 'Arial'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF8445AD,
              "opacity":1},
            "location":{
              "x":239,
              "y":65},
            "size":{
              "width":62,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74272f89edc94bcb96d84b4f7d28aa89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Narrow Bold', 'Arial'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF8445AD,
                  "opacity":1},
                "location":{
                  "x":239,
                  "y":65},
                "size":{
                  "width":62,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c92fdd72bb094474bfd40589a0464cda",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":112},
            "size":{
              "width":785,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/reports/u23_line.png"}},
{
          "id":"1c17d3988a324b55b72d2a5ce864139f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":252,
              "y":600},
            "size":{
              "width":74,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19a57c2f342143b191b372fe7698c7c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":252,
                  "y":600},
                "size":{
                  "width":74,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69df2651b7e147d0a96700f6a430063a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF575757},
            "location":{
              "x":21,
              "y":102},
            "size":{
              "width":200,
              "height":111},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d1dd5774dfa4a629b6ab1f81f0a1fea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF575757},
                "location":{
                  "x":21,
                  "y":102},
                "size":{
                  "width":200,
                  "height":111},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u61.png"}},
{
          "id":"6085c7dc5db6417487228cf9e6245fba",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":92,
              "y":113},
            "size":{
              "width":50,
              "height":50},
            "outerShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":188,
                "g":188,
                "b":188,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e8cfa4459ed43cdadca368e52a472ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":92,
                  "y":113},
                "size":{
                  "width":50,
                  "height":50},
                "outerShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":188,
                    "g":188,
                    "b":188,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u51.png"}},
{
          "id":"f148fdec647146e5a8b1434402ff5fae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF575757},
            "location":{
              "x":21,
              "y":173},
            "size":{
              "width":199,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"254833ec242b47d2bd7c0fd8c50453c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF575757},
                "location":{
                  "x":21,
                  "y":173},
                "size":{
                  "width":199,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/news_updates/u207.png"}},
{
          "id":"debdc93e365944cda4541a2d120c75e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF575757},
            "location":{
              "x":20,
              "y":212},
            "size":{
              "width":200,
              "height":111},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54b3184d51f749339f70d7b3e85824d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF575757},
                "location":{
                  "x":20,
                  "y":212},
                "size":{
                  "width":200,
                  "height":111},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u61.png"}},
{
          "id":"e8a9cc19dd684705a1179dad6d467795",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":91,
              "y":223},
            "size":{
              "width":48,
              "height":48},
            "outerShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":188,
                "g":188,
                "b":188,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ce9c3bb981c4d619470091b67e08a2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":91,
                  "y":223},
                "size":{
                  "width":48,
                  "height":48},
                "outerShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":188,
                    "g":188,
                    "b":188,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u57.png"}},
{
          "id":"8e88b94586d04bb49752d2bd49a1fb2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF575757},
            "location":{
              "x":20,
              "y":283},
            "size":{
              "width":200,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4f782d97af44ad0af714893e00a437b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF575757},
                "location":{
                  "x":20,
                  "y":283},
                "size":{
                  "width":200,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/projects/u211.png"}},
{
          "id":"c0a5a92732094d56a66e155053073c74",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF575757},
            "location":{
              "x":20,
              "y":321},
            "size":{
              "width":200,
              "height":111},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13975b08c3fa406fa14c79e6403b68e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF575757},
                "location":{
                  "x":20,
                  "y":321},
                "size":{
                  "width":200,
                  "height":111},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u61.png"}},
{
          "id":"e3ff8e01f2764bd0b2b11191871fef18",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":91,
              "y":332},
            "size":{
              "width":48,
              "height":48},
            "outerShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":188,
                "g":188,
                "b":188,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab15ee41afab4c088c1cc8307a7d5d6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":91,
                  "y":332},
                "size":{
                  "width":48,
                  "height":48},
                "outerShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":188,
                    "g":188,
                    "b":188,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u63.png"}},
{
          "id":"13fd0f03fb4d4b80afd2aeba056f3979",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF575757},
            "location":{
              "x":40,
              "y":392},
            "size":{
              "width":160,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bba56520cb84e60b2c2242dfd0c566a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF575757},
                "location":{
                  "x":40,
                  "y":392},
                "size":{
                  "width":160,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u65.png"}},
{
          "id":"8f76479ca8b74e5090b6e9a4d1939480",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF575757},
            "location":{
              "x":20,
              "y":432},
            "size":{
              "width":200,
              "height":111},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bf742a871e64fcf9401229742478cad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF575757},
                "location":{
                  "x":20,
                  "y":432},
                "size":{
                  "width":200,
                  "height":111},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u61.png"}},
{
          "id":"1eaf53bb05c14edc87ff5a12f2149749",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":91,
              "y":443},
            "size":{
              "width":48,
              "height":48},
            "outerShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":188,
                "g":188,
                "b":188,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16efb9273c374881b7e0054b09485876",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":91,
                  "y":443},
                "size":{
                  "width":48,
                  "height":48},
                "outerShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":188,
                    "g":188,
                    "b":188,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u69.png"}},
{
          "id":"f203e49e05cb45afa79e094fa15deb0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF575757},
            "location":{
              "x":40,
              "y":503},
            "size":{
              "width":160,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81dfd37054bc4e88b424f2536018f8f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF575757},
                "location":{
                  "x":40,
                  "y":503},
                "size":{
                  "width":160,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u65.png"}},
{
          "id":"d3cc2d72fbe348668f91566c2d574d5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":20,
              "y":543},
            "size":{
              "width":200,
              "height":111},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a6f0c4b35ec416cb310e10e708571b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":20,
                  "y":543},
                "size":{
                  "width":200,
                  "height":111},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/news_updates/u209.png"}},
{
          "id":"4fbb1d7f44654ff88142cffd5b6a355e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":91,
              "y":554},
            "size":{
              "width":48,
              "height":48},
            "outerShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":188,
                "g":188,
                "b":188,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16330ef182264eba8b818bd0c3add3fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":91,
                  "y":554},
                "size":{
                  "width":48,
                  "height":48},
                "outerShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":188,
                    "g":188,
                    "b":188,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u75.png"}},
{
          "id":"6a629938410a4d77a8f00242ccbbe71d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":40,
              "y":614},
            "size":{
              "width":160,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcdd8745cbdb47fa9454b5b249b14e02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":40,
                  "y":614},
                "size":{
                  "width":160,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/projects/u223.png"}},
{
          "id":"49a6e3164c4d42aa96e2b47a8b40c9e3",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":20,
              "y":212},
            "size":{
              "width":200,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cfb722b7518410dad7fa203cf9b0360",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":20,
                  "y":212},
                "size":{
                  "width":200,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News Updates in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news_updates.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u81.png"}},
{
          "id":"b9451b04bcef4510a80a469a70e1b87f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":21,
              "y":102},
            "size":{
              "width":200,
              "height":111}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"413b13ea8e214f368d522c3431efdaeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":21,
                  "y":102},
                "size":{
                  "width":200,
                  "height":111}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Dashboard in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"dashboard.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u79.png"}},
{
          "id":"e752df187e8d46b488edb67fd8dd89a7",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":20,
              "y":321},
            "size":{
              "width":200,
              "height":111}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf587de59fe0486483b82716199453bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":20,
                  "y":321},
                "size":{
                  "width":200,
                  "height":111}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Users in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"users.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u79.png"}},
{
          "id":"fffcb59dbf9241f4980933e7e88a82af",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":20,
              "y":430},
            "size":{
              "width":200,
              "height":112}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a8e8d36d79d4c7285cba77d8a02862b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":20,
                  "y":430},
                "size":{
                  "width":200,
                  "height":112}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Projects in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"projects.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u85.png"}},
{
          "id":"85b43d3b67c547b39843c698685d7055",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":20,
              "y":545},
            "size":{
              "width":200,
              "height":109}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c49e26d0f8344db4be88165547738593",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":20,
                  "y":545},
                "size":{
                  "width":200,
                  "height":109}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Reports in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"reports.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u87.png"}},
{
          "id":"f62c46e81ebe40088b3f97625afe7195",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":249,
              "y":142},
            "size":{
              "width":371,
              "height":229},
            "outerShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":188,
                "g":188,
                "b":188,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb60076b2b0641a695933286213f6f48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":249,
                  "y":142},
                "size":{
                  "width":371,
                  "height":229},
                "outerShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":188,
                    "g":188,
                    "b":188,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/reports/u66.png"}},
{
          "id":"78080abc8e414da8ac27bd6700ed413d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":630,
              "y":142},
            "size":{
              "width":384,
              "height":248},
            "outerShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":188,
                "g":188,
                "b":188,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"990c06c9c72448c39c62089bdb375c26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":630,
                  "y":142},
                "size":{
                  "width":384,
                  "height":248},
                "outerShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":188,
                    "g":188,
                    "b":188,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/reports/u68.png"}},
{
          "id":"15666a956c3f4231b6aafc93adb38f6e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":249,
              "y":440},
            "size":{
              "width":765,
              "height":240},
            "outerShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":188,
                "g":188,
                "b":188,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89a035f22f07494bbbe2a026372105a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":249,
                  "y":440},
                "size":{
                  "width":765,
                  "height":240},
                "outerShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":188,
                    "g":188,
                    "b":188,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/reports/u70.jpg"}}]}},
  "masters":{
    "94f8821b4bd94788b5cc436b44ff4f3d":{
      "packageId":"94f8821b4bd94788b5cc436b44ff4f3d",
      "type":"Axure:Master",
      "name":"New Master 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"28c93813b38647b2b164b9e09177eac9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":-16,
                "y":0},
              "size":{
                "width":1016,
                "height":690},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"830357c732864407b8522edb2a2455e1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-16,
                    "y":0},
                  "size":{
                    "width":1016,
                    "height":690},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u1.png"}},
{
            "id":"e44fbd401aa944089e8e5f16df78b550",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF8445AD},
              "location":{
                "x":-20,
                "y":0},
              "size":{
                "width":1020,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"77653441843842838d0546cc0127d6ab",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF8445AD},
                  "location":{
                    "x":-20,
                    "y":0},
                  "size":{
                    "width":1020,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u3.png"}},
{
            "id":"2c8a0a156bf74f39bd7b6e6bb160c340",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "location":{
                "x":0,
                "y":49},
              "size":{
                "width":200,
                "height":641},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"55184db0186d44d78b3949cf87e643e6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "location":{
                    "x":0,
                    "y":49},
                  "size":{
                    "width":200,
                    "height":641},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u5.png"}},
{
            "id":"30e5a7d9c7884c9e9af62f7b275f076f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF8445AD},
              "location":{
                "x":900,
                "y":10},
              "size":{
                "width":34,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6d25e5cf503240a2a22955705ea1c013",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF8445AD},
                  "location":{
                    "x":900,
                    "y":10},
                  "size":{
                    "width":34,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u7.png"}},
{
            "id":"afa8bbeccb2c416fb00309d5a0a39de9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":689},
              "size":{
                "width":984,
                "height":25},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"14b04da03a5344ff9ba4f051e36d31b6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":689},
                  "size":{
                    "width":984,
                    "height":25},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u9.png"}},
{
            "id":"02804bed18a648f0ba7708384dd6f9ad",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Arial Bold', 'Arial'",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "size":{
                "width":200,
                "height":100},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF515151},
              "outerShadow":{
                "on":false,
                "offsetX":5,
                "offsetY":5,
                "blurRadius":5,
                "color":{
                  "r":188,
                  "g":188,
                  "b":188,
                  "a":0.349019607843137}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aae9e40428ce49a6b231d8b73bd2aa44",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Bold', 'Arial'",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "size":{
                    "width":200,
                    "height":100},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF515151},
                  "outerShadow":{
                    "on":false,
                    "offsetX":5,
                    "offsetY":5,
                    "blurRadius":5,
                    "color":{
                      "r":188,
                      "g":188,
                      "b":188,
                      "a":0.349019607843137}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u11.png"}},
{
            "id":"bb94e6fc3bdd45648536ad9dae6c04fd",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Bold', 'Arial'",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF8445AD},
              "location":{
                "x":810,
                "y":10},
              "size":{
                "width":90,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"86f0d4376e2a4cf78f38b7afe2e66693",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Bold', 'Arial'",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF8445AD},
                  "location":{
                    "x":810,
                    "y":10},
                  "size":{
                    "width":90,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u13.png"}},
{
            "id":"6d19e2165f484f2f91547387aaa4c0aa",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":90},
              "size":{
                "width":800,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4CAF50}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/dashboard/u15_line.png"}},
{
            "id":"3093340320e34795834ea6f26df495f3",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":34,
                "y":2},
              "size":{
                "width":88,
                "height":88}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5189ab40624d4ac8992e435c4f58808f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":34,
                    "y":2},
                  "size":{
                    "width":88,
                    "height":88}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/splash/u4.png"}},
{
            "id":"58ad05f8ab22426e89b347681bce1d5f",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":194,
                "y":-3},
              "size":{
                "width":10,
                "height":693},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF333333}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/dashboard/u18_line.png"}},
{
            "id":"94e358730f06438a80b018d9f03beda4",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":-5,
                "y":-3},
              "size":{
                "width":10,
                "height":693},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF333333}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/dashboard/u18_line.png"}}]}}},
  "objectPaths":{
    "52061efb53794b9e932e51f128efd672":{
      "scriptId":"u0",
      "28c93813b38647b2b164b9e09177eac9":{
        "scriptId":"u1"},
      "830357c732864407b8522edb2a2455e1":{
        "scriptId":"u2"},
      "e44fbd401aa944089e8e5f16df78b550":{
        "scriptId":"u3"},
      "77653441843842838d0546cc0127d6ab":{
        "scriptId":"u4"},
      "2c8a0a156bf74f39bd7b6e6bb160c340":{
        "scriptId":"u5"},
      "55184db0186d44d78b3949cf87e643e6":{
        "scriptId":"u6"},
      "30e5a7d9c7884c9e9af62f7b275f076f":{
        "scriptId":"u7"},
      "6d25e5cf503240a2a22955705ea1c013":{
        "scriptId":"u8"},
      "afa8bbeccb2c416fb00309d5a0a39de9":{
        "scriptId":"u9"},
      "14b04da03a5344ff9ba4f051e36d31b6":{
        "scriptId":"u10"},
      "02804bed18a648f0ba7708384dd6f9ad":{
        "scriptId":"u11"},
      "aae9e40428ce49a6b231d8b73bd2aa44":{
        "scriptId":"u12"},
      "bb94e6fc3bdd45648536ad9dae6c04fd":{
        "scriptId":"u13"},
      "86f0d4376e2a4cf78f38b7afe2e66693":{
        "scriptId":"u14"},
      "6d19e2165f484f2f91547387aaa4c0aa":{
        "scriptId":"u15"},
      "3093340320e34795834ea6f26df495f3":{
        "scriptId":"u16"},
      "5189ab40624d4ac8992e435c4f58808f":{
        "scriptId":"u17"},
      "58ad05f8ab22426e89b347681bce1d5f":{
        "scriptId":"u18"},
      "94e358730f06438a80b018d9f03beda4":{
        "scriptId":"u19"}},
    "b32a9909592c4edb996fbf3793e35492":{
      "scriptId":"u20"},
    "0c220710eed345aea8d022bb806067a9":{
      "scriptId":"u21"},
    "74272f89edc94bcb96d84b4f7d28aa89":{
      "scriptId":"u22"},
    "c92fdd72bb094474bfd40589a0464cda":{
      "scriptId":"u23"},
    "1c17d3988a324b55b72d2a5ce864139f":{
      "scriptId":"u24"},
    "19a57c2f342143b191b372fe7698c7c5":{
      "scriptId":"u25"},
    "69df2651b7e147d0a96700f6a430063a":{
      "scriptId":"u26"},
    "9d1dd5774dfa4a629b6ab1f81f0a1fea":{
      "scriptId":"u27"},
    "6085c7dc5db6417487228cf9e6245fba":{
      "scriptId":"u28"},
    "6e8cfa4459ed43cdadca368e52a472ee":{
      "scriptId":"u29"},
    "f148fdec647146e5a8b1434402ff5fae":{
      "scriptId":"u30"},
    "254833ec242b47d2bd7c0fd8c50453c4":{
      "scriptId":"u31"},
    "debdc93e365944cda4541a2d120c75e5":{
      "scriptId":"u32"},
    "54b3184d51f749339f70d7b3e85824d4":{
      "scriptId":"u33"},
    "e8a9cc19dd684705a1179dad6d467795":{
      "scriptId":"u34"},
    "6ce9c3bb981c4d619470091b67e08a2c":{
      "scriptId":"u35"},
    "8e88b94586d04bb49752d2bd49a1fb2d":{
      "scriptId":"u36"},
    "f4f782d97af44ad0af714893e00a437b":{
      "scriptId":"u37"},
    "c0a5a92732094d56a66e155053073c74":{
      "scriptId":"u38"},
    "13975b08c3fa406fa14c79e6403b68e2":{
      "scriptId":"u39"},
    "e3ff8e01f2764bd0b2b11191871fef18":{
      "scriptId":"u40"},
    "ab15ee41afab4c088c1cc8307a7d5d6e":{
      "scriptId":"u41"},
    "13fd0f03fb4d4b80afd2aeba056f3979":{
      "scriptId":"u42"},
    "3bba56520cb84e60b2c2242dfd0c566a":{
      "scriptId":"u43"},
    "8f76479ca8b74e5090b6e9a4d1939480":{
      "scriptId":"u44"},
    "0bf742a871e64fcf9401229742478cad":{
      "scriptId":"u45"},
    "1eaf53bb05c14edc87ff5a12f2149749":{
      "scriptId":"u46"},
    "16efb9273c374881b7e0054b09485876":{
      "scriptId":"u47"},
    "f203e49e05cb45afa79e094fa15deb0f":{
      "scriptId":"u48"},
    "81dfd37054bc4e88b424f2536018f8f5":{
      "scriptId":"u49"},
    "d3cc2d72fbe348668f91566c2d574d5a":{
      "scriptId":"u50"},
    "4a6f0c4b35ec416cb310e10e708571b2":{
      "scriptId":"u51"},
    "4fbb1d7f44654ff88142cffd5b6a355e":{
      "scriptId":"u52"},
    "16330ef182264eba8b818bd0c3add3fe":{
      "scriptId":"u53"},
    "6a629938410a4d77a8f00242ccbbe71d":{
      "scriptId":"u54"},
    "bcdd8745cbdb47fa9454b5b249b14e02":{
      "scriptId":"u55"},
    "49a6e3164c4d42aa96e2b47a8b40c9e3":{
      "scriptId":"u56"},
    "8cfb722b7518410dad7fa203cf9b0360":{
      "scriptId":"u57"},
    "b9451b04bcef4510a80a469a70e1b87f":{
      "scriptId":"u58"},
    "413b13ea8e214f368d522c3431efdaeb":{
      "scriptId":"u59"},
    "e752df187e8d46b488edb67fd8dd89a7":{
      "scriptId":"u60"},
    "cf587de59fe0486483b82716199453bb":{
      "scriptId":"u61"},
    "fffcb59dbf9241f4980933e7e88a82af":{
      "scriptId":"u62"},
    "5a8e8d36d79d4c7285cba77d8a02862b":{
      "scriptId":"u63"},
    "85b43d3b67c547b39843c698685d7055":{
      "scriptId":"u64"},
    "c49e26d0f8344db4be88165547738593":{
      "scriptId":"u65"},
    "f62c46e81ebe40088b3f97625afe7195":{
      "scriptId":"u66"},
    "fb60076b2b0641a695933286213f6f48":{
      "scriptId":"u67"},
    "78080abc8e414da8ac27bd6700ed413d":{
      "scriptId":"u68"},
    "990c06c9c72448c39c62089bdb375c26":{
      "scriptId":"u69"},
    "15666a956c3f4231b6aafc93adb38f6e":{
      "scriptId":"u70"},
    "89a035f22f07494bbbe2a026372105a6":{
      "scriptId":"u71"}}});