$axure.loadCurrentPage({
  "url":"news_updates_-__details.html",
  "generationDate":new Date(1470822513637),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"27541ca7c96647d387ff445c42758f9a",
    "type":"Axure:Page",
    "name":"News Updates -  Details",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"52061efb53794b9e932e51f128efd672",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"94f8821b4bd94788b5cc436b44ff4f3d"},
{
          "id":"0c220710eed345aea8d022bb806067a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Narrow Bold', 'Arial'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF8445AD,
              "opacity":1},
            "location":{
              "x":239,
              "y":65},
            "size":{
              "width":113,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74272f89edc94bcb96d84b4f7d28aa89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Narrow Bold', 'Arial'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF8445AD,
                  "opacity":1},
                "location":{
                  "x":239,
                  "y":65},
                "size":{
                  "width":113,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5e82f41be734f5ea67b87edcfb3226c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF575757},
            "location":{
              "x":21,
              "y":102},
            "size":{
              "width":200,
              "height":111},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2849701df96744ebafe7d50ae74b9981",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF575757},
                "location":{
                  "x":21,
                  "y":102},
                "size":{
                  "width":200,
                  "height":111},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u61.png"}},
{
          "id":"df374b4d016a4cd3b66e3ca0a0d5706c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":92,
              "y":113},
            "size":{
              "width":50,
              "height":50},
            "outerShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":188,
                "g":188,
                "b":188,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e8306b571ca463e9271c2230cd2abd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":92,
                  "y":113},
                "size":{
                  "width":50,
                  "height":50},
                "outerShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":188,
                    "g":188,
                    "b":188,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u51.png"}},
{
          "id":"008cb3c2ce2749eb825795ef52e11a24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF575757},
            "location":{
              "x":21,
              "y":173},
            "size":{
              "width":199,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8851d1bbbfff4a22b27296073966aa0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF575757},
                "location":{
                  "x":21,
                  "y":173},
                "size":{
                  "width":199,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/news_updates/u207.png"}},
{
          "id":"162ee1c68fa94a64a6659039fe6f5e67",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":20,
              "y":212},
            "size":{
              "width":200,
              "height":111},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07b1b48c0a00430ba49ab28f1f770405",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":20,
                  "y":212},
                "size":{
                  "width":200,
                  "height":111},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/news_updates/u209.png"}},
{
          "id":"a9516ec5b35a493aad919f70898d3ff4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":91,
              "y":223},
            "size":{
              "width":48,
              "height":48},
            "outerShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":188,
                "g":188,
                "b":188,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8da3d604e4b4458a692b83fb0bd4058",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":91,
                  "y":223},
                "size":{
                  "width":48,
                  "height":48},
                "outerShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":188,
                    "g":188,
                    "b":188,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u57.png"}},
{
          "id":"1196d909d3e046ae8bd24662988eaa5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":20,
              "y":283},
            "size":{
              "width":200,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd5c40852f3947aea7d2e52e814a61e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":20,
                  "y":283},
                "size":{
                  "width":200,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/news_updates/u213.png"}},
{
          "id":"70ba9c90a20847da9dd4033c855ea8d6",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":21,
              "y":103},
            "size":{
              "width":200,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"512f5f376a4e471abfe01d8c3be8c705",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":21,
                  "y":103},
                "size":{
                  "width":200,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Dashboard in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"dashboard_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u81.png"}},
{
          "id":"f44064734ee94488aa0e7c8ed8a7345d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":20,
              "y":212},
            "size":{
              "width":200,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bc2a247a1774a698928bc391c0e4c38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":20,
                  "y":212},
                "size":{
                  "width":200,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News Updates -&nbsp; Details in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news_updates_-__details.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u81.png"}},
{
          "id":"eab161a988694ab5897e8d67ad2586ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4CAF50,
              "opacity":1},
            "location":{
              "x":240,
              "y":119},
            "size":{
              "width":750,
              "height":531},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b94832ab1eb44809b1d7e255c74c980",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4CAF50,
                  "opacity":1},
                "location":{
                  "x":240,
                  "y":119},
                "size":{
                  "width":750,
                  "height":531},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/news_updates_-__details/u38.png"}},
{
          "id":"6541a4792da14f56a375147b9bce4ab1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":500},
            "size":{
              "width":750,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/news_updates_-__details/u40_line.png"}},
{
          "id":"dc92dbec0eb341d0be9d9f5b57921026",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":566},
            "size":{
              "width":96,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4c1cf453fd647f58a07d17aef3b0e00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":261,
                  "y":566},
                "size":{
                  "width":96,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9430ed1982b4a338ad9716edbb5cfdc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2E2925,
              "opacity":1},
            "location":{
              "x":256,
              "y":130},
            "size":{
              "width":101,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90924346817143b3b25ce0c8381c5d33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2E2925,
                  "opacity":1},
                "location":{
                  "x":256,
                  "y":130},
                "size":{
                  "width":101,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4abf68e4621a421cbf335166daeba28d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":260,
              "y":172},
            "size":{
              "width":705,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fabdd1a769084339b3e4545c09ec3387",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":260,
                  "y":172},
                "size":{
                  "width":705,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce24f08f41b84dafbd1740d30b9f6d1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF8445AD},
            "location":{
              "x":860,
              "y":562},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"882b0f1baded4d32b094e964b91c457b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8445AD},
                "location":{
                  "x":860,
                  "y":562},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News Updates in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news_updates_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/news_updates_-__details/u47.png"}}]}},
  "masters":{
    "94f8821b4bd94788b5cc436b44ff4f3d":{
      "packageId":"94f8821b4bd94788b5cc436b44ff4f3d",
      "type":"Axure:Master",
      "name":"New Master 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"28c93813b38647b2b164b9e09177eac9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":-16,
                "y":0},
              "size":{
                "width":1016,
                "height":690},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"830357c732864407b8522edb2a2455e1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-16,
                    "y":0},
                  "size":{
                    "width":1016,
                    "height":690},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u1.png"}},
{
            "id":"e44fbd401aa944089e8e5f16df78b550",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF8445AD},
              "location":{
                "x":-20,
                "y":0},
              "size":{
                "width":1020,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"77653441843842838d0546cc0127d6ab",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF8445AD},
                  "location":{
                    "x":-20,
                    "y":0},
                  "size":{
                    "width":1020,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u3.png"}},
{
            "id":"2c8a0a156bf74f39bd7b6e6bb160c340",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "location":{
                "x":0,
                "y":49},
              "size":{
                "width":200,
                "height":641},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"55184db0186d44d78b3949cf87e643e6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "location":{
                    "x":0,
                    "y":49},
                  "size":{
                    "width":200,
                    "height":641},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u5.png"}},
{
            "id":"30e5a7d9c7884c9e9af62f7b275f076f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF8445AD},
              "location":{
                "x":900,
                "y":10},
              "size":{
                "width":34,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6d25e5cf503240a2a22955705ea1c013",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF8445AD},
                  "location":{
                    "x":900,
                    "y":10},
                  "size":{
                    "width":34,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u7.png"}},
{
            "id":"afa8bbeccb2c416fb00309d5a0a39de9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":689},
              "size":{
                "width":984,
                "height":25},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"14b04da03a5344ff9ba4f051e36d31b6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":689},
                  "size":{
                    "width":984,
                    "height":25},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u9.png"}},
{
            "id":"02804bed18a648f0ba7708384dd6f9ad",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Arial Bold', 'Arial'",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "size":{
                "width":200,
                "height":100},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF515151},
              "outerShadow":{
                "on":false,
                "offsetX":5,
                "offsetY":5,
                "blurRadius":5,
                "color":{
                  "r":188,
                  "g":188,
                  "b":188,
                  "a":0.349019607843137}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aae9e40428ce49a6b231d8b73bd2aa44",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Bold', 'Arial'",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "size":{
                    "width":200,
                    "height":100},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF515151},
                  "outerShadow":{
                    "on":false,
                    "offsetX":5,
                    "offsetY":5,
                    "blurRadius":5,
                    "color":{
                      "r":188,
                      "g":188,
                      "b":188,
                      "a":0.349019607843137}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u11.png"}},
{
            "id":"bb94e6fc3bdd45648536ad9dae6c04fd",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Bold', 'Arial'",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF8445AD},
              "location":{
                "x":810,
                "y":10},
              "size":{
                "width":90,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"86f0d4376e2a4cf78f38b7afe2e66693",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Bold', 'Arial'",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF8445AD},
                  "location":{
                    "x":810,
                    "y":10},
                  "size":{
                    "width":90,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u13.png"}},
{
            "id":"6d19e2165f484f2f91547387aaa4c0aa",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":90},
              "size":{
                "width":800,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4CAF50}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/dashboard/u15_line.png"}},
{
            "id":"3093340320e34795834ea6f26df495f3",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":34,
                "y":2},
              "size":{
                "width":88,
                "height":88}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5189ab40624d4ac8992e435c4f58808f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":34,
                    "y":2},
                  "size":{
                    "width":88,
                    "height":88}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/splash/u4.png"}},
{
            "id":"58ad05f8ab22426e89b347681bce1d5f",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":194,
                "y":-3},
              "size":{
                "width":10,
                "height":693},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF333333}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/dashboard/u18_line.png"}},
{
            "id":"94e358730f06438a80b018d9f03beda4",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":-5,
                "y":-3},
              "size":{
                "width":10,
                "height":693},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF333333}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/dashboard/u18_line.png"}}]}}},
  "objectPaths":{
    "52061efb53794b9e932e51f128efd672":{
      "scriptId":"u0",
      "28c93813b38647b2b164b9e09177eac9":{
        "scriptId":"u1"},
      "830357c732864407b8522edb2a2455e1":{
        "scriptId":"u2"},
      "e44fbd401aa944089e8e5f16df78b550":{
        "scriptId":"u3"},
      "77653441843842838d0546cc0127d6ab":{
        "scriptId":"u4"},
      "2c8a0a156bf74f39bd7b6e6bb160c340":{
        "scriptId":"u5"},
      "55184db0186d44d78b3949cf87e643e6":{
        "scriptId":"u6"},
      "30e5a7d9c7884c9e9af62f7b275f076f":{
        "scriptId":"u7"},
      "6d25e5cf503240a2a22955705ea1c013":{
        "scriptId":"u8"},
      "afa8bbeccb2c416fb00309d5a0a39de9":{
        "scriptId":"u9"},
      "14b04da03a5344ff9ba4f051e36d31b6":{
        "scriptId":"u10"},
      "02804bed18a648f0ba7708384dd6f9ad":{
        "scriptId":"u11"},
      "aae9e40428ce49a6b231d8b73bd2aa44":{
        "scriptId":"u12"},
      "bb94e6fc3bdd45648536ad9dae6c04fd":{
        "scriptId":"u13"},
      "86f0d4376e2a4cf78f38b7afe2e66693":{
        "scriptId":"u14"},
      "6d19e2165f484f2f91547387aaa4c0aa":{
        "scriptId":"u15"},
      "3093340320e34795834ea6f26df495f3":{
        "scriptId":"u16"},
      "5189ab40624d4ac8992e435c4f58808f":{
        "scriptId":"u17"},
      "58ad05f8ab22426e89b347681bce1d5f":{
        "scriptId":"u18"},
      "94e358730f06438a80b018d9f03beda4":{
        "scriptId":"u19"}},
    "0c220710eed345aea8d022bb806067a9":{
      "scriptId":"u20"},
    "74272f89edc94bcb96d84b4f7d28aa89":{
      "scriptId":"u21"},
    "a5e82f41be734f5ea67b87edcfb3226c":{
      "scriptId":"u22"},
    "2849701df96744ebafe7d50ae74b9981":{
      "scriptId":"u23"},
    "df374b4d016a4cd3b66e3ca0a0d5706c":{
      "scriptId":"u24"},
    "2e8306b571ca463e9271c2230cd2abd3":{
      "scriptId":"u25"},
    "008cb3c2ce2749eb825795ef52e11a24":{
      "scriptId":"u26"},
    "8851d1bbbfff4a22b27296073966aa0a":{
      "scriptId":"u27"},
    "162ee1c68fa94a64a6659039fe6f5e67":{
      "scriptId":"u28"},
    "07b1b48c0a00430ba49ab28f1f770405":{
      "scriptId":"u29"},
    "a9516ec5b35a493aad919f70898d3ff4":{
      "scriptId":"u30"},
    "f8da3d604e4b4458a692b83fb0bd4058":{
      "scriptId":"u31"},
    "1196d909d3e046ae8bd24662988eaa5e":{
      "scriptId":"u32"},
    "fd5c40852f3947aea7d2e52e814a61e5":{
      "scriptId":"u33"},
    "70ba9c90a20847da9dd4033c855ea8d6":{
      "scriptId":"u34"},
    "512f5f376a4e471abfe01d8c3be8c705":{
      "scriptId":"u35"},
    "f44064734ee94488aa0e7c8ed8a7345d":{
      "scriptId":"u36"},
    "8bc2a247a1774a698928bc391c0e4c38":{
      "scriptId":"u37"},
    "eab161a988694ab5897e8d67ad2586ca":{
      "scriptId":"u38"},
    "2b94832ab1eb44809b1d7e255c74c980":{
      "scriptId":"u39"},
    "6541a4792da14f56a375147b9bce4ab1":{
      "scriptId":"u40"},
    "dc92dbec0eb341d0be9d9f5b57921026":{
      "scriptId":"u41"},
    "d4c1cf453fd647f58a07d17aef3b0e00":{
      "scriptId":"u42"},
    "f9430ed1982b4a338ad9716edbb5cfdc":{
      "scriptId":"u43"},
    "90924346817143b3b25ce0c8381c5d33":{
      "scriptId":"u44"},
    "4abf68e4621a421cbf335166daeba28d":{
      "scriptId":"u45"},
    "fabdd1a769084339b3e4545c09ec3387":{
      "scriptId":"u46"},
    "ce24f08f41b84dafbd1740d30b9f6d1a":{
      "scriptId":"u47"},
    "882b0f1baded4d32b094e964b91c457b":{
      "scriptId":"u48"}}});