$axure.loadCurrentPage({
  "url":"dashboard.html",
  "generationDate":new Date(1470822511501.17),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f4795b63ae274b44980c3ec92e83371c",
    "type":"Axure:Page",
    "name":"Dashboard",
    "notes":{
      "Note":"<p><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">Top Level Navigation links</span></p><p><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">Default&nbsp; Navigation Link </span></p><p><span>Background color: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">None</span><span>&nbsp;</span></p><p><span>Border Color: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">None</span></p><p><span>Font size: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">13</span></p><p><span>Font Color: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">#</span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">363636</span><span>&nbsp;</span></p><p><span>&nbsp;</span></p><p><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">ActiveTop Navigation link</span></p><p><span>Background color: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">None</span><span>&nbsp;</span></p><p><span>Border Color: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">None</span></p><p><span>Font size: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">13</span></p><p><span>Font Color: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">#1DB0E5</span></p><p><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">&nbsp;</span></p><p><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">Second level Top Navigation</span></p><p><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">Active Tab</span></p><p><span>Background color: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">1DB0E5</span></p><p><span>Border Color: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">#CCCCCC</span></p><p><span>Font size: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">13</span></p><p><span>Font Color: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">#FFFFFF</span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\"></span><span>&nbsp;</span></p><p><span>&nbsp;</span></p><p><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">Inactive Tab</span></p><p><span>Background color: #</span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">FFFFFF</span></p><p><span>Border Color: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">#CCCCCC</span></p><p><span>Font size: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">13</span></p><p><span>Font Color: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">#363636</span><span>&nbsp;</span></p><p><span>&nbsp;</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"52061efb53794b9e932e51f128efd672",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"94f8821b4bd94788b5cc436b44ff4f3d"},
{
          "id":"75190f5b0e9743efa0fbe4712ae44b21",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF363636},
            "location":{
              "x":21,
              "y":102},
            "size":{
              "width":200,
              "height":111},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77392aa4176c4788baecd394fe7c7d81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF363636},
                "location":{
                  "x":21,
                  "y":102},
                "size":{
                  "width":200,
                  "height":111},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u20.png"}},
{
          "id":"b32a9909592c4edb996fbf3793e35492",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":89},
            "size":{
              "width":779,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/dashboard/u22_line.png"}},
{
          "id":"fa3e19e6c67d48c3b2e608c290618fc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5E5E5E,
              "opacity":1},
            "location":{
              "x":250,
              "y":65},
            "size":{
              "width":89,
              "height":24},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c54f4da0ec9f4a72a36d4fa1fa1f4f02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF5E5E5E,
                  "opacity":1},
                "location":{
                  "x":250,
                  "y":65},
                "size":{
                  "width":89,
                  "height":24},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"593b5ddb61014a768617cee367e41812",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":127},
            "size":{
              "width":233,
              "height":78},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4CAF50},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfa95dcb8c09410d8ba79839304e7ef4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":127},
                "size":{
                  "width":233,
                  "height":78},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4CAF50},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u25.png"}},
{
          "id":"ad0280d53d994e08b19ed260db2a78aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":250},
            "size":{
              "width":750,
              "height":380},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a49ea641b8f240a2a6206df1741cafa7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":250},
                "size":{
                  "width":750,
                  "height":380},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u27.png"}},
{
          "id":"f9dab4464e8d49a0bf88e1f6fe099b92",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "verticalAlignment":"middle",
            "location":{
              "x":344,
              "y":154},
            "size":{
              "width":88,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72ec7a1251564ed1a97fd561896da466",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "location":{
                  "x":344,
                  "y":154},
                "size":{
                  "width":88,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34f7b99e1ae54dbaa43b0e21ffbe2310",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF8445AD},
            "location":{
              "x":250,
              "y":127},
            "size":{
              "width":74,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb4408fb89b540cc9dea95aae30c5379",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8445AD},
                "location":{
                  "x":250,
                  "y":127},
                "size":{
                  "width":74,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u31.png"}},
{
          "id":"d4d143a64d3245eb8d27d4309b0ba020",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":267,
              "y":145},
            "size":{
              "width":41,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c8acff385f04c5e9d0b94dcb3129592",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":267,
                  "y":145},
                "size":{
                  "width":41,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b5201e288b445218b3a286ad7ba023c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":767,
              "y":127},
            "size":{
              "width":233,
              "height":78},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4CAF50},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"192c3832cbe14b28886d74fdcc66ec4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":767,
                  "y":127},
                "size":{
                  "width":233,
                  "height":78},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4CAF50},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u25.png"}},
{
          "id":"e58099c2149e4fe0ad6be181e767a4b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "verticalAlignment":"middle",
            "location":{
              "x":849,
              "y":157},
            "size":{
              "width":138,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ace7517953d84520ad4bef0ccffc69e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "location":{
                  "x":849,
                  "y":157},
                "size":{
                  "width":138,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"610b8db3b2eb4a1d91e1ab5e49258bdf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF8445AD},
            "location":{
              "x":767,
              "y":127},
            "size":{
              "width":74,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"226e1aee654645d9bc97fbde8528cf24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8445AD},
                "location":{
                  "x":767,
                  "y":127},
                "size":{
                  "width":74,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u31.png"}},
{
          "id":"203d0f95061c43ddae47add4ad733600",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":784,
              "y":145},
            "size":{
              "width":41,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"026ae92a30a94148b4f4d7c270615c86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":784,
                  "y":145},
                "size":{
                  "width":41,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6f90164107442d4802824d662eb9a98",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":508,
              "y":127},
            "size":{
              "width":233,
              "height":78},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4CAF50},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"494fc3c5b3fa47c083debeaa755b237e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":508,
                  "y":127},
                "size":{
                  "width":233,
                  "height":78},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4CAF50},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u25.png"}},
{
          "id":"4883d094b94948f59d05ba618bedc675",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "verticalAlignment":"middle",
            "location":{
              "x":584,
              "y":154},
            "size":{
              "width":154,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cff971a12784beb914a5325f4ee8c57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "location":{
                  "x":584,
                  "y":154},
                "size":{
                  "width":154,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1036179864fb4570934166c519603c75",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFF8445AD},
            "location":{
              "x":508,
              "y":127},
            "size":{
              "width":74,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bfc5fe523224ea4b1ac44e238d391c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8445AD},
                "location":{
                  "x":508,
                  "y":127},
                "size":{
                  "width":74,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u31.png"}},
{
          "id":"abfa0f5f00a844c291a0124876fbfe8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":526,
              "y":145},
            "size":{
              "width":41,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dbd61c2a97a48c8bf5a6ab1cddde30d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":526,
                  "y":145},
                "size":{
                  "width":41,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29abda3eb9f6493a9c784c611d869fd2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":92,
              "y":113},
            "size":{
              "width":50,
              "height":50},
            "outerShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":188,
                "g":188,
                "b":188,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"916c2b96c5a94dcba7a8e85130c335d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":92,
                  "y":113},
                "size":{
                  "width":50,
                  "height":50},
                "outerShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":188,
                    "g":188,
                    "b":188,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u51.png"}},
{
          "id":"34dc2dcb44b24137adf7c27516e35d0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF363636},
            "location":{
              "x":21,
              "y":173},
            "size":{
              "width":199,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de4d1ba5c1864d048d8d713c6dc52a18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF363636},
                "location":{
                  "x":21,
                  "y":173},
                "size":{
                  "width":199,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u53.png"}},
{
          "id":"0988c72b53904a5f9323985af70885ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xD35E5E5E},
            "location":{
              "x":20,
              "y":212},
            "size":{
              "width":200,
              "height":111},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdd43c447496414a9037cb032bfd1e22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xD35E5E5E},
                "location":{
                  "x":20,
                  "y":212},
                "size":{
                  "width":200,
                  "height":111},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u55.png"}},
{
          "id":"6a0f7a95cbe04ebbaa39634e259558ad",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":91,
              "y":223},
            "size":{
              "width":48,
              "height":48},
            "outerShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":188,
                "g":188,
                "b":188,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5eff6cac17fe4a87af7a2762f140ff39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":91,
                  "y":223},
                "size":{
                  "width":48,
                  "height":48},
                "outerShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":188,
                    "g":188,
                    "b":188,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u57.png"}},
{
          "id":"2ac8e1f8a6be4031a5101f8865cfd4b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xD35E5E5E},
            "location":{
              "x":20,
              "y":283},
            "size":{
              "width":200,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53ef8d81c9c945e28c787e06504adb1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xD35E5E5E},
                "location":{
                  "x":20,
                  "y":283},
                "size":{
                  "width":200,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u59.png"}},
{
          "id":"72e4bc8bdc3d4bc28180b67a06efe8f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF575757},
            "location":{
              "x":20,
              "y":321},
            "size":{
              "width":200,
              "height":111},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87319c80b06f41f5a347bde7dc0aab81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF575757},
                "location":{
                  "x":20,
                  "y":321},
                "size":{
                  "width":200,
                  "height":111},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u61.png"}},
{
          "id":"f579ecb75a964d9eb45cb2a0eccbe27b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":91,
              "y":332},
            "size":{
              "width":48,
              "height":48},
            "outerShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":188,
                "g":188,
                "b":188,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"017e10b158ed4851ad3eed575171caeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":91,
                  "y":332},
                "size":{
                  "width":48,
                  "height":48},
                "outerShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":188,
                    "g":188,
                    "b":188,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u63.png"}},
{
          "id":"72bfea42e2a44ad189737a8b95734738",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF575757},
            "location":{
              "x":40,
              "y":392},
            "size":{
              "width":160,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecd867a1de7840d490df637185e40156",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF575757},
                "location":{
                  "x":40,
                  "y":392},
                "size":{
                  "width":160,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u65.png"}},
{
          "id":"54407d2722d84df5b71a2b32a4cdfd71",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF575757},
            "location":{
              "x":20,
              "y":431},
            "size":{
              "width":200,
              "height":111},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa56017a71134273ac7ba77558cf89e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF575757},
                "location":{
                  "x":20,
                  "y":431},
                "size":{
                  "width":200,
                  "height":111},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u61.png"}},
{
          "id":"5ddf3ca74eb14cbdb690b8fd497150fc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":91,
              "y":442},
            "size":{
              "width":48,
              "height":48},
            "outerShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":188,
                "g":188,
                "b":188,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f2937d149d14e8a9baa299e6ea18fdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":91,
                  "y":442},
                "size":{
                  "width":48,
                  "height":48},
                "outerShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":188,
                    "g":188,
                    "b":188,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u69.png"}},
{
          "id":"57791c004ed34bb3aa2fec6926eaf8e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF575757},
            "location":{
              "x":40,
              "y":502},
            "size":{
              "width":160,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd9d58ad2c944c11a03356dd076d9ae4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF575757},
                "location":{
                  "x":40,
                  "y":502},
                "size":{
                  "width":160,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u65.png"}},
{
          "id":"b9833a6310a8493c962a4d6e0bb6e70e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF575757},
            "location":{
              "x":20,
              "y":543},
            "size":{
              "width":200,
              "height":111},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"126aba3ec4a5445baf768a53255929db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF575757},
                "location":{
                  "x":20,
                  "y":543},
                "size":{
                  "width":200,
                  "height":111},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u61.png"}},
{
          "id":"b31867946ee743e7a16493c2544c0d0f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":91,
              "y":554},
            "size":{
              "width":36,
              "height":36},
            "outerShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":188,
                "g":188,
                "b":188,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"708dfae1b7144c989841034248f021b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":91,
                  "y":554},
                "size":{
                  "width":36,
                  "height":36},
                "outerShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":188,
                    "g":188,
                    "b":188,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u75.png"}},
{
          "id":"49b653fdd6c34e4ca710a736462a08fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF575757},
            "location":{
              "x":40,
              "y":614},
            "size":{
              "width":160,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6beb2b8b268143a397430747564aa75b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF575757},
                "location":{
                  "x":40,
                  "y":614},
                "size":{
                  "width":160,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u65.png"}},
{
          "id":"b566ee93483b441fba43eca0d7a83dfd",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":21,
              "y":102},
            "size":{
              "width":200,
              "height":111}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4e3978dad93417abf520211c9dd16eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":21,
                  "y":102},
                "size":{
                  "width":200,
                  "height":111}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Dashboard in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"dashboard.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u79.png"}},
{
          "id":"9eaa2be3c3724f28963d35b1ac998c91",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":20,
              "y":211},
            "size":{
              "width":200,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b382f0f0d234f74b9a11d66c0f9ff02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":20,
                  "y":211},
                "size":{
                  "width":200,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News Updates in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news_updates.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u81.png"}},
{
          "id":"3104e4447dcc4ddc8d6b20cc548d720c",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":20,
              "y":321},
            "size":{
              "width":200,
              "height":111}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ba76d38914542b69e4b39f7dba5ca48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":20,
                  "y":321},
                "size":{
                  "width":200,
                  "height":111}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Users in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"users.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u79.png"}},
{
          "id":"faa1badcf51d4e5ba08a74d0b6894f49",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":19,
              "y":430},
            "size":{
              "width":200,
              "height":112}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80eeec1b167048e3a0221d79018f97d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":19,
                  "y":430},
                "size":{
                  "width":200,
                  "height":112}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Projects in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"projects.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u85.png"}},
{
          "id":"b350f15d0d5040158b1c0c54828fb3e9",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":20,
              "y":545},
            "size":{
              "width":200,
              "height":109}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f4b9642e51f4b56aed0bc7bf66697d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":20,
                  "y":545},
                "size":{
                  "width":200,
                  "height":109}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Reports in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"reports.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u87.png"}}]}},
  "masters":{
    "94f8821b4bd94788b5cc436b44ff4f3d":{
      "packageId":"94f8821b4bd94788b5cc436b44ff4f3d",
      "type":"Axure:Master",
      "name":"New Master 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"28c93813b38647b2b164b9e09177eac9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":-16,
                "y":0},
              "size":{
                "width":1016,
                "height":690},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"830357c732864407b8522edb2a2455e1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-16,
                    "y":0},
                  "size":{
                    "width":1016,
                    "height":690},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u1.png"}},
{
            "id":"e44fbd401aa944089e8e5f16df78b550",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF8445AD},
              "location":{
                "x":-20,
                "y":0},
              "size":{
                "width":1020,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"77653441843842838d0546cc0127d6ab",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF8445AD},
                  "location":{
                    "x":-20,
                    "y":0},
                  "size":{
                    "width":1020,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u3.png"}},
{
            "id":"2c8a0a156bf74f39bd7b6e6bb160c340",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "location":{
                "x":0,
                "y":49},
              "size":{
                "width":200,
                "height":641},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"55184db0186d44d78b3949cf87e643e6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "location":{
                    "x":0,
                    "y":49},
                  "size":{
                    "width":200,
                    "height":641},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u5.png"}},
{
            "id":"30e5a7d9c7884c9e9af62f7b275f076f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF8445AD},
              "location":{
                "x":900,
                "y":10},
              "size":{
                "width":34,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6d25e5cf503240a2a22955705ea1c013",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF8445AD},
                  "location":{
                    "x":900,
                    "y":10},
                  "size":{
                    "width":34,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u7.png"}},
{
            "id":"afa8bbeccb2c416fb00309d5a0a39de9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":689},
              "size":{
                "width":984,
                "height":25},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"14b04da03a5344ff9ba4f051e36d31b6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":689},
                  "size":{
                    "width":984,
                    "height":25},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u9.png"}},
{
            "id":"02804bed18a648f0ba7708384dd6f9ad",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Arial Bold', 'Arial'",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "size":{
                "width":200,
                "height":100},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF515151},
              "outerShadow":{
                "on":false,
                "offsetX":5,
                "offsetY":5,
                "blurRadius":5,
                "color":{
                  "r":188,
                  "g":188,
                  "b":188,
                  "a":0.349019607843137}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aae9e40428ce49a6b231d8b73bd2aa44",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Bold', 'Arial'",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "size":{
                    "width":200,
                    "height":100},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF515151},
                  "outerShadow":{
                    "on":false,
                    "offsetX":5,
                    "offsetY":5,
                    "blurRadius":5,
                    "color":{
                      "r":188,
                      "g":188,
                      "b":188,
                      "a":0.349019607843137}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u11.png"}},
{
            "id":"bb94e6fc3bdd45648536ad9dae6c04fd",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Bold', 'Arial'",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF8445AD},
              "location":{
                "x":810,
                "y":10},
              "size":{
                "width":90,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"86f0d4376e2a4cf78f38b7afe2e66693",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Bold', 'Arial'",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF8445AD},
                  "location":{
                    "x":810,
                    "y":10},
                  "size":{
                    "width":90,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u13.png"}},
{
            "id":"6d19e2165f484f2f91547387aaa4c0aa",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":90},
              "size":{
                "width":800,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4CAF50}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/dashboard/u15_line.png"}},
{
            "id":"3093340320e34795834ea6f26df495f3",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":34,
                "y":2},
              "size":{
                "width":88,
                "height":88}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5189ab40624d4ac8992e435c4f58808f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":34,
                    "y":2},
                  "size":{
                    "width":88,
                    "height":88}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/splash/u4.png"}},
{
            "id":"58ad05f8ab22426e89b347681bce1d5f",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":194,
                "y":-3},
              "size":{
                "width":10,
                "height":693},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF333333}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/dashboard/u18_line.png"}},
{
            "id":"94e358730f06438a80b018d9f03beda4",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":-5,
                "y":-3},
              "size":{
                "width":10,
                "height":693},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF333333}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/dashboard/u18_line.png"}}]}}},
  "objectPaths":{
    "52061efb53794b9e932e51f128efd672":{
      "scriptId":"u0",
      "28c93813b38647b2b164b9e09177eac9":{
        "scriptId":"u1"},
      "830357c732864407b8522edb2a2455e1":{
        "scriptId":"u2"},
      "e44fbd401aa944089e8e5f16df78b550":{
        "scriptId":"u3"},
      "77653441843842838d0546cc0127d6ab":{
        "scriptId":"u4"},
      "2c8a0a156bf74f39bd7b6e6bb160c340":{
        "scriptId":"u5"},
      "55184db0186d44d78b3949cf87e643e6":{
        "scriptId":"u6"},
      "30e5a7d9c7884c9e9af62f7b275f076f":{
        "scriptId":"u7"},
      "6d25e5cf503240a2a22955705ea1c013":{
        "scriptId":"u8"},
      "afa8bbeccb2c416fb00309d5a0a39de9":{
        "scriptId":"u9"},
      "14b04da03a5344ff9ba4f051e36d31b6":{
        "scriptId":"u10"},
      "02804bed18a648f0ba7708384dd6f9ad":{
        "scriptId":"u11"},
      "aae9e40428ce49a6b231d8b73bd2aa44":{
        "scriptId":"u12"},
      "bb94e6fc3bdd45648536ad9dae6c04fd":{
        "scriptId":"u13"},
      "86f0d4376e2a4cf78f38b7afe2e66693":{
        "scriptId":"u14"},
      "6d19e2165f484f2f91547387aaa4c0aa":{
        "scriptId":"u15"},
      "3093340320e34795834ea6f26df495f3":{
        "scriptId":"u16"},
      "5189ab40624d4ac8992e435c4f58808f":{
        "scriptId":"u17"},
      "58ad05f8ab22426e89b347681bce1d5f":{
        "scriptId":"u18"},
      "94e358730f06438a80b018d9f03beda4":{
        "scriptId":"u19"}},
    "75190f5b0e9743efa0fbe4712ae44b21":{
      "scriptId":"u20"},
    "77392aa4176c4788baecd394fe7c7d81":{
      "scriptId":"u21"},
    "b32a9909592c4edb996fbf3793e35492":{
      "scriptId":"u22"},
    "fa3e19e6c67d48c3b2e608c290618fc2":{
      "scriptId":"u23"},
    "c54f4da0ec9f4a72a36d4fa1fa1f4f02":{
      "scriptId":"u24"},
    "593b5ddb61014a768617cee367e41812":{
      "scriptId":"u25"},
    "cfa95dcb8c09410d8ba79839304e7ef4":{
      "scriptId":"u26"},
    "ad0280d53d994e08b19ed260db2a78aa":{
      "scriptId":"u27"},
    "a49ea641b8f240a2a6206df1741cafa7":{
      "scriptId":"u28"},
    "f9dab4464e8d49a0bf88e1f6fe099b92":{
      "scriptId":"u29"},
    "72ec7a1251564ed1a97fd561896da466":{
      "scriptId":"u30"},
    "34f7b99e1ae54dbaa43b0e21ffbe2310":{
      "scriptId":"u31"},
    "fb4408fb89b540cc9dea95aae30c5379":{
      "scriptId":"u32"},
    "d4d143a64d3245eb8d27d4309b0ba020":{
      "scriptId":"u33"},
    "3c8acff385f04c5e9d0b94dcb3129592":{
      "scriptId":"u34"},
    "4b5201e288b445218b3a286ad7ba023c":{
      "scriptId":"u35"},
    "192c3832cbe14b28886d74fdcc66ec4a":{
      "scriptId":"u36"},
    "e58099c2149e4fe0ad6be181e767a4b6":{
      "scriptId":"u37"},
    "ace7517953d84520ad4bef0ccffc69e7":{
      "scriptId":"u38"},
    "610b8db3b2eb4a1d91e1ab5e49258bdf":{
      "scriptId":"u39"},
    "226e1aee654645d9bc97fbde8528cf24":{
      "scriptId":"u40"},
    "203d0f95061c43ddae47add4ad733600":{
      "scriptId":"u41"},
    "026ae92a30a94148b4f4d7c270615c86":{
      "scriptId":"u42"},
    "b6f90164107442d4802824d662eb9a98":{
      "scriptId":"u43"},
    "494fc3c5b3fa47c083debeaa755b237e":{
      "scriptId":"u44"},
    "4883d094b94948f59d05ba618bedc675":{
      "scriptId":"u45"},
    "5cff971a12784beb914a5325f4ee8c57":{
      "scriptId":"u46"},
    "1036179864fb4570934166c519603c75":{
      "scriptId":"u47"},
    "8bfc5fe523224ea4b1ac44e238d391c2":{
      "scriptId":"u48"},
    "abfa0f5f00a844c291a0124876fbfe8c":{
      "scriptId":"u49"},
    "8dbd61c2a97a48c8bf5a6ab1cddde30d":{
      "scriptId":"u50"},
    "29abda3eb9f6493a9c784c611d869fd2":{
      "scriptId":"u51"},
    "916c2b96c5a94dcba7a8e85130c335d9":{
      "scriptId":"u52"},
    "34dc2dcb44b24137adf7c27516e35d0c":{
      "scriptId":"u53"},
    "de4d1ba5c1864d048d8d713c6dc52a18":{
      "scriptId":"u54"},
    "0988c72b53904a5f9323985af70885ea":{
      "scriptId":"u55"},
    "bdd43c447496414a9037cb032bfd1e22":{
      "scriptId":"u56"},
    "6a0f7a95cbe04ebbaa39634e259558ad":{
      "scriptId":"u57"},
    "5eff6cac17fe4a87af7a2762f140ff39":{
      "scriptId":"u58"},
    "2ac8e1f8a6be4031a5101f8865cfd4b2":{
      "scriptId":"u59"},
    "53ef8d81c9c945e28c787e06504adb1d":{
      "scriptId":"u60"},
    "72e4bc8bdc3d4bc28180b67a06efe8f7":{
      "scriptId":"u61"},
    "87319c80b06f41f5a347bde7dc0aab81":{
      "scriptId":"u62"},
    "f579ecb75a964d9eb45cb2a0eccbe27b":{
      "scriptId":"u63"},
    "017e10b158ed4851ad3eed575171caeb":{
      "scriptId":"u64"},
    "72bfea42e2a44ad189737a8b95734738":{
      "scriptId":"u65"},
    "ecd867a1de7840d490df637185e40156":{
      "scriptId":"u66"},
    "54407d2722d84df5b71a2b32a4cdfd71":{
      "scriptId":"u67"},
    "aa56017a71134273ac7ba77558cf89e3":{
      "scriptId":"u68"},
    "5ddf3ca74eb14cbdb690b8fd497150fc":{
      "scriptId":"u69"},
    "6f2937d149d14e8a9baa299e6ea18fdb":{
      "scriptId":"u70"},
    "57791c004ed34bb3aa2fec6926eaf8e5":{
      "scriptId":"u71"},
    "dd9d58ad2c944c11a03356dd076d9ae4":{
      "scriptId":"u72"},
    "b9833a6310a8493c962a4d6e0bb6e70e":{
      "scriptId":"u73"},
    "126aba3ec4a5445baf768a53255929db":{
      "scriptId":"u74"},
    "b31867946ee743e7a16493c2544c0d0f":{
      "scriptId":"u75"},
    "708dfae1b7144c989841034248f021b3":{
      "scriptId":"u76"},
    "49b653fdd6c34e4ca710a736462a08fe":{
      "scriptId":"u77"},
    "6beb2b8b268143a397430747564aa75b":{
      "scriptId":"u78"},
    "b566ee93483b441fba43eca0d7a83dfd":{
      "scriptId":"u79"},
    "b4e3978dad93417abf520211c9dd16eb":{
      "scriptId":"u80"},
    "9eaa2be3c3724f28963d35b1ac998c91":{
      "scriptId":"u81"},
    "9b382f0f0d234f74b9a11d66c0f9ff02":{
      "scriptId":"u82"},
    "3104e4447dcc4ddc8d6b20cc548d720c":{
      "scriptId":"u83"},
    "6ba76d38914542b69e4b39f7dba5ca48":{
      "scriptId":"u84"},
    "faa1badcf51d4e5ba08a74d0b6894f49":{
      "scriptId":"u85"},
    "80eeec1b167048e3a0221d79018f97d1":{
      "scriptId":"u86"},
    "b350f15d0d5040158b1c0c54828fb3e9":{
      "scriptId":"u87"},
    "4f4b9642e51f4b56aed0bc7bf66697d3":{
      "scriptId":"u88"}}});