$axure.loadCurrentPage({
  "url":"surveys_-_create_ambassador_survey_2.html",
  "generationDate":new Date(1479235413505.28),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7cf0d9458ba04fa2903302f6ceb9b103",
    "type":"Axure:Page",
    "name":"Surveys - Create Ambassador Survey 2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ed9e661311c14ecabc6e21374bd7da49",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"e163cbb4cef54461ad56955f368f2e96"},
{
          "id":"50d2b2d4c29646dc93056ec91da36a68",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":293,
              "y":142},
            "size":{
              "width":1022,
              "height":578},
            "borderWidth":"-1",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":0,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"275a469800b24cfba05d332b439140ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":293,
                  "y":142},
                "size":{
                  "width":1022,
                  "height":578},
                "borderWidth":"-1",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":0,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/surveys_-_create_ambassador_survey_2/u11.png"}},
{
          "id":"25d072d34c744d62ae340b57ca681863",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Regular', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":294,
              "y":72},
            "size":{
              "width":231,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6187c0abb18745ea9d858ede21541561",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Regular', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":294,
                  "y":72},
                "size":{
                  "width":231,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff04d3ec6cb7424382e0f3a344183d96",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1996C7},
            "location":{
              "x":293,
              "y":142},
            "size":{
              "width":1022,
              "height":54},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"940f47bfa61648ed8dcf3ffe78419feb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1996C7},
                "location":{
                  "x":293,
                  "y":142},
                "size":{
                  "width":1022,
                  "height":54},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/surveys_-_create_ambassador_survey_2/u15.png"}},
{
          "id":"78296b63b5c1497b852ac6ea441e9d08",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1996C7},
            "location":{
              "x":704,
              "y":610},
            "size":{
              "width":70,
              "height":30},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":0,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21d65a0ed6504bcdb474d8a7f22494a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1996C7},
                "location":{
                  "x":704,
                  "y":610},
                "size":{
                  "width":70,
                  "height":30},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":0,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/list_of_ambassadors/u17.png"}},
{
          "id":"a597a1daee1742d7aae84b0c93cc41e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":320,
              "y":207},
            "size":{
              "width":120,
              "height":1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c14a89666b7741198643c90d10089896",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":320,
                  "y":207},
                "size":{
                  "width":120,
                  "height":1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ca10e75ef4b4166b698f148c564d50e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1996C7},
            "location":{
              "x":800,
              "y":610},
            "size":{
              "width":70,
              "height":30},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":0,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ffc8c91a8824374afe36ff31624847c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1996C7},
                "location":{
                  "x":800,
                  "y":610},
                "size":{
                  "width":70,
                  "height":30},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":0,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/list_of_ambassadors/u17.png"}},
{
          "id":"34adc3f7b77a4b679a9359b511262cca",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":202},
            "size":{
              "width":294,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f13f9ec036984d7685f6d2277554e943",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":321,
              "y":404},
            "size":{
              "width":120,
              "height":1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d72f830c29f4daf9e0267d7f88766b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":321,
                  "y":404},
                "size":{
                  "width":120,
                  "height":1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46c2a82b8bdf491d8d9c7d4b92d03fc2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":411,
              "y":399},
            "size":{
              "width":294,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"96ce6536e20d4766a36da88705c2e79c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":441,
              "y":437},
            "size":{
              "width":120,
              "height":1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbf50b194f4e462b879674f3ee640c92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":441,
                  "y":437},
                "size":{
                  "width":120,
                  "height":1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4456224c106345ae89fc2f53a6517a42",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":505,
              "y":433},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b50133793bbb4f05b3ab01627454ebf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":441,
              "y":465},
            "size":{
              "width":120,
              "height":1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ee4768e4d084da3907908fcaa21ed86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":441,
                  "y":465},
                "size":{
                  "width":120,
                  "height":1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"47a2a573126a4f4eadd11e6cd233c08f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":505,
              "y":461},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4d57dc657b834d90adf9435fcce1b3e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":441,
              "y":494},
            "size":{
              "width":120,
              "height":1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"728744e22c804851ac6b0c5f6fd34214",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":441,
                  "y":494},
                "size":{
                  "width":120,
                  "height":1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97982b0cc95940d88a17e8e4eb849467",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":505,
              "y":490},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"20c24641a972428196119ba7ff7e7874",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":441,
              "y":523},
            "size":{
              "width":120,
              "height":1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6b4cb6cffb6445ebdf5c652d70fe8ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":441,
                  "y":523},
                "size":{
                  "width":120,
                  "height":1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d96dde4cecc4342bee06c645285a7e5",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":505,
              "y":519},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"821ae6453ff54221be4112073f1d8ab1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":793,
              "y":206},
            "size":{
              "width":120,
              "height":1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b457e02a2fc147349d3a3961e5732e0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":793,
                  "y":206},
                "size":{
                  "width":120,
                  "height":1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dad72f8d451746ac8ce248637b7039b2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":883,
              "y":201},
            "size":{
              "width":294,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"14cfeaa7eb334e8a99600dd2b7e6d74d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":913,
              "y":239},
            "size":{
              "width":120,
              "height":1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7481d5da43274469ad98140b755b2346",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":913,
                  "y":239},
                "size":{
                  "width":120,
                  "height":1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2a0bf93d713477cb77ed542b1aa3ba2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":977,
              "y":235},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d13db3494491464b8cc029a1bb80eb6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":913,
              "y":267},
            "size":{
              "width":120,
              "height":1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ecb19fe48b74c42948580a3f6f210d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":913,
                  "y":267},
                "size":{
                  "width":120,
                  "height":1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3042d99144df42a38e7fbdfada615e4b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":977,
              "y":263},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b51b95ef638e4793b57052d1b64a8aa5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":913,
              "y":296},
            "size":{
              "width":120,
              "height":1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5243c4e1c2f64922ad9bd67d30c11a05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":913,
                  "y":296},
                "size":{
                  "width":120,
                  "height":1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9341969c366d489fa7225eb8d0b0bc0b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":977,
              "y":292},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"54507283c08d4cd4b53b14141b0af6c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":913,
              "y":325},
            "size":{
              "width":120,
              "height":1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4724d936674a46639b865bfdcb3fc5ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":913,
                  "y":325},
                "size":{
                  "width":120,
                  "height":1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d70d53eb5bb4eebb813e25247fbe271",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":977,
              "y":321},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d3ad9f4b0ba34cbc805139b813b6b85e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":794,
              "y":403},
            "size":{
              "width":120,
              "height":1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a7ad1fd19984b208e642e13a841c488",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":794,
                  "y":403},
                "size":{
                  "width":120,
                  "height":1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2da85272549441e2b45e73362f9e0fa6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":884,
              "y":398},
            "size":{
              "width":294,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5976678a158542cc962c1c32a5d3e512",
          "label":"Line Horizontal",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":336,
              "y":361},
            "size":{
              "width":960,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/surveys_-_create_ambassador_survey_2/line_horizontal_u57_line.png"}},
{
          "id":"1046721e71b74f14bdf0fbb729308b9e",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":239},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"638fb9bd578a40b185ab230d4785b8a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":239},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"6e56f117ee4b4def8c90c8dd8d4607a5",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":465},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d7525b48dd04e0bbfbdb4fec6598005",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":465},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"a1ba58eb9f6e40e3944b75b5f489abcb",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":794,
              "y":264},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b39aaf55994f4fc19518bafc030b150e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":794,
                  "y":264},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"f992c81d06e24194a7b765d7396030cf",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":794,
              "y":454},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"351950e1c21344aab4ab5f555bc3b311",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":794,
                  "y":454},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"b9ecfb13231048a2a9e1adf0904dedad",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":409,
              "y":258},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9a9095cbf1847699c7c8410e7a16bd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":409,
                  "y":258},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"f357860fe86341e4b3b8384ad13582c7",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":794,
              "y":281},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0ab22c900134e499417c7c9f208be91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":794,
                  "y":281},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c39338e3ecaa4cbd8878f01049d6b790",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":794,
              "y":471},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d317bde54e4a4ce88344de664aff339f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":794,
                  "y":471},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"72b6a416da9e4503bb16980ae821ee7b",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":319,
              "y":483},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"442178184cf2418e8a0c20184b4e3774",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":319,
                  "y":483},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"7c6fc4cc31ff4de88ae6b4a3f0f7a1f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":54},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba31a676ddf84be9ac7aacc18bb79856",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":54},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Dashboard in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"dashboard.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"c61a846594c74e078a4dc93432865cae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":95},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"572c839d48324edc8de2e652803c2087",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":95},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open List Of Ambassadors in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"list_of_ambassadors.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"2c611599c3f94315843cc9654c6d9ebb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1996C7,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":136},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ba4e281cb874db0a3582cf8b2270b03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1996C7,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":136},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Surveys in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"surveys.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"36fed7cbc8f64c488ae75b9d29068b1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":177},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a34d986edb0146d38d95a069dd896168",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":177},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Leads in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"leads.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"8deba48bfea64853a854b5d03fe19205",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":219},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dcffb110c774140bddee6cf4ddea40d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":219},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News Updates in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news_updates.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"c8ab97e167f749279c19ace5a1d6f5bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":261},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d438c4b243f04e70ad24f8929a48c7f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":261},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Users in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"users.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"06a5ab230a4c4539a1c08db5e2a760dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":-1,
              "y":303},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6046d82b8a124558a6a8c2a8cbbbf253",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":-1,
                  "y":303},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Events in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"events.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}}]}},
  "masters":{
    "e163cbb4cef54461ad56955f368f2e96":{
      "packageId":"e163cbb4cef54461ad56955f368f2e96",
      "type":"Axure:Master",
      "name":"main",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1affd31496854a90aaf55cb21b7c1027",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF9F9F9},
              "size":{
                "width":1366,
                "height":768}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6b795c4f50714ccc8e66f16ce98c2618",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF9F9F9},
                  "size":{
                    "width":1366,
                    "height":768}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u1.png"}},
{
            "id":"cee52dc11a8744b0a43052d502487fd5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF1996C7},
              "size":{
                "width":1366,
                "height":50},
              "borderWidth":"-1",
              "outerShadow":{
                "on":true,
                "offsetX":0,
                "offsetY":1,
                "blurRadius":5,
                "color":{
                  "r":0,
                  "g":0,
                  "b":0,
                  "a":0.349019607843137}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bde88dba9c1a4e2988a327f1c196765c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF1996C7},
                  "size":{
                    "width":1366,
                    "height":50},
                  "borderWidth":"-1",
                  "outerShadow":{
                    "on":true,
                    "offsetX":0,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.349019607843137}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u3.png"}},
{
            "id":"56fbb49b18bd46129591d114da88345e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF0E5570},
              "location":{
                "x":0,
                "y":50},
              "size":{
                "width":1366,
                "height":4},
              "borderWidth":"-1",
              "outerShadow":{
                "on":true,
                "offsetX":0,
                "offsetY":1,
                "blurRadius":5,
                "color":{
                  "r":0,
                  "g":0,
                  "b":0,
                  "a":0.349019607843137}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b9154b46c7af49f6b3c8fa13b5e2aa9c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0E5570},
                  "location":{
                    "x":0,
                    "y":50},
                  "size":{
                    "width":1366,
                    "height":4},
                  "borderWidth":"-1",
                  "outerShadow":{
                    "on":true,
                    "offsetX":0,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.349019607843137}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u5.png"}},
{
            "id":"8e7b142cf5d5486cbc949c1ae82f56d1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF212121},
              "location":{
                "x":0,
                "y":54},
              "size":{
                "width":250,
                "height":714},
              "borderWidth":"-1",
              "outerShadow":{
                "on":true,
                "offsetX":2,
                "offsetY":0,
                "blurRadius":5,
                "color":{
                  "r":0,
                  "g":0,
                  "b":0,
                  "a":0.349019607843137}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59e38fb539e04bb29cde628389cf5bd8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF212121},
                  "location":{
                    "x":0,
                    "y":54},
                  "size":{
                    "width":250,
                    "height":714},
                  "borderWidth":"-1",
                  "outerShadow":{
                    "on":true,
                    "offsetX":2,
                    "offsetY":0,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.349019607843137}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u7.png"}},
{
            "id":"dcdfff1ef73440ecb729883ed1488cee",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"28px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":31,
                "y":7},
              "size":{
                "width":140,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ee24b8d3672d4a26a4e0d5b9d8a0528a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"28px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":31,
                    "y":7},
                  "size":{
                    "width":140,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "ed9e661311c14ecabc6e21374bd7da49":{
      "scriptId":"u0",
      "1affd31496854a90aaf55cb21b7c1027":{
        "scriptId":"u1"},
      "6b795c4f50714ccc8e66f16ce98c2618":{
        "scriptId":"u2"},
      "cee52dc11a8744b0a43052d502487fd5":{
        "scriptId":"u3"},
      "bde88dba9c1a4e2988a327f1c196765c":{
        "scriptId":"u4"},
      "56fbb49b18bd46129591d114da88345e":{
        "scriptId":"u5"},
      "b9154b46c7af49f6b3c8fa13b5e2aa9c":{
        "scriptId":"u6"},
      "8e7b142cf5d5486cbc949c1ae82f56d1":{
        "scriptId":"u7"},
      "59e38fb539e04bb29cde628389cf5bd8":{
        "scriptId":"u8"},
      "dcdfff1ef73440ecb729883ed1488cee":{
        "scriptId":"u9"},
      "ee24b8d3672d4a26a4e0d5b9d8a0528a":{
        "scriptId":"u10"}},
    "50d2b2d4c29646dc93056ec91da36a68":{
      "scriptId":"u11"},
    "275a469800b24cfba05d332b439140ad":{
      "scriptId":"u12"},
    "25d072d34c744d62ae340b57ca681863":{
      "scriptId":"u13"},
    "6187c0abb18745ea9d858ede21541561":{
      "scriptId":"u14"},
    "ff04d3ec6cb7424382e0f3a344183d96":{
      "scriptId":"u15"},
    "940f47bfa61648ed8dcf3ffe78419feb":{
      "scriptId":"u16"},
    "78296b63b5c1497b852ac6ea441e9d08":{
      "scriptId":"u17"},
    "21d65a0ed6504bcdb474d8a7f22494a9":{
      "scriptId":"u18"},
    "a597a1daee1742d7aae84b0c93cc41e1":{
      "scriptId":"u19"},
    "c14a89666b7741198643c90d10089896":{
      "scriptId":"u20"},
    "7ca10e75ef4b4166b698f148c564d50e":{
      "scriptId":"u21"},
    "1ffc8c91a8824374afe36ff31624847c":{
      "scriptId":"u22"},
    "34adc3f7b77a4b679a9359b511262cca":{
      "scriptId":"u23"},
    "f13f9ec036984d7685f6d2277554e943":{
      "scriptId":"u24"},
    "8d72f830c29f4daf9e0267d7f88766b8":{
      "scriptId":"u25"},
    "46c2a82b8bdf491d8d9c7d4b92d03fc2":{
      "scriptId":"u26"},
    "96ce6536e20d4766a36da88705c2e79c":{
      "scriptId":"u27"},
    "fbf50b194f4e462b879674f3ee640c92":{
      "scriptId":"u28"},
    "4456224c106345ae89fc2f53a6517a42":{
      "scriptId":"u29"},
    "b50133793bbb4f05b3ab01627454ebf1":{
      "scriptId":"u30"},
    "4ee4768e4d084da3907908fcaa21ed86":{
      "scriptId":"u31"},
    "47a2a573126a4f4eadd11e6cd233c08f":{
      "scriptId":"u32"},
    "4d57dc657b834d90adf9435fcce1b3e2":{
      "scriptId":"u33"},
    "728744e22c804851ac6b0c5f6fd34214":{
      "scriptId":"u34"},
    "97982b0cc95940d88a17e8e4eb849467":{
      "scriptId":"u35"},
    "20c24641a972428196119ba7ff7e7874":{
      "scriptId":"u36"},
    "b6b4cb6cffb6445ebdf5c652d70fe8ca":{
      "scriptId":"u37"},
    "2d96dde4cecc4342bee06c645285a7e5":{
      "scriptId":"u38"},
    "821ae6453ff54221be4112073f1d8ab1":{
      "scriptId":"u39"},
    "b457e02a2fc147349d3a3961e5732e0a":{
      "scriptId":"u40"},
    "dad72f8d451746ac8ce248637b7039b2":{
      "scriptId":"u41"},
    "14cfeaa7eb334e8a99600dd2b7e6d74d":{
      "scriptId":"u42"},
    "7481d5da43274469ad98140b755b2346":{
      "scriptId":"u43"},
    "e2a0bf93d713477cb77ed542b1aa3ba2":{
      "scriptId":"u44"},
    "d13db3494491464b8cc029a1bb80eb6c":{
      "scriptId":"u45"},
    "2ecb19fe48b74c42948580a3f6f210d0":{
      "scriptId":"u46"},
    "3042d99144df42a38e7fbdfada615e4b":{
      "scriptId":"u47"},
    "b51b95ef638e4793b57052d1b64a8aa5":{
      "scriptId":"u48"},
    "5243c4e1c2f64922ad9bd67d30c11a05":{
      "scriptId":"u49"},
    "9341969c366d489fa7225eb8d0b0bc0b":{
      "scriptId":"u50"},
    "54507283c08d4cd4b53b14141b0af6c5":{
      "scriptId":"u51"},
    "4724d936674a46639b865bfdcb3fc5ff":{
      "scriptId":"u52"},
    "3d70d53eb5bb4eebb813e25247fbe271":{
      "scriptId":"u53"},
    "d3ad9f4b0ba34cbc805139b813b6b85e":{
      "scriptId":"u54"},
    "0a7ad1fd19984b208e642e13a841c488":{
      "scriptId":"u55"},
    "2da85272549441e2b45e73362f9e0fa6":{
      "scriptId":"u56"},
    "5976678a158542cc962c1c32a5d3e512":{
      "scriptId":"u57"},
    "1046721e71b74f14bdf0fbb729308b9e":{
      "scriptId":"u58"},
    "638fb9bd578a40b185ab230d4785b8a7":{
      "scriptId":"u59"},
    "6e56f117ee4b4def8c90c8dd8d4607a5":{
      "scriptId":"u60"},
    "0d7525b48dd04e0bbfbdb4fec6598005":{
      "scriptId":"u61"},
    "a1ba58eb9f6e40e3944b75b5f489abcb":{
      "scriptId":"u62"},
    "b39aaf55994f4fc19518bafc030b150e":{
      "scriptId":"u63"},
    "f992c81d06e24194a7b765d7396030cf":{
      "scriptId":"u64"},
    "351950e1c21344aab4ab5f555bc3b311":{
      "scriptId":"u65"},
    "b9ecfb13231048a2a9e1adf0904dedad":{
      "scriptId":"u66"},
    "b9a9095cbf1847699c7c8410e7a16bd2":{
      "scriptId":"u67"},
    "f357860fe86341e4b3b8384ad13582c7":{
      "scriptId":"u68"},
    "f0ab22c900134e499417c7c9f208be91":{
      "scriptId":"u69"},
    "c39338e3ecaa4cbd8878f01049d6b790":{
      "scriptId":"u70"},
    "d317bde54e4a4ce88344de664aff339f":{
      "scriptId":"u71"},
    "72b6a416da9e4503bb16980ae821ee7b":{
      "scriptId":"u72"},
    "442178184cf2418e8a0c20184b4e3774":{
      "scriptId":"u73"},
    "7c6fc4cc31ff4de88ae6b4a3f0f7a1f2":{
      "scriptId":"u74"},
    "ba31a676ddf84be9ac7aacc18bb79856":{
      "scriptId":"u75"},
    "c61a846594c74e078a4dc93432865cae":{
      "scriptId":"u76"},
    "572c839d48324edc8de2e652803c2087":{
      "scriptId":"u77"},
    "2c611599c3f94315843cc9654c6d9ebb":{
      "scriptId":"u78"},
    "3ba4e281cb874db0a3582cf8b2270b03":{
      "scriptId":"u79"},
    "36fed7cbc8f64c488ae75b9d29068b1b":{
      "scriptId":"u80"},
    "a34d986edb0146d38d95a069dd896168":{
      "scriptId":"u81"},
    "8deba48bfea64853a854b5d03fe19205":{
      "scriptId":"u82"},
    "8dcffb110c774140bddee6cf4ddea40d":{
      "scriptId":"u83"},
    "c8ab97e167f749279c19ace5a1d6f5bc":{
      "scriptId":"u84"},
    "d438c4b243f04e70ad24f8929a48c7f6":{
      "scriptId":"u85"},
    "06a5ab230a4c4539a1c08db5e2a760dc":{
      "scriptId":"u86"},
    "6046d82b8a124558a6a8c2a8cbbbf253":{
      "scriptId":"u87"}}});