$axure.loadCurrentPage({
  "url":"dashboard_1.html",
  "generationDate":new Date(1470822513230.11),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"564dfa69f91643409ac59346cde58c2d",
    "type":"Axure:Page",
    "name":"Dashboard",
    "notes":{
      "Note":"<p><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">Top Level Navigation links</span></p><p><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">Default&nbsp; Navigation Link </span></p><p><span>Background color: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">None</span><span>&nbsp;</span></p><p><span>Border Color: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">None</span></p><p><span>Font size: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">13</span></p><p><span>Font Color: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">#</span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">363636</span><span>&nbsp;</span></p><p><span>&nbsp;</span></p><p><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">ActiveTop Navigation link</span></p><p><span>Background color: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">None</span><span>&nbsp;</span></p><p><span>Border Color: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">None</span></p><p><span>Font size: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">13</span></p><p><span>Font Color: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">#1DB0E5</span></p><p><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">&nbsp;</span></p><p><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">Second level Top Navigation</span></p><p><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">Active Tab</span></p><p><span>Background color: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">1DB0E5</span></p><p><span>Border Color: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">#CCCCCC</span></p><p><span>Font size: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">13</span></p><p><span>Font Color: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">#FFFFFF</span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\"></span><span>&nbsp;</span></p><p><span>&nbsp;</span></p><p><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">Inactive Tab</span></p><p><span>Background color: #</span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">FFFFFF</span></p><p><span>Border Color: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">#CCCCCC</span></p><p><span>Font size: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">13</span></p><p><span>Font Color: </span><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;\">#363636</span><span>&nbsp;</span></p><p><span>&nbsp;</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"52061efb53794b9e932e51f128efd672",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"94f8821b4bd94788b5cc436b44ff4f3d"},
{
          "id":"75190f5b0e9743efa0fbe4712ae44b21",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF363636},
            "location":{
              "x":21,
              "y":102},
            "size":{
              "width":200,
              "height":111},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77392aa4176c4788baecd394fe7c7d81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF363636},
                "location":{
                  "x":21,
                  "y":102},
                "size":{
                  "width":200,
                  "height":111},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u20.png"}},
{
          "id":"b32a9909592c4edb996fbf3793e35492",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":89},
            "size":{
              "width":779,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/dashboard/u22_line.png"}},
{
          "id":"fa3e19e6c67d48c3b2e608c290618fc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5E5E5E,
              "opacity":1},
            "location":{
              "x":250,
              "y":65},
            "size":{
              "width":89,
              "height":24},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c54f4da0ec9f4a72a36d4fa1fa1f4f02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF5E5E5E,
                  "opacity":1},
                "location":{
                  "x":250,
                  "y":65},
                "size":{
                  "width":89,
                  "height":24},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29abda3eb9f6493a9c784c611d869fd2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":92,
              "y":113},
            "size":{
              "width":50,
              "height":50},
            "outerShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":188,
                "g":188,
                "b":188,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"916c2b96c5a94dcba7a8e85130c335d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":92,
                  "y":113},
                "size":{
                  "width":50,
                  "height":50},
                "outerShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":188,
                    "g":188,
                    "b":188,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u51.png"}},
{
          "id":"34dc2dcb44b24137adf7c27516e35d0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF363636},
            "location":{
              "x":21,
              "y":173},
            "size":{
              "width":199,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de4d1ba5c1864d048d8d713c6dc52a18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF363636},
                "location":{
                  "x":21,
                  "y":173},
                "size":{
                  "width":199,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u53.png"}},
{
          "id":"0988c72b53904a5f9323985af70885ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xD35E5E5E},
            "location":{
              "x":20,
              "y":212},
            "size":{
              "width":200,
              "height":111},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdd43c447496414a9037cb032bfd1e22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xD35E5E5E},
                "location":{
                  "x":20,
                  "y":212},
                "size":{
                  "width":200,
                  "height":111},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u55.png"}},
{
          "id":"6a0f7a95cbe04ebbaa39634e259558ad",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":91,
              "y":223},
            "size":{
              "width":48,
              "height":48},
            "outerShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":188,
                "g":188,
                "b":188,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5eff6cac17fe4a87af7a2762f140ff39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":91,
                  "y":223},
                "size":{
                  "width":48,
                  "height":48},
                "outerShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":188,
                    "g":188,
                    "b":188,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u57.png"}},
{
          "id":"2ac8e1f8a6be4031a5101f8865cfd4b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xD35E5E5E},
            "location":{
              "x":20,
              "y":283},
            "size":{
              "width":200,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53ef8d81c9c945e28c787e06504adb1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xD35E5E5E},
                "location":{
                  "x":20,
                  "y":283},
                "size":{
                  "width":200,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u59.png"}},
{
          "id":"b566ee93483b441fba43eca0d7a83dfd",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":21,
              "y":102},
            "size":{
              "width":200,
              "height":111}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4e3978dad93417abf520211c9dd16eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":21,
                  "y":102},
                "size":{
                  "width":200,
                  "height":111}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Dashboard in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"dashboard_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u79.png"}},
{
          "id":"9eaa2be3c3724f28963d35b1ac998c91",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":20,
              "y":211},
            "size":{
              "width":200,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b382f0f0d234f74b9a11d66c0f9ff02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":20,
                  "y":211},
                "size":{
                  "width":200,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News Updates in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news_updates_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u81.png"}}]}},
  "masters":{
    "94f8821b4bd94788b5cc436b44ff4f3d":{
      "packageId":"94f8821b4bd94788b5cc436b44ff4f3d",
      "type":"Axure:Master",
      "name":"New Master 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"28c93813b38647b2b164b9e09177eac9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":-16,
                "y":0},
              "size":{
                "width":1016,
                "height":690},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"830357c732864407b8522edb2a2455e1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-16,
                    "y":0},
                  "size":{
                    "width":1016,
                    "height":690},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u1.png"}},
{
            "id":"e44fbd401aa944089e8e5f16df78b550",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF8445AD},
              "location":{
                "x":-20,
                "y":0},
              "size":{
                "width":1020,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"77653441843842838d0546cc0127d6ab",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF8445AD},
                  "location":{
                    "x":-20,
                    "y":0},
                  "size":{
                    "width":1020,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u3.png"}},
{
            "id":"2c8a0a156bf74f39bd7b6e6bb160c340",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "location":{
                "x":0,
                "y":49},
              "size":{
                "width":200,
                "height":641},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"55184db0186d44d78b3949cf87e643e6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "location":{
                    "x":0,
                    "y":49},
                  "size":{
                    "width":200,
                    "height":641},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u5.png"}},
{
            "id":"30e5a7d9c7884c9e9af62f7b275f076f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF8445AD},
              "location":{
                "x":900,
                "y":10},
              "size":{
                "width":34,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6d25e5cf503240a2a22955705ea1c013",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF8445AD},
                  "location":{
                    "x":900,
                    "y":10},
                  "size":{
                    "width":34,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u7.png"}},
{
            "id":"afa8bbeccb2c416fb00309d5a0a39de9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":689},
              "size":{
                "width":984,
                "height":25},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"14b04da03a5344ff9ba4f051e36d31b6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":689},
                  "size":{
                    "width":984,
                    "height":25},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u9.png"}},
{
            "id":"02804bed18a648f0ba7708384dd6f9ad",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Arial Bold', 'Arial'",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "size":{
                "width":200,
                "height":100},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF515151},
              "outerShadow":{
                "on":false,
                "offsetX":5,
                "offsetY":5,
                "blurRadius":5,
                "color":{
                  "r":188,
                  "g":188,
                  "b":188,
                  "a":0.349019607843137}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aae9e40428ce49a6b231d8b73bd2aa44",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Bold', 'Arial'",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "size":{
                    "width":200,
                    "height":100},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF515151},
                  "outerShadow":{
                    "on":false,
                    "offsetX":5,
                    "offsetY":5,
                    "blurRadius":5,
                    "color":{
                      "r":188,
                      "g":188,
                      "b":188,
                      "a":0.349019607843137}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u11.png"}},
{
            "id":"bb94e6fc3bdd45648536ad9dae6c04fd",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Bold', 'Arial'",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF8445AD},
              "location":{
                "x":810,
                "y":10},
              "size":{
                "width":90,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"86f0d4376e2a4cf78f38b7afe2e66693",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Bold', 'Arial'",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF8445AD},
                  "location":{
                    "x":810,
                    "y":10},
                  "size":{
                    "width":90,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u13.png"}},
{
            "id":"6d19e2165f484f2f91547387aaa4c0aa",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":90},
              "size":{
                "width":800,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF4CAF50}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/dashboard/u15_line.png"}},
{
            "id":"3093340320e34795834ea6f26df495f3",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":34,
                "y":2},
              "size":{
                "width":88,
                "height":88}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5189ab40624d4ac8992e435c4f58808f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":34,
                    "y":2},
                  "size":{
                    "width":88,
                    "height":88}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/splash/u4.png"}},
{
            "id":"58ad05f8ab22426e89b347681bce1d5f",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":194,
                "y":-3},
              "size":{
                "width":10,
                "height":693},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF333333}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/dashboard/u18_line.png"}},
{
            "id":"94e358730f06438a80b018d9f03beda4",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":-5,
                "y":-3},
              "size":{
                "width":10,
                "height":693},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF333333}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/dashboard/u18_line.png"}}]}}},
  "objectPaths":{
    "52061efb53794b9e932e51f128efd672":{
      "scriptId":"u0",
      "28c93813b38647b2b164b9e09177eac9":{
        "scriptId":"u1"},
      "830357c732864407b8522edb2a2455e1":{
        "scriptId":"u2"},
      "e44fbd401aa944089e8e5f16df78b550":{
        "scriptId":"u3"},
      "77653441843842838d0546cc0127d6ab":{
        "scriptId":"u4"},
      "2c8a0a156bf74f39bd7b6e6bb160c340":{
        "scriptId":"u5"},
      "55184db0186d44d78b3949cf87e643e6":{
        "scriptId":"u6"},
      "30e5a7d9c7884c9e9af62f7b275f076f":{
        "scriptId":"u7"},
      "6d25e5cf503240a2a22955705ea1c013":{
        "scriptId":"u8"},
      "afa8bbeccb2c416fb00309d5a0a39de9":{
        "scriptId":"u9"},
      "14b04da03a5344ff9ba4f051e36d31b6":{
        "scriptId":"u10"},
      "02804bed18a648f0ba7708384dd6f9ad":{
        "scriptId":"u11"},
      "aae9e40428ce49a6b231d8b73bd2aa44":{
        "scriptId":"u12"},
      "bb94e6fc3bdd45648536ad9dae6c04fd":{
        "scriptId":"u13"},
      "86f0d4376e2a4cf78f38b7afe2e66693":{
        "scriptId":"u14"},
      "6d19e2165f484f2f91547387aaa4c0aa":{
        "scriptId":"u15"},
      "3093340320e34795834ea6f26df495f3":{
        "scriptId":"u16"},
      "5189ab40624d4ac8992e435c4f58808f":{
        "scriptId":"u17"},
      "58ad05f8ab22426e89b347681bce1d5f":{
        "scriptId":"u18"},
      "94e358730f06438a80b018d9f03beda4":{
        "scriptId":"u19"}},
    "75190f5b0e9743efa0fbe4712ae44b21":{
      "scriptId":"u20"},
    "77392aa4176c4788baecd394fe7c7d81":{
      "scriptId":"u21"},
    "b32a9909592c4edb996fbf3793e35492":{
      "scriptId":"u22"},
    "fa3e19e6c67d48c3b2e608c290618fc2":{
      "scriptId":"u23"},
    "c54f4da0ec9f4a72a36d4fa1fa1f4f02":{
      "scriptId":"u24"},
    "29abda3eb9f6493a9c784c611d869fd2":{
      "scriptId":"u25"},
    "916c2b96c5a94dcba7a8e85130c335d9":{
      "scriptId":"u26"},
    "34dc2dcb44b24137adf7c27516e35d0c":{
      "scriptId":"u27"},
    "de4d1ba5c1864d048d8d713c6dc52a18":{
      "scriptId":"u28"},
    "0988c72b53904a5f9323985af70885ea":{
      "scriptId":"u29"},
    "bdd43c447496414a9037cb032bfd1e22":{
      "scriptId":"u30"},
    "6a0f7a95cbe04ebbaa39634e259558ad":{
      "scriptId":"u31"},
    "5eff6cac17fe4a87af7a2762f140ff39":{
      "scriptId":"u32"},
    "2ac8e1f8a6be4031a5101f8865cfd4b2":{
      "scriptId":"u33"},
    "53ef8d81c9c945e28c787e06504adb1d":{
      "scriptId":"u34"},
    "b566ee93483b441fba43eca0d7a83dfd":{
      "scriptId":"u35"},
    "b4e3978dad93417abf520211c9dd16eb":{
      "scriptId":"u36"},
    "9eaa2be3c3724f28963d35b1ac998c91":{
      "scriptId":"u37"},
    "9b382f0f0d234f74b9a11d66c0f9ff02":{
      "scriptId":"u38"}}});