$axure.loadCurrentPage({
  "url":"inventory_-_update_stock.html",
  "generationDate":new Date(1478111751554.96),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0833c8dbec104d909dc943ff447833f3",
    "type":"Axure:Page",
    "name":"Inventory - Update Stock",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ed9e661311c14ecabc6e21374bd7da49",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"e163cbb4cef54461ad56955f368f2e96"},
{
          "id":"50d2b2d4c29646dc93056ec91da36a68",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":122},
            "size":{
              "width":1022,
              "height":368},
            "borderWidth":"-1",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":0,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"275a469800b24cfba05d332b439140ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":122},
                "size":{
                  "width":1022,
                  "height":368},
                "borderWidth":"-1",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":0,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/inventory_-_add_new_product/u13.png"}},
{
          "id":"25d072d34c744d62ae340b57ca681863",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Regular', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":294,
              "y":72},
            "size":{
              "width":294,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6187c0abb18745ea9d858ede21541561",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Regular', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":294,
                  "y":72},
                "size":{
                  "width":294,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff04d3ec6cb7424382e0f3a344183d96",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1996C7},
            "location":{
              "x":294,
              "y":122},
            "size":{
              "width":1022,
              "height":35},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"940f47bfa61648ed8dcf3ffe78419feb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1996C7},
                "location":{
                  "x":294,
                  "y":122},
                "size":{
                  "width":1022,
                  "height":35},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/inventory/u17.png"}},
{
          "id":"61285f53c3af4e509e50a73c69c49851",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":540,
              "y":215},
            "size":{
              "width":120,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7bf5235656b468c8ee91e42d6a9b86c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":540,
                  "y":215},
                "size":{
                  "width":120,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78296b63b5c1497b852ac6ea441e9d08",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1996C7},
            "location":{
              "x":720,
              "y":440},
            "size":{
              "width":70,
              "height":30},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":0,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21d65a0ed6504bcdb474d8a7f22494a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1996C7},
                "location":{
                  "x":720,
                  "y":440},
                "size":{
                  "width":70,
                  "height":30},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":0,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/inventory_-_add_new_product/u23.png"}},
{
          "id":"7ca10e75ef4b4166b698f148c564d50e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1996C7},
            "location":{
              "x":810,
              "y":440},
            "size":{
              "width":70,
              "height":30},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":0,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ffc8c91a8824374afe36ff31624847c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1996C7},
                "location":{
                  "x":810,
                  "y":440},
                "size":{
                  "width":70,
                  "height":30},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":0,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/inventory_-_add_new_product/u23.png"}},
{
          "id":"993f2d140b554fef83c39682f93110e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":410,
              "y":241},
            "size":{
              "width":120,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed723ddaf6544068b952b4f8abf3c8f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":410,
                  "y":241},
                "size":{
                  "width":120,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e19d4cc5f24747a48c3576974e868af2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":563,
              "y":241},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"69193f78000a4b558ffce7b31d9627b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":410,
              "y":184},
            "size":{
              "width":120,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"403879d766dd495aa1806cc1355a1ef7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":410,
                  "y":184},
                "size":{
                  "width":120,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"73bdaa58364f4852aec5994d3c4c5400",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":563,
              "y":281},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f2bae48798334739b553e6a06ad4bba0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":413,
              "y":276},
            "size":{
              "width":120,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6920137443384413bf28945ffe4e18cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":413,
                  "y":276},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9beb1cab0d74478ebd9b6f74d6615705",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":180},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c6e9f87c400748c0b4e1fb5cd1f7a640",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":413,
              "y":348},
            "size":{
              "width":120,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0747630621c45048c28bf4a97abbcf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":413,
                  "y":348},
                "size":{
                  "width":120,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00bb43707d924f61a7e0f72f658d3305",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":563,
              "y":344},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"004378ddc9cb49ea9766ab90a588d88c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":54},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"718df9e7513e475c8713b75593f6d36e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":54},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Dashboard in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"dashboard.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u151.png"}},
{
          "id":"a19c55c59f514eb0a062645ef545a429",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1996C7,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":95},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5755b1b9734b4546937d285f7803a17a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1996C7,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":95},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Inventory in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"inventory.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u151.png"}},
{
          "id":"06f3c12526d74df4add5e7e497465354",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":136},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3abdcd6e4ce14a53a776dc5d69b736fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":136},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Reports in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"reports.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u151.png"}},
{
          "id":"9150f91ed89c407087573b8e39d37877",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":177},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3881dd897cd048dfbcfdd0a412eaee12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":177},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Users in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"users.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u151.png"}}]}},
  "masters":{
    "e163cbb4cef54461ad56955f368f2e96":{
      "packageId":"e163cbb4cef54461ad56955f368f2e96",
      "type":"Axure:Master",
      "name":"main",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1affd31496854a90aaf55cb21b7c1027",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF9F9F9},
              "size":{
                "width":1366,
                "height":768}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6b795c4f50714ccc8e66f16ce98c2618",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF9F9F9},
                  "size":{
                    "width":1366,
                    "height":768}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u1.png"}},
{
            "id":"cee52dc11a8744b0a43052d502487fd5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF1996C7},
              "size":{
                "width":1366,
                "height":50},
              "borderWidth":"-1",
              "outerShadow":{
                "on":true,
                "offsetX":0,
                "offsetY":1,
                "blurRadius":5,
                "color":{
                  "r":0,
                  "g":0,
                  "b":0,
                  "a":0.349019607843137}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bde88dba9c1a4e2988a327f1c196765c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF1996C7},
                  "size":{
                    "width":1366,
                    "height":50},
                  "borderWidth":"-1",
                  "outerShadow":{
                    "on":true,
                    "offsetX":0,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.349019607843137}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u3.png"}},
{
            "id":"56fbb49b18bd46129591d114da88345e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF1996C7},
              "location":{
                "x":0,
                "y":50},
              "size":{
                "width":1366,
                "height":4},
              "borderWidth":"-1",
              "outerShadow":{
                "on":true,
                "offsetX":0,
                "offsetY":1,
                "blurRadius":5,
                "color":{
                  "r":0,
                  "g":0,
                  "b":0,
                  "a":0.349019607843137}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b9154b46c7af49f6b3c8fa13b5e2aa9c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF1996C7},
                  "location":{
                    "x":0,
                    "y":50},
                  "size":{
                    "width":1366,
                    "height":4},
                  "borderWidth":"-1",
                  "outerShadow":{
                    "on":true,
                    "offsetX":0,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.349019607843137}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u5.png"}},
{
            "id":"8e7b142cf5d5486cbc949c1ae82f56d1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF212121},
              "location":{
                "x":0,
                "y":54},
              "size":{
                "width":250,
                "height":714},
              "borderWidth":"-1",
              "outerShadow":{
                "on":true,
                "offsetX":2,
                "offsetY":0,
                "blurRadius":5,
                "color":{
                  "r":0,
                  "g":0,
                  "b":0,
                  "a":0.349019607843137}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59e38fb539e04bb29cde628389cf5bd8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF212121},
                  "location":{
                    "x":0,
                    "y":54},
                  "size":{
                    "width":250,
                    "height":714},
                  "borderWidth":"-1",
                  "outerShadow":{
                    "on":true,
                    "offsetX":2,
                    "offsetY":0,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.349019607843137}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u7.png"}},
{
            "id":"dcdfff1ef73440ecb729883ed1488cee",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"28px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":31,
                "y":7},
              "size":{
                "width":227,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ee24b8d3672d4a26a4e0d5b9d8a0528a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"28px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":31,
                    "y":7},
                  "size":{
                    "width":227,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8d54821cdaf544ecb28f3ec8b3fa7703",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":446,
                "y":20},
              "size":{
                "width":185,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f8bd0ce314154ca0b0a2b663c0f86542",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":446,
                    "y":20},
                  "size":{
                    "width":185,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "ed9e661311c14ecabc6e21374bd7da49":{
      "scriptId":"u0",
      "1affd31496854a90aaf55cb21b7c1027":{
        "scriptId":"u1"},
      "6b795c4f50714ccc8e66f16ce98c2618":{
        "scriptId":"u2"},
      "cee52dc11a8744b0a43052d502487fd5":{
        "scriptId":"u3"},
      "bde88dba9c1a4e2988a327f1c196765c":{
        "scriptId":"u4"},
      "56fbb49b18bd46129591d114da88345e":{
        "scriptId":"u5"},
      "b9154b46c7af49f6b3c8fa13b5e2aa9c":{
        "scriptId":"u6"},
      "8e7b142cf5d5486cbc949c1ae82f56d1":{
        "scriptId":"u7"},
      "59e38fb539e04bb29cde628389cf5bd8":{
        "scriptId":"u8"},
      "dcdfff1ef73440ecb729883ed1488cee":{
        "scriptId":"u9"},
      "ee24b8d3672d4a26a4e0d5b9d8a0528a":{
        "scriptId":"u10"},
      "8d54821cdaf544ecb28f3ec8b3fa7703":{
        "scriptId":"u11"},
      "f8bd0ce314154ca0b0a2b663c0f86542":{
        "scriptId":"u12"}},
    "50d2b2d4c29646dc93056ec91da36a68":{
      "scriptId":"u13"},
    "275a469800b24cfba05d332b439140ad":{
      "scriptId":"u14"},
    "25d072d34c744d62ae340b57ca681863":{
      "scriptId":"u15"},
    "6187c0abb18745ea9d858ede21541561":{
      "scriptId":"u16"},
    "ff04d3ec6cb7424382e0f3a344183d96":{
      "scriptId":"u17"},
    "940f47bfa61648ed8dcf3ffe78419feb":{
      "scriptId":"u18"},
    "61285f53c3af4e509e50a73c69c49851":{
      "scriptId":"u19"},
    "e7bf5235656b468c8ee91e42d6a9b86c":{
      "scriptId":"u20"},
    "78296b63b5c1497b852ac6ea441e9d08":{
      "scriptId":"u21"},
    "21d65a0ed6504bcdb474d8a7f22494a9":{
      "scriptId":"u22"},
    "7ca10e75ef4b4166b698f148c564d50e":{
      "scriptId":"u23"},
    "1ffc8c91a8824374afe36ff31624847c":{
      "scriptId":"u24"},
    "993f2d140b554fef83c39682f93110e4":{
      "scriptId":"u25"},
    "ed723ddaf6544068b952b4f8abf3c8f6":{
      "scriptId":"u26"},
    "e19d4cc5f24747a48c3576974e868af2":{
      "scriptId":"u27"},
    "69193f78000a4b558ffce7b31d9627b3":{
      "scriptId":"u28"},
    "403879d766dd495aa1806cc1355a1ef7":{
      "scriptId":"u29"},
    "73bdaa58364f4852aec5994d3c4c5400":{
      "scriptId":"u30"},
    "f2bae48798334739b553e6a06ad4bba0":{
      "scriptId":"u31"},
    "6920137443384413bf28945ffe4e18cf":{
      "scriptId":"u32"},
    "9beb1cab0d74478ebd9b6f74d6615705":{
      "scriptId":"u33"},
    "c6e9f87c400748c0b4e1fb5cd1f7a640":{
      "scriptId":"u34"},
    "d0747630621c45048c28bf4a97abbcf8":{
      "scriptId":"u35"},
    "00bb43707d924f61a7e0f72f658d3305":{
      "scriptId":"u36"},
    "004378ddc9cb49ea9766ab90a588d88c":{
      "scriptId":"u37"},
    "718df9e7513e475c8713b75593f6d36e":{
      "scriptId":"u38"},
    "a19c55c59f514eb0a062645ef545a429":{
      "scriptId":"u39"},
    "5755b1b9734b4546937d285f7803a17a":{
      "scriptId":"u40"},
    "06f3c12526d74df4add5e7e497465354":{
      "scriptId":"u41"},
    "3abdcd6e4ce14a53a776dc5d69b736fa":{
      "scriptId":"u42"},
    "9150f91ed89c407087573b8e39d37877":{
      "scriptId":"u43"},
    "3881dd897cd048dfbcfdd0a412eaee12":{
      "scriptId":"u44"}}});