$axure.loadCurrentPage({
  "url":"login_-_verify.html",
  "generationDate":new Date(1470822510207.19),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c135ffb597634c7e899259056292d70c",
    "type":"Axure:Page",
    "name":"Login - Verify",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f1d12d64d171410fb281310ad179260d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":-43},
            "size":{
              "width":469,
              "height":813}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52504cad537b4606882b8f2fa8623e60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":-43},
                "size":{
                  "width":469,
                  "height":813}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/splash/u0.png"}},
{
          "id":"f93edf6064344342b9a49a003914a300",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9FAF5},
            "location":{
              "x":181,
              "y":103},
            "size":{
              "width":295,
              "height":523},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c53b998aef844a78da8960e16f2448c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9FAF5},
                "location":{
                  "x":181,
                  "y":103},
                "size":{
                  "width":295,
                  "height":523},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/splash/u2.png"}},
{
          "id":"c43490046a034d3983d0b4fbb5f69183",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":381},
            "size":{
              "width":214,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4CAF50}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/login/u4_line.png"}},
{
          "id":"c3a25b4c295f4f4cbc18c47bfade56d7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "location":{
              "x":181,
              "y":103},
            "size":{
              "width":295,
              "height":38},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":5,
              "color":{
                "r":94,
                "g":94,
                "b":94,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a1911db10e04ec6a959222ebe27400e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "location":{
                  "x":181,
                  "y":103},
                "size":{
                  "width":295,
                  "height":38},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":5,
                  "color":{
                    "r":94,
                    "g":94,
                    "b":94,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login_-_forget_password/u5.png"}},
{
          "id":"cf44ae3f0361403a8020e29e4ddb72ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "fontSize":"17px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xDDFFFFFF,
              "opacity":0.866666674613953},
            "baseStyle":"6e631585fe0e401a93235178bc877cb7",
            "location":{
              "x":198,
              "y":111},
            "size":{
              "width":89,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e07aa09fa9294afe85f5ea95866e7fdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "fontSize":"17px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xDDFFFFFF,
                  "opacity":0.866666674613953},
                "baseStyle":"6e631585fe0e401a93235178bc877cb7",
                "location":{
                  "x":198,
                  "y":111},
                "size":{
                  "width":89,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b885e68584974338be9620eea8341fdf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Roboto Medium', 'Roboto'",
            "fontSize":"15px",
            "fontWeight":"500",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF8445AD,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFBCE01,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":377,
              "y":405},
            "size":{
              "width":67,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":188,
                "g":188,
                "b":188,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d23ac752fd724cd3b4d807846d7a6fbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Medium', 'Roboto'",
                "fontSize":"15px",
                "fontWeight":"500",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF8445AD,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFBCE01,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":377,
                  "y":405},
                "size":{
                  "width":67,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":188,
                    "g":188,
                    "b":188,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Set New Password in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"set_new_password.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"3102b12ebbbb4259ba26c88efc0fdeaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"13px",
            "horizontalAlignment":"center",
            "baseStyle":"db0f01df1fcf495085ab10f03b87b2cb",
            "location":{
              "x":206,
              "y":281},
            "size":{
              "width":244,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a29d4885663d4ac69485ce79b0149418",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"13px",
                "horizontalAlignment":"center",
                "baseStyle":"db0f01df1fcf495085ab10f03b87b2cb",
                "location":{
                  "x":206,
                  "y":281},
                "size":{
                  "width":244,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"467268caa94b40059073935d8c0d70d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"13px",
            "horizontalAlignment":"center",
            "baseStyle":"db0f01df1fcf495085ab10f03b87b2cb",
            "location":{
              "x":206,
              "y":220},
            "size":{
              "width":244,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b588c213187f4c208b4114c58abcefe2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"13px",
                "horizontalAlignment":"center",
                "baseStyle":"db0f01df1fcf495085ab10f03b87b2cb",
                "location":{
                  "x":206,
                  "y":220},
                "size":{
                  "width":244,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d90c5253b5b447bab1c640e68fde7612",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"17px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF8445AD,
              "opacity":1},
            "baseStyle":"db0f01df1fcf495085ab10f03b87b2cb",
            "location":{
              "x":246,
              "y":180},
            "size":{
              "width":142,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ccbdbd17cb4484c834415b2b460350d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"17px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF8445AD,
                  "opacity":1},
                "baseStyle":"db0f01df1fcf495085ab10f03b87b2cb",
                "location":{
                  "x":246,
                  "y":180},
                "size":{
                  "width":142,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b464fb4f713442da1524f4340e0ddc2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x89000000,
              "opacity":0.537254929542542},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":217,
              "y":356},
            "size":{
              "width":217,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "f1d12d64d171410fb281310ad179260d":{
      "scriptId":"u0"},
    "52504cad537b4606882b8f2fa8623e60":{
      "scriptId":"u1"},
    "f93edf6064344342b9a49a003914a300":{
      "scriptId":"u2"},
    "4c53b998aef844a78da8960e16f2448c":{
      "scriptId":"u3"},
    "c43490046a034d3983d0b4fbb5f69183":{
      "scriptId":"u4"},
    "c3a25b4c295f4f4cbc18c47bfade56d7":{
      "scriptId":"u5"},
    "3a1911db10e04ec6a959222ebe27400e":{
      "scriptId":"u6"},
    "cf44ae3f0361403a8020e29e4ddb72ee":{
      "scriptId":"u7"},
    "e07aa09fa9294afe85f5ea95866e7fdd":{
      "scriptId":"u8"},
    "b885e68584974338be9620eea8341fdf":{
      "scriptId":"u9"},
    "d23ac752fd724cd3b4d807846d7a6fbd":{
      "scriptId":"u10"},
    "3102b12ebbbb4259ba26c88efc0fdeaa":{
      "scriptId":"u11"},
    "a29d4885663d4ac69485ce79b0149418":{
      "scriptId":"u12"},
    "467268caa94b40059073935d8c0d70d4":{
      "scriptId":"u13"},
    "b588c213187f4c208b4114c58abcefe2":{
      "scriptId":"u14"},
    "d90c5253b5b447bab1c640e68fde7612":{
      "scriptId":"u15"},
    "1ccbdbd17cb4484c834415b2b460350d":{
      "scriptId":"u16"},
    "7b464fb4f713442da1524f4340e0ddc2":{
      "scriptId":"u17"}}});