$axure.loadCurrentPage({
  "url":"options.html",
  "generationDate":new Date(1470822510365.63),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"03dc82e67f3747749cde6d05561ed3d0",
    "type":"Axure:Page",
    "name":"Options",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e7a262b522284df4b0918f50c6d532b9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":-43}},
          "adaptiveStyles":{
},
          "masterId":"866c22c904d0473f85c124c9890df389"},
{
          "id":"6c4aaf7796df4c7497ba93add09c0fae",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "location":{
              "x":181,
              "y":103},
            "size":{
              "width":295,
              "height":43},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":5,
              "color":{
                "r":94,
                "g":94,
                "b":94,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8254199a66a44fde931929895163f87f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "location":{
                  "x":181,
                  "y":103},
                "size":{
                  "width":295,
                  "height":43},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":5,
                  "color":{
                    "r":94,
                    "g":94,
                    "b":94,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/options/u5.png"}},
{
          "id":"7c4873ea81d443929c22c6e360d92a89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "fontSize":"17px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xDDFFFFFF,
              "opacity":0.866666674613953},
            "baseStyle":"6e631585fe0e401a93235178bc877cb7",
            "location":{
              "x":220,
              "y":112},
            "size":{
              "width":62,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"915081ce2fe44076b27ca45c02d1ded6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "fontSize":"17px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xDDFFFFFF,
                  "opacity":0.866666674613953},
                "baseStyle":"6e631585fe0e401a93235178bc877cb7",
                "location":{
                  "x":220,
                  "y":112},
                "size":{
                  "width":62,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"137272e97d6e429780c6f15e51f9a5a4",
          "label":"Menu Icon",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "location":{
              "x":181,
              "y":104},
            "size":{
              "width":38,
              "height":33},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cbad76258c840dda97a333391d23602",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "location":{
                  "x":181,
                  "y":104},
                "size":{
                  "width":38,
                  "height":33},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1<br> (If state of (Dynamic Panel) equals Invisible)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["062fbdf4f1f94e2c85c9cffaf602bef5"]}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["062fbdf4f1f94e2c85c9cffaf602bef5"],
                      "panelIndex":0}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set (Dynamic Panel) to visible",
                      "panelsToStates":[{
                          "panelPath":["062fbdf4f1f94e2c85c9cffaf602bef5"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]},
{
                  "description":"Case 2<br> (Else If state of (Dynamic Panel) equals visible)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["062fbdf4f1f94e2c85c9cffaf602bef5"]}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["062fbdf4f1f94e2c85c9cffaf602bef5"],
                      "panelIndex":1}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set (Dynamic Panel) to Invisible",
                      "panelsToStates":[{
                          "panelPath":["062fbdf4f1f94e2c85c9cffaf602bef5"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/options/menu_icon_u9.png"}},
{
          "id":"9bd965a3f3ab4d1faa7b37d72570b227",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF8445AD,
              "opacity":1},
            "location":{
              "x":189,
              "y":225},
            "size":{
              "width":279,
              "height":279}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3acca75db73e444e909a6ef21b413a65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF8445AD,
                  "opacity":1},
                "location":{
                  "x":189,
                  "y":225},
                "size":{
                  "width":279,
                  "height":279}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/splash/u4.png"}},
{
          "id":"062fbdf4f1f94e2c85c9cffaf602bef5",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":181,
              "y":144},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"e440e16fae354c3f96bd68e67ac0e423",
              "label":"Invisible",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"8dc78ea2f5b942e8bd3ab4cb897c8d24",
              "label":"visible",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c3cec399b4534688971b916124ed7cfb",
                  "label":"",
                  "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF8445AD},
                    "size":{
                      "width":229,
                      "height":482}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3cf4bed0cf9b4d119115fae37f0296b8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF8445AD},
                        "size":{
                          "width":229,
                          "height":482}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/options/u14.png"}},
{
                  "id":"b022fca8480c4c5db413d86463fc9763",
                  "label":"",
                  "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "verticalAlignment":"middle",
                    "baseStyle":"f434fc19aed0486cb28659f79fc585db",
                    "lineSpacing":"20px",
                    "location":{
                      "x":17,
                      "y":255},
                    "size":{
                      "width":74,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b60d30fe1c6b4e6f83a22a8bf22145fd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "verticalAlignment":"middle",
                        "baseStyle":"f434fc19aed0486cb28659f79fc585db",
                        "lineSpacing":"20px",
                        "location":{
                          "x":17,
                          "y":255},
                        "size":{
                          "width":74,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4c690777de97411cb1c9e247f69d5464",
                  "label":"",
                  "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c1c60ce7633041de9dc7ebc43150c375",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/options/u18.png"}},
{
                  "id":"bc459d44eee143f099f0ae7f7ffd5088",
                  "label":"",
                  "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":61,
                      "y":12},
                    "size":{
                      "width":168,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8c977abd7fa4424985bb6371c0fa9127",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":61,
                          "y":12},
                        "size":{
                          "width":168,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"55e994ec0acb48048b6f5ad62d10affd",
                  "label":"",
                  "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "location":{
                      "x":12,
                      "y":12},
                    "size":{
                      "width":39,
                      "height":39}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b8dc568872e14082bfd0dbfeebc3cd0e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "location":{
                          "x":12,
                          "y":12},
                        "size":{
                          "width":39,
                          "height":39}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/options/u22.png"}},
{
                  "id":"a32ce7becbe94e49afdab1374ad53437",
                  "label":"",
                  "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "verticalAlignment":"bottom",
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "location":{
                      "x":0,
                      "y":62},
                    "size":{
                      "width":229,
                      "height":63},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f44cfea2592444508f7b6c5236f87b2b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "verticalAlignment":"bottom",
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "location":{
                          "x":0,
                          "y":62},
                        "size":{
                          "width":229,
                          "height":63},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/options/u24.png"}},
{
                  "id":"22e0608ef10d49aa9b909483d5758ba4",
                  "label":"",
                  "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":57,
                      "y":75},
                    "size":{
                      "width":162,
                      "height":38}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"91751763fd8e455ead17a53852cc7b71",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":57,
                          "y":75},
                        "size":{
                          "width":162,
                          "height":38}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2e300c5b6f3143839a0d27a7d809f96e",
                  "label":"",
                  "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "verticalAlignment":"bottom",
                    "location":{
                      "x":12,
                      "y":75},
                    "size":{
                      "width":35,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8feadb0e737b4111be2abfd5b2d750f5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "verticalAlignment":"bottom",
                        "location":{
                          "x":12,
                          "y":75},
                        "size":{
                          "width":35,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/options/u28.png"}},
{
                  "id":"3fe2df29178d4f5993ddb297e1956f4e",
                  "label":"",
                  "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "location":{
                      "x":0,
                      "y":125},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b4e366025cac47a59d02334c0fd59c89",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "location":{
                          "x":0,
                          "y":125},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/options/u18.png"}},
{
                  "id":"7d71520b553c4179a00ffe6dfc5aa8de",
                  "label":"",
                  "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":61,
                      "y":137},
                    "size":{
                      "width":158,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"400984ffa3b84facb1bed31e21708887",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":61,
                          "y":137},
                        "size":{
                          "width":158,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"055f603e30404bc89c1c57ea8c6ad02c",
                  "label":"",
                  "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":12,
                      "y":137},
                    "size":{
                      "width":39,
                      "height":39}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0bec90918b9f45dda73b8bead08311b1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":12,
                          "y":137},
                        "size":{
                          "width":39,
                          "height":39}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/options/u34.png"}},
{
                  "id":"4a6a9e893b6741148ed3292bdf16be43",
                  "label":"",
                  "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x19FFFFFF},
                    "location":{
                      "x":0,
                      "y":187},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b0d42fbea7da4bd682907b6f90f327ef",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x19FFFFFF},
                        "location":{
                          "x":0,
                          "y":187},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/options/u18.png"}},
{
                  "id":"284fe74ec2454c759805503ed1c0509f",
                  "label":"",
                  "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":61,
                      "y":199},
                    "size":{
                      "width":158,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"702d67a7c5b648fabdf851d040f1b8c5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":61,
                          "y":199},
                        "size":{
                          "width":158,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"80e7b5d47a36428a828c67547e3fac94",
                  "label":"",
                  "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":12,
                      "y":199},
                    "size":{
                      "width":39,
                      "height":39}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3af01becf7d74f98b9f41e810d3b80aa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":12,
                          "y":199},
                        "size":{
                          "width":39,
                          "height":39}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/options/u40.png"}},
{
                  "id":"2954e8690c524df0ac6ecf346d3fa31d",
                  "label":"",
                  "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                  "panelIndex":1,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":229,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c2d42d3353a14e8da2cd64c63a8e6f75",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":229,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Options - Profile in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"options_-_profile.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/options/u42.png"}},
{
                  "id":"ecff3f3508c747e3a85bbdaba0dda496",
                  "label":"",
                  "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                  "panelIndex":1,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":62},
                    "size":{
                      "width":229,
                      "height":64},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5bf4bc6ebe5c4e2db10e222ec52b77cd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":62},
                        "size":{
                          "width":229,
                          "height":64},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Options - News Updates in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"options_-_news_updates.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"06282d144f5e4f768d8fbda7909f3dba",
                  "label":"",
                  "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                  "panelIndex":1,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":1,
                      "y":125},
                    "size":{
                      "width":229,
                      "height":64},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d36dc318535d498191aec7b63c28528c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"062fbdf4f1f94e2c85c9cffaf602bef5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":1,
                          "y":125},
                        "size":{
                          "width":229,
                          "height":64},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Options - Change Password in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"options_-_change_password.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "866c22c904d0473f85c124c9890df389":{
      "packageId":"866c22c904d0473f85c124c9890df389",
      "type":"Axure:Master",
      "name":"frame-plain",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"786c97fb188e44ee8e7e5f4a26a54118",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":90,
                "y":-43},
              "size":{
                "width":469,
                "height":813}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cff2973955f54ebe8c64abe06b548aee",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":90,
                    "y":-43},
                  "size":{
                    "width":469,
                    "height":813}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/splash/u0.png"}},
{
            "id":"67400802aab24ac38de05902cd4eb835",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF9FAF5},
              "location":{
                "x":181,
                "y":103},
              "size":{
                "width":295,
                "height":523},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eea47f19de544c8b962b75de32a1caf9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF9FAF5},
                  "location":{
                    "x":181,
                    "y":103},
                  "size":{
                    "width":295,
                    "height":523},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/options/u3.png"}}]}}},
  "objectPaths":{
    "e7a262b522284df4b0918f50c6d532b9":{
      "scriptId":"u0",
      "786c97fb188e44ee8e7e5f4a26a54118":{
        "scriptId":"u1"},
      "cff2973955f54ebe8c64abe06b548aee":{
        "scriptId":"u2"},
      "67400802aab24ac38de05902cd4eb835":{
        "scriptId":"u3"},
      "eea47f19de544c8b962b75de32a1caf9":{
        "scriptId":"u4"}},
    "6c4aaf7796df4c7497ba93add09c0fae":{
      "scriptId":"u5"},
    "8254199a66a44fde931929895163f87f":{
      "scriptId":"u6"},
    "7c4873ea81d443929c22c6e360d92a89":{
      "scriptId":"u7"},
    "915081ce2fe44076b27ca45c02d1ded6":{
      "scriptId":"u8"},
    "137272e97d6e429780c6f15e51f9a5a4":{
      "scriptId":"u9"},
    "4cbad76258c840dda97a333391d23602":{
      "scriptId":"u10"},
    "9bd965a3f3ab4d1faa7b37d72570b227":{
      "scriptId":"u11"},
    "3acca75db73e444e909a6ef21b413a65":{
      "scriptId":"u12"},
    "062fbdf4f1f94e2c85c9cffaf602bef5":{
      "scriptId":"u13"},
    "c3cec399b4534688971b916124ed7cfb":{
      "scriptId":"u14"},
    "3cf4bed0cf9b4d119115fae37f0296b8":{
      "scriptId":"u15"},
    "b022fca8480c4c5db413d86463fc9763":{
      "scriptId":"u16"},
    "b60d30fe1c6b4e6f83a22a8bf22145fd":{
      "scriptId":"u17"},
    "4c690777de97411cb1c9e247f69d5464":{
      "scriptId":"u18"},
    "c1c60ce7633041de9dc7ebc43150c375":{
      "scriptId":"u19"},
    "bc459d44eee143f099f0ae7f7ffd5088":{
      "scriptId":"u20"},
    "8c977abd7fa4424985bb6371c0fa9127":{
      "scriptId":"u21"},
    "55e994ec0acb48048b6f5ad62d10affd":{
      "scriptId":"u22"},
    "b8dc568872e14082bfd0dbfeebc3cd0e":{
      "scriptId":"u23"},
    "a32ce7becbe94e49afdab1374ad53437":{
      "scriptId":"u24"},
    "f44cfea2592444508f7b6c5236f87b2b":{
      "scriptId":"u25"},
    "22e0608ef10d49aa9b909483d5758ba4":{
      "scriptId":"u26"},
    "91751763fd8e455ead17a53852cc7b71":{
      "scriptId":"u27"},
    "2e300c5b6f3143839a0d27a7d809f96e":{
      "scriptId":"u28"},
    "8feadb0e737b4111be2abfd5b2d750f5":{
      "scriptId":"u29"},
    "3fe2df29178d4f5993ddb297e1956f4e":{
      "scriptId":"u30"},
    "b4e366025cac47a59d02334c0fd59c89":{
      "scriptId":"u31"},
    "7d71520b553c4179a00ffe6dfc5aa8de":{
      "scriptId":"u32"},
    "400984ffa3b84facb1bed31e21708887":{
      "scriptId":"u33"},
    "055f603e30404bc89c1c57ea8c6ad02c":{
      "scriptId":"u34"},
    "0bec90918b9f45dda73b8bead08311b1":{
      "scriptId":"u35"},
    "4a6a9e893b6741148ed3292bdf16be43":{
      "scriptId":"u36"},
    "b0d42fbea7da4bd682907b6f90f327ef":{
      "scriptId":"u37"},
    "284fe74ec2454c759805503ed1c0509f":{
      "scriptId":"u38"},
    "702d67a7c5b648fabdf851d040f1b8c5":{
      "scriptId":"u39"},
    "80e7b5d47a36428a828c67547e3fac94":{
      "scriptId":"u40"},
    "3af01becf7d74f98b9f41e810d3b80aa":{
      "scriptId":"u41"},
    "2954e8690c524df0ac6ecf346d3fa31d":{
      "scriptId":"u42"},
    "c2d42d3353a14e8da2cd64c63a8e6f75":{
      "scriptId":"u43"},
    "ecff3f3508c747e3a85bbdaba0dda496":{
      "scriptId":"u44"},
    "5bf4bc6ebe5c4e2db10e222ec52b77cd":{
      "scriptId":"u45"},
    "06282d144f5e4f768d8fbda7909f3dba":{
      "scriptId":"u46"},
    "d36dc318535d498191aec7b63c28528c":{
      "scriptId":"u47"}}});