$axure.loadCurrentPage({
  "url":"dashboard.html",
  "generationDate":new Date(1472619279875.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"81613470e65642a787a0252c05a2c94c",
    "type":"Axure:Page",
    "name":"Dashboard",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6ca76bd3a37646f6afdb1eae79ca0167",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"e163cbb4cef54461ad56955f368f2e96"},
{
          "id":"5f9cb2219b124226b2335a8c2aff1629",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Regular', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":294,
              "y":72},
            "size":{
              "width":119,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20b0fe2e26c74df59ee490977594359c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Regular', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":294,
                  "y":72},
                "size":{
                  "width":119,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a198b3c327a04a1fbbc5c49344fc24ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1996C7,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":54},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1190a93751b44c5826c9bcc7069c7ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1996C7,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":54},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Dashboard in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"dashboard.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"07e42ed8722847b78b597d77cd73a30c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":95},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab7434716f1b44ea84ec10c8e068f037",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":95},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Manage Keyword in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"manage_keyword.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"3df09826e82f460ea4a69626e5431b9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":136},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f594d2cd595e432e8fb31840bba2e5f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":136},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Security in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"security.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"65f16792e1ed48bd9e6c8647bd2ed24a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":177},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b80a8217777419f95fd613a08a1d35e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":177},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Security in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"security.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"8287cff38b114c979e21b2dd246253d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":130},
            "size":{
              "width":233,
              "height":78},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4CAF50},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8f7681b535d493fbf05d9cea17c66c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":130},
                "size":{
                  "width":233,
                  "height":78},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4CAF50},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u21.png"}},
{
          "id":"dc4ff32739ab4e72ba6cfd3b0083dd03",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "verticalAlignment":"middle",
            "location":{
              "x":388,
              "y":157},
            "size":{
              "width":95,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4609954aca8c4a70a5de8e594471be8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "location":{
                  "x":388,
                  "y":157},
                "size":{
                  "width":95,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23f6155d93424ccbb3a15c93ea4e69de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF1996C7},
            "location":{
              "x":294,
              "y":130},
            "size":{
              "width":74,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"918646b2bfa54f4eac42a774608b1aab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1996C7},
                "location":{
                  "x":294,
                  "y":130},
                "size":{
                  "width":74,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u25.png"}},
{
          "id":"60a69f672cb24f4e99ad55dec26f9c73",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":311,
              "y":148},
            "size":{
              "width":21,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"546e044bfd734b43bb3d83194e69f7d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":311,
                  "y":148},
                "size":{
                  "width":21,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb3dbda1aea740c79368d3e6560db52c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":557,
              "y":130},
            "size":{
              "width":233,
              "height":78},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4CAF50},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1dcb406fd34a48029da9233af858678f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":557,
                  "y":130},
                "size":{
                  "width":233,
                  "height":78},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4CAF50},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u21.png"}},
{
          "id":"b1388153b8c745c081e42452638fe5c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "verticalAlignment":"middle",
            "location":{
              "x":651,
              "y":157},
            "size":{
              "width":56,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f97eded2ee9647738d0dabf21bcc01e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "location":{
                  "x":651,
                  "y":157},
                "size":{
                  "width":56,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9bf1763a86e345c9aa61df3766eab625",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF1996C7},
            "location":{
              "x":557,
              "y":130},
            "size":{
              "width":74,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05239f107a19462ba4ae23d193350d5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1996C7},
                "location":{
                  "x":557,
                  "y":130},
                "size":{
                  "width":74,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u25.png"}},
{
          "id":"4fd63d12d5004b618f68a19c41c63744",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":574,
              "y":148},
            "size":{
              "width":41,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdaa5a43427a4a2093f2abf94d1883f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":574,
                  "y":148},
                "size":{
                  "width":41,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45c7f974e759498ab65c3563a94fbdf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":827,
              "y":129},
            "size":{
              "width":233,
              "height":78},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4CAF50},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6676dece9dd84a899f714e1dea56ef46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":827,
                  "y":129},
                "size":{
                  "width":233,
                  "height":78},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4CAF50},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u21.png"}},
{
          "id":"b5ba8a3d1fc54eeca767ccd36947f2ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "verticalAlignment":"middle",
            "location":{
              "x":921,
              "y":144},
            "size":{
              "width":96,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ef166002a9d4acdb7640d0499e147f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "location":{
                  "x":921,
                  "y":144},
                "size":{
                  "width":96,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe0ceeaff9984c7bb9651130ff74456d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF1996C7},
            "location":{
              "x":827,
              "y":129},
            "size":{
              "width":74,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"330d1f3cba5b410bacfd8b8950fb7767",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1996C7},
                "location":{
                  "x":827,
                  "y":129},
                "size":{
                  "width":74,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u25.png"}},
{
          "id":"158a62a2c1cb426d8ffbf275ab811a31",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":836,
              "y":157},
            "size":{
              "width":56,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b033f53f26140b4b2354fae668bc03b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":836,
                  "y":157},
                "size":{
                  "width":56,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5fbbb4481eaf4f92a2452e179c6cddc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1087,
              "y":130},
            "size":{
              "width":233,
              "height":78},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4CAF50},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5475f97ffdba4809b03b23f065bf6192",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1087,
                  "y":130},
                "size":{
                  "width":233,
                  "height":78},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4CAF50},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u21.png"}},
{
          "id":"c4dc8c2201d4413d8948b2fff6ac92f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "verticalAlignment":"middle",
            "location":{
              "x":1167,
              "y":158},
            "size":{
              "width":145,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50f28479d9e94951b2a23e5f5b8cfdeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "location":{
                  "x":1167,
                  "y":158},
                "size":{
                  "width":145,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"51e061c93be444709940c82b21f4e40b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF1996C7},
            "location":{
              "x":1087,
              "y":130},
            "size":{
              "width":74,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"450cf6d020a14779ad47b1c256c5ee0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1996C7},
                "location":{
                  "x":1087,
                  "y":130},
                "size":{
                  "width":74,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u25.png"}},
{
          "id":"9f387fd90e164ef0ab1f7ec3660f782e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":219},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98ff040188af40039522b3d989c785ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":219},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Security in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"security.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"e932a0c88a1945afaf8014e5e33e61a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":261},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"115e6146d37447ebb0e9b0a7af139250",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":261},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Security in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"security.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"8f9e92266979493e85cff13907cc6df3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":303},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7a3c7128a4847cb8b130d17fb6e8d1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":303},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Security in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"security.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"9ce3f3c0b46c4298ae2a19bd9d32b3e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":345},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63f87c9549314c1dbd962ba61e32ba7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":345},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Users in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"users.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"b789e9d7f9e44e7b882fe11ec2bfaca6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1096,
              "y":158},
            "size":{
              "width":56,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7115dd423c284713a2a8f8caff2f0c71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1096,
                  "y":158},
                "size":{
                  "width":56,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b8e0db9e8b047a8b9f1e9dd0d91b868",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":330},
            "size":{
              "width":1072,
              "height":410}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f749872901f4c67a6f0fbef40047fbd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":268,
                  "y":0},
                "size":{
                  "width":268,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0723b0d41cc44aef94ec22da62f1ec67",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":268,
                      "y":0},
                    "size":{
                      "width":268,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/dashboard/u62.png"}},
{
              "id":"87178f33ef0f41ebbf1ce15e2a65a35d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":268,
                  "y":20},
                "size":{
                  "width":268,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e3c1f411418c43928b7264b5d5314b87",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":268,
                      "y":20},
                    "size":{
                      "width":268,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/dashboard/u70.png"}},
{
              "id":"806002c117c14e3d99cb32e6048e6bd4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":268,
                  "y":50},
                "size":{
                  "width":268,
                  "height":360}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"612009462d4140a599ed307f48eff13d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":268,
                      "y":50},
                    "size":{
                      "width":268,
                      "height":360}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/dashboard/u78.png"}},
{
              "id":"452892fc1a1e4dab98fd86cecc8c5ac5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":536,
                  "y":0},
                "size":{
                  "width":268,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b712dd977e4b40a1bfd0fc592385f631",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":536,
                      "y":0},
                    "size":{
                      "width":268,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/dashboard/u62.png"}},
{
              "id":"3467fde8fd6e43c2be83c25bcbe7c4a5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":536,
                  "y":20},
                "size":{
                  "width":268,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"172f87299dbc401890dd0d6ba41f73db",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":536,
                      "y":20},
                    "size":{
                      "width":268,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/dashboard/u70.png"}},
{
              "id":"29e36efed0b34af7b3cbfb6e1892f8d1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":536,
                  "y":50},
                "size":{
                  "width":268,
                  "height":360}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bd6dae7e9bb845c6829b963ae1811570",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":536,
                      "y":50},
                    "size":{
                      "width":268,
                      "height":360}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/dashboard/u78.png"}},
{
              "id":"7e0a1a2898ec4504927b033078677251",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":804,
                  "y":0},
                "size":{
                  "width":268,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e817ec5963fd48e59b07f6a08ca80237",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":804,
                      "y":0},
                    "size":{
                      "width":268,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/dashboard/u68.png"}},
{
              "id":"48c58c28766547bead3c8397e4301a53",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":804,
                  "y":20},
                "size":{
                  "width":268,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f0eb63b5cac74364b047cab7505ce1d9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":804,
                      "y":20},
                    "size":{
                      "width":268,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/dashboard/u76.png"}},
{
              "id":"99ebdb259cce493287f5cf7eaf248e1d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":804,
                  "y":50},
                "size":{
                  "width":268,
                  "height":360}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"89d94db2f1ce41e6973506826dc81fee",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":804,
                      "y":50},
                    "size":{
                      "width":268,
                      "height":360}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/dashboard/u84.png"}},
{
              "id":"15f25932a875480ca5c450219134e7dc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":268,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cf0d45a308184943ac28907662819eb2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":268,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/dashboard/u62.png"}},
{
              "id":"ad49cd6abb95414a8bd32a947ee74c10",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":20},
                "size":{
                  "width":268,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2f01e51cb01642d48bd3a5ba0bd1aa12",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":20},
                    "size":{
                      "width":268,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/dashboard/u70.png"}},
{
              "id":"709ec4dcade54f67b046f5f792e99862",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":268,
                  "height":360}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e5e29c70fcd847cbabded9c2ebc5dd90",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":50},
                    "size":{
                      "width":268,
                      "height":360}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/dashboard/u78.png"}}]},
{
          "id":"0ad9af0f86544d89b0679a71985f839a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Regular', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":294,
              "y":275},
            "size":{
              "width":104,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fc2206d0fe04d93b1ef0a7fafb529d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Regular', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":294,
                  "y":275},
                "size":{
                  "width":104,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "e163cbb4cef54461ad56955f368f2e96":{
      "packageId":"e163cbb4cef54461ad56955f368f2e96",
      "type":"Axure:Master",
      "name":"main",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1affd31496854a90aaf55cb21b7c1027",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF9F9F9},
              "size":{
                "width":1366,
                "height":768}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6b795c4f50714ccc8e66f16ce98c2618",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF9F9F9},
                  "size":{
                    "width":1366,
                    "height":768}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u1.png"}},
{
            "id":"cee52dc11a8744b0a43052d502487fd5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF1996C7},
              "size":{
                "width":1366,
                "height":50},
              "borderWidth":"-1",
              "outerShadow":{
                "on":true,
                "offsetX":0,
                "offsetY":1,
                "blurRadius":5,
                "color":{
                  "r":0,
                  "g":0,
                  "b":0,
                  "a":0.349019607843137}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bde88dba9c1a4e2988a327f1c196765c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF1996C7},
                  "size":{
                    "width":1366,
                    "height":50},
                  "borderWidth":"-1",
                  "outerShadow":{
                    "on":true,
                    "offsetX":0,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.349019607843137}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u3.png"}},
{
            "id":"56fbb49b18bd46129591d114da88345e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF0E5570},
              "location":{
                "x":0,
                "y":50},
              "size":{
                "width":1366,
                "height":4},
              "borderWidth":"-1",
              "outerShadow":{
                "on":true,
                "offsetX":0,
                "offsetY":1,
                "blurRadius":5,
                "color":{
                  "r":0,
                  "g":0,
                  "b":0,
                  "a":0.349019607843137}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b9154b46c7af49f6b3c8fa13b5e2aa9c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0E5570},
                  "location":{
                    "x":0,
                    "y":50},
                  "size":{
                    "width":1366,
                    "height":4},
                  "borderWidth":"-1",
                  "outerShadow":{
                    "on":true,
                    "offsetX":0,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.349019607843137}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u5.png"}},
{
            "id":"8e7b142cf5d5486cbc949c1ae82f56d1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF212121},
              "location":{
                "x":0,
                "y":54},
              "size":{
                "width":250,
                "height":714},
              "borderWidth":"-1",
              "outerShadow":{
                "on":true,
                "offsetX":2,
                "offsetY":0,
                "blurRadius":5,
                "color":{
                  "r":0,
                  "g":0,
                  "b":0,
                  "a":0.349019607843137}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59e38fb539e04bb29cde628389cf5bd8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF212121},
                  "location":{
                    "x":0,
                    "y":54},
                  "size":{
                    "width":250,
                    "height":714},
                  "borderWidth":"-1",
                  "outerShadow":{
                    "on":true,
                    "offsetX":2,
                    "offsetY":0,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.349019607843137}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u7.png"}},
{
            "id":"dcdfff1ef73440ecb729883ed1488cee",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"28px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":31,
                "y":7},
              "size":{
                "width":192,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ee24b8d3672d4a26a4e0d5b9d8a0528a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"28px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":31,
                    "y":7},
                  "size":{
                    "width":192,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "6ca76bd3a37646f6afdb1eae79ca0167":{
      "scriptId":"u0",
      "1affd31496854a90aaf55cb21b7c1027":{
        "scriptId":"u1"},
      "6b795c4f50714ccc8e66f16ce98c2618":{
        "scriptId":"u2"},
      "cee52dc11a8744b0a43052d502487fd5":{
        "scriptId":"u3"},
      "bde88dba9c1a4e2988a327f1c196765c":{
        "scriptId":"u4"},
      "56fbb49b18bd46129591d114da88345e":{
        "scriptId":"u5"},
      "b9154b46c7af49f6b3c8fa13b5e2aa9c":{
        "scriptId":"u6"},
      "8e7b142cf5d5486cbc949c1ae82f56d1":{
        "scriptId":"u7"},
      "59e38fb539e04bb29cde628389cf5bd8":{
        "scriptId":"u8"},
      "dcdfff1ef73440ecb729883ed1488cee":{
        "scriptId":"u9"},
      "ee24b8d3672d4a26a4e0d5b9d8a0528a":{
        "scriptId":"u10"}},
    "5f9cb2219b124226b2335a8c2aff1629":{
      "scriptId":"u11"},
    "20b0fe2e26c74df59ee490977594359c":{
      "scriptId":"u12"},
    "a198b3c327a04a1fbbc5c49344fc24ec":{
      "scriptId":"u13"},
    "a1190a93751b44c5826c9bcc7069c7ab":{
      "scriptId":"u14"},
    "07e42ed8722847b78b597d77cd73a30c":{
      "scriptId":"u15"},
    "ab7434716f1b44ea84ec10c8e068f037":{
      "scriptId":"u16"},
    "3df09826e82f460ea4a69626e5431b9b":{
      "scriptId":"u17"},
    "f594d2cd595e432e8fb31840bba2e5f1":{
      "scriptId":"u18"},
    "65f16792e1ed48bd9e6c8647bd2ed24a":{
      "scriptId":"u19"},
    "5b80a8217777419f95fd613a08a1d35e":{
      "scriptId":"u20"},
    "8287cff38b114c979e21b2dd246253d7":{
      "scriptId":"u21"},
    "d8f7681b535d493fbf05d9cea17c66c9":{
      "scriptId":"u22"},
    "dc4ff32739ab4e72ba6cfd3b0083dd03":{
      "scriptId":"u23"},
    "4609954aca8c4a70a5de8e594471be8b":{
      "scriptId":"u24"},
    "23f6155d93424ccbb3a15c93ea4e69de":{
      "scriptId":"u25"},
    "918646b2bfa54f4eac42a774608b1aab":{
      "scriptId":"u26"},
    "60a69f672cb24f4e99ad55dec26f9c73":{
      "scriptId":"u27"},
    "546e044bfd734b43bb3d83194e69f7d7":{
      "scriptId":"u28"},
    "bb3dbda1aea740c79368d3e6560db52c":{
      "scriptId":"u29"},
    "1dcb406fd34a48029da9233af858678f":{
      "scriptId":"u30"},
    "b1388153b8c745c081e42452638fe5c1":{
      "scriptId":"u31"},
    "f97eded2ee9647738d0dabf21bcc01e8":{
      "scriptId":"u32"},
    "9bf1763a86e345c9aa61df3766eab625":{
      "scriptId":"u33"},
    "05239f107a19462ba4ae23d193350d5b":{
      "scriptId":"u34"},
    "4fd63d12d5004b618f68a19c41c63744":{
      "scriptId":"u35"},
    "bdaa5a43427a4a2093f2abf94d1883f6":{
      "scriptId":"u36"},
    "45c7f974e759498ab65c3563a94fbdf2":{
      "scriptId":"u37"},
    "6676dece9dd84a899f714e1dea56ef46":{
      "scriptId":"u38"},
    "b5ba8a3d1fc54eeca767ccd36947f2ab":{
      "scriptId":"u39"},
    "8ef166002a9d4acdb7640d0499e147f3":{
      "scriptId":"u40"},
    "fe0ceeaff9984c7bb9651130ff74456d":{
      "scriptId":"u41"},
    "330d1f3cba5b410bacfd8b8950fb7767":{
      "scriptId":"u42"},
    "158a62a2c1cb426d8ffbf275ab811a31":{
      "scriptId":"u43"},
    "0b033f53f26140b4b2354fae668bc03b":{
      "scriptId":"u44"},
    "5fbbb4481eaf4f92a2452e179c6cddc1":{
      "scriptId":"u45"},
    "5475f97ffdba4809b03b23f065bf6192":{
      "scriptId":"u46"},
    "c4dc8c2201d4413d8948b2fff6ac92f2":{
      "scriptId":"u47"},
    "50f28479d9e94951b2a23e5f5b8cfdeb":{
      "scriptId":"u48"},
    "51e061c93be444709940c82b21f4e40b":{
      "scriptId":"u49"},
    "450cf6d020a14779ad47b1c256c5ee0c":{
      "scriptId":"u50"},
    "9f387fd90e164ef0ab1f7ec3660f782e":{
      "scriptId":"u51"},
    "98ff040188af40039522b3d989c785ec":{
      "scriptId":"u52"},
    "e932a0c88a1945afaf8014e5e33e61a4":{
      "scriptId":"u53"},
    "115e6146d37447ebb0e9b0a7af139250":{
      "scriptId":"u54"},
    "8f9e92266979493e85cff13907cc6df3":{
      "scriptId":"u55"},
    "c7a3c7128a4847cb8b130d17fb6e8d1e":{
      "scriptId":"u56"},
    "9ce3f3c0b46c4298ae2a19bd9d32b3e8":{
      "scriptId":"u57"},
    "63f87c9549314c1dbd962ba61e32ba7a":{
      "scriptId":"u58"},
    "b789e9d7f9e44e7b882fe11ec2bfaca6":{
      "scriptId":"u59"},
    "7115dd423c284713a2a8f8caff2f0c71":{
      "scriptId":"u60"},
    "5b8e0db9e8b047a8b9f1e9dd0d91b868":{
      "scriptId":"u61"},
    "15f25932a875480ca5c450219134e7dc":{
      "scriptId":"u62"},
    "cf0d45a308184943ac28907662819eb2":{
      "scriptId":"u63"},
    "8f749872901f4c67a6f0fbef40047fbd":{
      "scriptId":"u64"},
    "0723b0d41cc44aef94ec22da62f1ec67":{
      "scriptId":"u65"},
    "452892fc1a1e4dab98fd86cecc8c5ac5":{
      "scriptId":"u66"},
    "b712dd977e4b40a1bfd0fc592385f631":{
      "scriptId":"u67"},
    "7e0a1a2898ec4504927b033078677251":{
      "scriptId":"u68"},
    "e817ec5963fd48e59b07f6a08ca80237":{
      "scriptId":"u69"},
    "ad49cd6abb95414a8bd32a947ee74c10":{
      "scriptId":"u70"},
    "2f01e51cb01642d48bd3a5ba0bd1aa12":{
      "scriptId":"u71"},
    "87178f33ef0f41ebbf1ce15e2a65a35d":{
      "scriptId":"u72"},
    "e3c1f411418c43928b7264b5d5314b87":{
      "scriptId":"u73"},
    "3467fde8fd6e43c2be83c25bcbe7c4a5":{
      "scriptId":"u74"},
    "172f87299dbc401890dd0d6ba41f73db":{
      "scriptId":"u75"},
    "48c58c28766547bead3c8397e4301a53":{
      "scriptId":"u76"},
    "f0eb63b5cac74364b047cab7505ce1d9":{
      "scriptId":"u77"},
    "709ec4dcade54f67b046f5f792e99862":{
      "scriptId":"u78"},
    "e5e29c70fcd847cbabded9c2ebc5dd90":{
      "scriptId":"u79"},
    "806002c117c14e3d99cb32e6048e6bd4":{
      "scriptId":"u80"},
    "612009462d4140a599ed307f48eff13d":{
      "scriptId":"u81"},
    "29e36efed0b34af7b3cbfb6e1892f8d1":{
      "scriptId":"u82"},
    "bd6dae7e9bb845c6829b963ae1811570":{
      "scriptId":"u83"},
    "99ebdb259cce493287f5cf7eaf248e1d":{
      "scriptId":"u84"},
    "89d94db2f1ce41e6973506826dc81fee":{
      "scriptId":"u85"},
    "0ad9af0f86544d89b0679a71985f839a":{
      "scriptId":"u86"},
    "0fc2206d0fe04d93b1ef0a7fafb529d3":{
      "scriptId":"u87"}}});