$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1478751333745.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a6fed97c31104bd88d26a906afe97388",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6ca76bd3a37646f6afdb1eae79ca0167",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"e163cbb4cef54461ad56955f368f2e96"},
{
          "id":"5f9cb2219b124226b2335a8c2aff1629",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Regular', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":294,
              "y":72},
            "size":{
              "width":101,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20b0fe2e26c74df59ee490977594359c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Regular', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":294,
                  "y":72},
                "size":{
                  "width":101,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4392ad38465743e9b303dbd380d19b4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1996C7,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":54},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2644655afe94273871a84092116f92f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1996C7,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":54},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u37.png"}},
{
          "id":"2ee13707ff0849878812458f5e9dc479",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF212121},
            "location":{
              "x":0,
              "y":95},
            "size":{
              "width":250,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2060860d7344dd0b77bb37bdc6f498d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF212121},
                "location":{
                  "x":0,
                  "y":95},
                "size":{
                  "width":250,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Create Request in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"create_request.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u37.png"}},
{
          "id":"fac55c7b7fcf4108a132986a10fb0f06",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":293,
              "y":142},
            "size":{
              "width":1057,
              "height":588},
            "borderWidth":"-1",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":0,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53203faadd1b4a97b7d74f48e3fee9ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":293,
                  "y":142},
                "size":{
                  "width":1057,
                  "height":588},
                "borderWidth":"-1",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":0,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u19.png"}},
{
          "id":"d985813d6da14de580d0bd3715008cc6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1996C7},
            "location":{
              "x":293,
              "y":142},
            "size":{
              "width":1057,
              "height":35},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3faa06ebbb2a478aaebba24628d4accf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1996C7},
                "location":{
                  "x":293,
                  "y":142},
                "size":{
                  "width":1057,
                  "height":35},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u21.png"}},
{
          "id":"e00d00ba9a8f44cfa4f89056f4b7817b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":567,
              "y":242},
            "size":{
              "width":120,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1640b83f076347db968d09cfa0d8b1bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":567,
                  "y":242},
                "size":{
                  "width":120,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1c49d839a064ced836e243159f9c60d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":567,
              "y":203},
            "size":{
              "width":120,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d810a9edc1f24b2e9f1744a364dbe828",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":567,
                  "y":203},
                "size":{
                  "width":120,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e29cb7db2be94848bfcdcb57452224ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":567,
              "y":319},
            "size":{
              "width":120,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7571390ff39f484faee67bd1e963ca4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":567,
                  "y":319},
                "size":{
                  "width":120,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59ab8a0faf6447aa828ec00810cbb1ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":567,
              "y":280},
            "size":{
              "width":120,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9148cdeba524467928b7acc019a388f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":567,
                  "y":280},
                "size":{
                  "width":120,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e600304e934048928d0f3cfc9943e785",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":567,
              "y":396},
            "size":{
              "width":120,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a124a7c60eea4e88896f03a0bced1699",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":567,
                  "y":396},
                "size":{
                  "width":120,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2569ab03fd9d48a0a60dfccfca6de872",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":567,
              "y":357},
            "size":{
              "width":120,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a275ffcf73894ed9a7010148c31337ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":567,
                  "y":357},
                "size":{
                  "width":120,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f24bd7fa6ff44fabb2dd62236432d2ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":567,
              "y":473},
            "size":{
              "width":120,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb25aad5eb10475f9758560d0ac30926",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":567,
                  "y":473},
                "size":{
                  "width":120,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a13ef5f512f46bb87b24598a182f181",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":567,
              "y":434},
            "size":{
              "width":120,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf04e1b78d244121a6aeb395b1f1594a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":567,
                  "y":434},
                "size":{
                  "width":120,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2923003e7a704601a0f3584691b70480",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":567,
              "y":550},
            "size":{
              "width":120,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c222949f927c4224b959bc5dc7aaa06b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":567,
                  "y":550},
                "size":{
                  "width":120,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e75ca8b7160495cb2223faca7229ea6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":567,
              "y":511},
            "size":{
              "width":120,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"037b42e1f326498ba46f24f3ff657b9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":567,
                  "y":511},
                "size":{
                  "width":120,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5fc3568350fd4cbebcf6e9f21e888178",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":695,
              "y":244},
            "size":{
              "width":120,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3adc04ecd098492a9f1bbbe7bfd1eb7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":695,
                  "y":244},
                "size":{
                  "width":120,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff3cfcd607c640e5ba609824eceb836d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":695,
              "y":205},
            "size":{
              "width":120,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a6b36ca318448db96d3d4133f3fd1c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":695,
                  "y":205},
                "size":{
                  "width":120,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"921a61fea74c436fa9aaac994843b769",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":695,
              "y":321},
            "size":{
              "width":120,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23acd110b84b40678250c73906c4c313",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":695,
                  "y":321},
                "size":{
                  "width":120,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf949ec6f7ae43acb9f5e37bc30bf1ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":695,
              "y":282},
            "size":{
              "width":120,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e32356fbb16542c6a4d44b80a002f0b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":695,
                  "y":282},
                "size":{
                  "width":120,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25cc752bb9184c28b8b529422cd7cb2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":695,
              "y":398},
            "size":{
              "width":120,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7785144cb9b4782ac8add493ea08f73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":695,
                  "y":398},
                "size":{
                  "width":120,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69fd4590901845c3815bb36f4bc2aaff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":695,
              "y":359},
            "size":{
              "width":120,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"baa22d8ec0ba4ef7834b5b658bede10a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":695,
                  "y":359},
                "size":{
                  "width":120,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ff753c91370464a92c0419ffd66b0f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":695,
              "y":475},
            "size":{
              "width":120,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab7b3ecdbd2f4694ad3aa4ef31ce60aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":695,
                  "y":475},
                "size":{
                  "width":120,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df652e3902fc428faa1f48b2be3f284e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":695,
              "y":436},
            "size":{
              "width":120,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6751151338b44f418def35ee6956f26c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":695,
                  "y":436},
                "size":{
                  "width":120,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d81eec5a35848a9a2b61216879fe70c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":695,
              "y":552},
            "size":{
              "width":120,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60cc8df6407e4ee6ac3aa56c06159345",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":695,
                  "y":552},
                "size":{
                  "width":120,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2737f8490fd446e4b10e00c940ed1377",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":695,
              "y":513},
            "size":{
              "width":120,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e994d624b7564f86b692f94818c20957",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":695,
                  "y":513},
                "size":{
                  "width":120,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cbde520b398542bcab99f2f3d27d65b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":340,
              "y":205},
            "size":{
              "width":200,
              "height":167}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a9e974aa6284e7aadf74cddc064e986",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":340,
                  "y":205},
                "size":{
                  "width":200,
                  "height":167}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u63.png"}}]}},
  "masters":{
    "e163cbb4cef54461ad56955f368f2e96":{
      "packageId":"e163cbb4cef54461ad56955f368f2e96",
      "type":"Axure:Master",
      "name":"main",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1affd31496854a90aaf55cb21b7c1027",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF9F9F9},
              "size":{
                "width":1366,
                "height":768}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6b795c4f50714ccc8e66f16ce98c2618",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF9F9F9},
                  "size":{
                    "width":1366,
                    "height":768}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u1.png"}},
{
            "id":"cee52dc11a8744b0a43052d502487fd5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF1996C7},
              "size":{
                "width":1366,
                "height":50},
              "borderWidth":"-1",
              "outerShadow":{
                "on":true,
                "offsetX":0,
                "offsetY":1,
                "blurRadius":5,
                "color":{
                  "r":0,
                  "g":0,
                  "b":0,
                  "a":0.349019607843137}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bde88dba9c1a4e2988a327f1c196765c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF1996C7},
                  "size":{
                    "width":1366,
                    "height":50},
                  "borderWidth":"-1",
                  "outerShadow":{
                    "on":true,
                    "offsetX":0,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.349019607843137}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u3.png"}},
{
            "id":"56fbb49b18bd46129591d114da88345e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF1996C7},
              "location":{
                "x":0,
                "y":50},
              "size":{
                "width":1366,
                "height":4},
              "borderWidth":"-1",
              "outerShadow":{
                "on":true,
                "offsetX":0,
                "offsetY":1,
                "blurRadius":5,
                "color":{
                  "r":0,
                  "g":0,
                  "b":0,
                  "a":0.349019607843137}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b9154b46c7af49f6b3c8fa13b5e2aa9c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF1996C7},
                  "location":{
                    "x":0,
                    "y":50},
                  "size":{
                    "width":1366,
                    "height":4},
                  "borderWidth":"-1",
                  "outerShadow":{
                    "on":true,
                    "offsetX":0,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.349019607843137}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u5.png"}},
{
            "id":"8e7b142cf5d5486cbc949c1ae82f56d1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF212121},
              "location":{
                "x":0,
                "y":54},
              "size":{
                "width":250,
                "height":714},
              "borderWidth":"-1",
              "outerShadow":{
                "on":true,
                "offsetX":2,
                "offsetY":0,
                "blurRadius":5,
                "color":{
                  "r":0,
                  "g":0,
                  "b":0,
                  "a":0.349019607843137}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59e38fb539e04bb29cde628389cf5bd8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF212121},
                  "location":{
                    "x":0,
                    "y":54},
                  "size":{
                    "width":250,
                    "height":714},
                  "borderWidth":"-1",
                  "outerShadow":{
                    "on":true,
                    "offsetX":2,
                    "offsetY":0,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.349019607843137}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u7.png"}},
{
            "id":"dcdfff1ef73440ecb729883ed1488cee",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"28px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":31,
                "y":7},
              "size":{
                "width":59,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ee24b8d3672d4a26a4e0d5b9d8a0528a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"28px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":31,
                    "y":7},
                  "size":{
                    "width":59,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8d54821cdaf544ecb28f3ec8b3fa7703",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":446,
                "y":20},
              "size":{
                "width":185,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f8bd0ce314154ca0b0a2b663c0f86542",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":446,
                    "y":20},
                  "size":{
                    "width":185,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "6ca76bd3a37646f6afdb1eae79ca0167":{
      "scriptId":"u0",
      "1affd31496854a90aaf55cb21b7c1027":{
        "scriptId":"u1"},
      "6b795c4f50714ccc8e66f16ce98c2618":{
        "scriptId":"u2"},
      "cee52dc11a8744b0a43052d502487fd5":{
        "scriptId":"u3"},
      "bde88dba9c1a4e2988a327f1c196765c":{
        "scriptId":"u4"},
      "56fbb49b18bd46129591d114da88345e":{
        "scriptId":"u5"},
      "b9154b46c7af49f6b3c8fa13b5e2aa9c":{
        "scriptId":"u6"},
      "8e7b142cf5d5486cbc949c1ae82f56d1":{
        "scriptId":"u7"},
      "59e38fb539e04bb29cde628389cf5bd8":{
        "scriptId":"u8"},
      "dcdfff1ef73440ecb729883ed1488cee":{
        "scriptId":"u9"},
      "ee24b8d3672d4a26a4e0d5b9d8a0528a":{
        "scriptId":"u10"},
      "8d54821cdaf544ecb28f3ec8b3fa7703":{
        "scriptId":"u11"},
      "f8bd0ce314154ca0b0a2b663c0f86542":{
        "scriptId":"u12"}},
    "5f9cb2219b124226b2335a8c2aff1629":{
      "scriptId":"u13"},
    "20b0fe2e26c74df59ee490977594359c":{
      "scriptId":"u14"},
    "4392ad38465743e9b303dbd380d19b4d":{
      "scriptId":"u15"},
    "d2644655afe94273871a84092116f92f":{
      "scriptId":"u16"},
    "2ee13707ff0849878812458f5e9dc479":{
      "scriptId":"u17"},
    "e2060860d7344dd0b77bb37bdc6f498d":{
      "scriptId":"u18"},
    "fac55c7b7fcf4108a132986a10fb0f06":{
      "scriptId":"u19"},
    "53203faadd1b4a97b7d74f48e3fee9ae":{
      "scriptId":"u20"},
    "d985813d6da14de580d0bd3715008cc6":{
      "scriptId":"u21"},
    "3faa06ebbb2a478aaebba24628d4accf":{
      "scriptId":"u22"},
    "e00d00ba9a8f44cfa4f89056f4b7817b":{
      "scriptId":"u23"},
    "1640b83f076347db968d09cfa0d8b1bc":{
      "scriptId":"u24"},
    "a1c49d839a064ced836e243159f9c60d":{
      "scriptId":"u25"},
    "d810a9edc1f24b2e9f1744a364dbe828":{
      "scriptId":"u26"},
    "e29cb7db2be94848bfcdcb57452224ab":{
      "scriptId":"u27"},
    "7571390ff39f484faee67bd1e963ca4f":{
      "scriptId":"u28"},
    "59ab8a0faf6447aa828ec00810cbb1ce":{
      "scriptId":"u29"},
    "f9148cdeba524467928b7acc019a388f":{
      "scriptId":"u30"},
    "e600304e934048928d0f3cfc9943e785":{
      "scriptId":"u31"},
    "a124a7c60eea4e88896f03a0bced1699":{
      "scriptId":"u32"},
    "2569ab03fd9d48a0a60dfccfca6de872":{
      "scriptId":"u33"},
    "a275ffcf73894ed9a7010148c31337ce":{
      "scriptId":"u34"},
    "f24bd7fa6ff44fabb2dd62236432d2ab":{
      "scriptId":"u35"},
    "bb25aad5eb10475f9758560d0ac30926":{
      "scriptId":"u36"},
    "5a13ef5f512f46bb87b24598a182f181":{
      "scriptId":"u37"},
    "cf04e1b78d244121a6aeb395b1f1594a":{
      "scriptId":"u38"},
    "2923003e7a704601a0f3584691b70480":{
      "scriptId":"u39"},
    "c222949f927c4224b959bc5dc7aaa06b":{
      "scriptId":"u40"},
    "6e75ca8b7160495cb2223faca7229ea6":{
      "scriptId":"u41"},
    "037b42e1f326498ba46f24f3ff657b9b":{
      "scriptId":"u42"},
    "5fc3568350fd4cbebcf6e9f21e888178":{
      "scriptId":"u43"},
    "3adc04ecd098492a9f1bbbe7bfd1eb7a":{
      "scriptId":"u44"},
    "ff3cfcd607c640e5ba609824eceb836d":{
      "scriptId":"u45"},
    "1a6b36ca318448db96d3d4133f3fd1c8":{
      "scriptId":"u46"},
    "921a61fea74c436fa9aaac994843b769":{
      "scriptId":"u47"},
    "23acd110b84b40678250c73906c4c313":{
      "scriptId":"u48"},
    "cf949ec6f7ae43acb9f5e37bc30bf1ea":{
      "scriptId":"u49"},
    "e32356fbb16542c6a4d44b80a002f0b5":{
      "scriptId":"u50"},
    "25cc752bb9184c28b8b529422cd7cb2c":{
      "scriptId":"u51"},
    "a7785144cb9b4782ac8add493ea08f73":{
      "scriptId":"u52"},
    "69fd4590901845c3815bb36f4bc2aaff":{
      "scriptId":"u53"},
    "baa22d8ec0ba4ef7834b5b658bede10a":{
      "scriptId":"u54"},
    "8ff753c91370464a92c0419ffd66b0f5":{
      "scriptId":"u55"},
    "ab7b3ecdbd2f4694ad3aa4ef31ce60aa":{
      "scriptId":"u56"},
    "df652e3902fc428faa1f48b2be3f284e":{
      "scriptId":"u57"},
    "6751151338b44f418def35ee6956f26c":{
      "scriptId":"u58"},
    "0d81eec5a35848a9a2b61216879fe70c":{
      "scriptId":"u59"},
    "60cc8df6407e4ee6ac3aa56c06159345":{
      "scriptId":"u60"},
    "2737f8490fd446e4b10e00c940ed1377":{
      "scriptId":"u61"},
    "e994d624b7564f86b692f94818c20957":{
      "scriptId":"u62"},
    "cbde520b398542bcab99f2f3d27d65b8":{
      "scriptId":"u63"},
    "1a9e974aa6284e7aadf74cddc064e986":{
      "scriptId":"u64"}}});